Flow: flow::async::Timed_concurrent_task_loop_impl< Time_accumulator > Class Template Reference
flow::async::Timed_concurrent_task_loop_impl< Time_accumulator > Class Template Reference
Decorator of a Concurrent_task_loop with same or greater lifetime that accumulates time elapsed in any tasks posted or scheduled onto that loop.
#include <timed_concurrent_task_loop.hpp>
Public Types
using Exchanger_func = Function< perf::duration_rep_t(Time_accumulator *)>
Short-hand for the exhanger function taken by the ctor.
Public Types inherited from flow::async::Concurrent_task_loop
using Thread_init_func = Function< void(size_t thread_idx)>
Short-hand for the thread-initializer-function optional arg type to start().
Public Member Functions
Timed_concurrent_task_loop_impl (Concurrent_task_loop *loop, perf::Clock_type clock_type, Exchanger_func &&exchanger_func_moved)
Constructs a time-accumulating version of existing loop *loop.
void start (Task &&init_task_or_empty=Task(), const Thread_init_func &thread_init_func_or_empty=Thread_init_func()) override
Implements superclass API.
void stop () override
Implements superclass API.
size_t n_threads () const override
Implements superclass API.
Op create_op () override
Implements superclass API.
const Op_list & per_thread_ops () override
Implements superclass API.
void post (Task &&task, Synchronicity synchronicity=Synchronicity::S_ASYNC) override
Implements superclass API.
void post (const Op &op, Task &&task, Synchronicity synchronicity=Synchronicity::S_ASYNC) override
Implements superclass API.
util::Scheduled_task_handle schedule_from_now (const Fine_duration &from_now, Scheduled_task &&task) override
Implements superclass API.
util::Scheduled_task_handle schedule_at (const Fine_time_pt &at, Scheduled_task &&task) override
Implements superclass API.
util::Scheduled_task_handle schedule_from_now (const Op &op, const Fine_duration &from_now, Scheduled_task &&task) override
Implements superclass API.
util::Scheduled_task_handle schedule_at (const Op &op, const Fine_time_pt &at, Scheduled_task &&task) override
See superclass API.
Task_engine_ptr task_engine () override
See superclass API.
perf::Duration accumulated_time ()
Returns the accumulated time spent on tasks this thread pool handles since its last invocation; and reset the accumulated time.
template<typename Handler >
auto asio_handler_timed (Handler &&handler_moved)
Given a boost.asio completion handler handler for a boost.asio async_*() action on some boost.asio I/O object to be initiated in the immediate near future, returns a wrapped handler with the same signature to be passed as the handler arg to that async_*() action, so that handler() will be properly timed.
Public Member Functions inherited from flow::async::Concurrent_task_loop
~Concurrent_task_loop () override
Any implementing subclass's destructor shall execute stop() – see its doc header please – and then clean up any resources.
virtual void start (Task &&init_task_or_empty=Task(), const Thread_init_func &thread_init_func_or_empty=Thread_init_func())=0
Starts all threads in the thread pool; any queued post()ed (and similar) tasks may begin executing immediately; and any future posted work may execute in these threads.
virtual void stop ()=0
Waits for any ongoing task(s)/completion handler(s) to return; then prevents any further-queued such tasks from running; then gracefully stops/joins all threads in pool; and then returns.
virtual size_t n_threads () const =0
How many threads does start() start?
virtual Op create_op ()=0
Return a new Op which can bundle together an arbitrary set of post()s that would result in the provided task functions executing non-concurrently.
virtual const Op_list & per_thread_ops ()=0
Returns the optional-use, pre-created collection of per-thread async::Op objects, such that the i-th Op therein corresponds to the i-th (of N, where N = # of threads in this pool) thread.
virtual void post (Task &&task, Synchronicity synchronicity=Synchronicity::S_ASYNC)=0
Cause the given Task (function) to execute within the thread pool as soon as possible, in the first thread available, in otherwise first-come-first-served fashion.
virtual void post (const Op &op, Task &&task, Synchronicity synchronicity=Synchronicity::S_ASYNC)=0
Identical to the other post() with the added constraint that no other Task also similarly posted with the equivalent async::Op may execute concurrently.
virtual util::Scheduled_task_handle schedule_from_now (const Fine_duration &from_now, Scheduled_task &&task)=0
Equivalent to 2-argument post() but execution is scheduled for later, after the given time period passes.
virtual util::Scheduled_task_handle schedule_at (const Fine_time_pt &at, Scheduled_task &&task)=0
Equivalent to 2-argument schedule_from_now() except one specifies an absolute time point instead of wait duration.
virtual util::Scheduled_task_handle schedule_from_now (const Op &op, const Fine_duration &from_now, Scheduled_task &&task)=0
Equivalent to 3-argument post() but execution is scheduled for later, after the given time period passes.
virtual util::Scheduled_task_handle schedule_at (const Op &op, const Fine_time_pt &at, Scheduled_task &&task)=0
Equivalent to 3-argument schedule_from_now() except one specifies an absolute time point instead of wait duration.
virtual Task_engine_ptr task_engine ()=0
Returns a pointer to an internal util::Task_engine (a/k/a boost.asio io_context) for the purpose of performing a boost.asio async_*() action on some boost.asio I/O object in the immediate near future.
Public Member Functions inherited from flow::util::Null_interface
virtual ~Null_interface ()=0
Boring virtual destructor.
Private Attributes
const flow::perf::Clock_type m_clock_type
See constructor.
Concurrent_task_loop *const m_loop
See constructor.
const Exchanger_func m_exhanger_func
See constructor.
Time_accumulator m_time_accumulator
Accumulates time ticks, of clock type m_clock_type, spent in tasks posted onto m_loop.
Additional Inherited Members
Related Functions inherited from flow::async::Concurrent_task_loop
template<typename Exec_ctx_ptr >
Exec_ctx_ptr op_to_exec_ctx (Concurrent_task_loop *loop, const Op &op)
Template specialization model for operation that obtains the underlying execution context, such as a util::Task_engine or util::Strand, stored in an async::Op generated by the given Concurrent_task_loop.
Detailed Description
template<typename Time_accumulator>
class flow::async::Timed_concurrent_task_loop_impl< Time_accumulator >
Decorator of a Concurrent_task_loop with same or greater lifetime that accumulates time elapsed in any tasks posted or scheduled onto that loop.
While this class template is publicly available, most likely the user shall choose one of 2 related classes:
Timed_concurrent_task_loop: This is essentially an alias of Timed_concurrent_task_loop_impl<T>, where T is an atomic suitable for accumulating times from tasks executing across a multi-thread pool. Use this if you have a general Concurrent_task_loop (of whatever actual non-abstract type) which may at times use multiple threads. In other words use it if you want a Concurrent_task_loop... but timed.
Timed_single_thread_task_loop: This is a refinement (subclass) of Single_thread_task_loop. Internally it uses a Timed_concurrent_task_loop<perf::duration_rep_t>, since no atomic is needed with only 1 thread of execution. In other words use it if you want a Single_thread_task_loop... but timed.
See also
Timed_concurrent_task_loop doc header for instructions/synopsis of timing functionality.
Template Parameters
Time_accumulator As of this writing this should be either perf::duration_rep_t; or atomic<perf::duration_rep_t>, depending on whether the Timed_*_loop that uses this template instance is guaranteed to be single-threaded or potentially a multi-thread pool.
Definition at line 51 of file timed_concurrent_task_loop.hpp.
Member Typedef Documentation
Exchanger_func
template<typename Time_accumulator > using flow::async::Timed_concurrent_task_loop_impl< Time_accumulator >::Exchanger_func = Function<perf::duration_rep_t (Time_accumulator*)>
Short-hand for the exhanger function taken by the ctor.
Definition at line 57 of file timed_concurrent_task_loop.hpp.
Constructor & Destructor Documentation
Timed_concurrent_task_loop_impl()
template<typename Time_accumulator > flow::async::Timed_concurrent_task_loop_impl< Time_accumulator >::Timed_concurrent_task_loop_impl (Concurrent_task_loop * loop, perf::Clock_type clock_type, Exchanger_func && exchanger_func_moved) explicit
Constructs a time-accumulating version of existing loop *loop.
*loop must exist at least until *this is destroyed.
Parameters
clock_type See timed_function(). Use a perf::Clock_type that tracks thread time, not process time, typically. That said, in single-thread loops without competing concurrent work on the same machine, more precise non-per-thread clocks may be suitable (it is a trade-off).
loop The loop object being decorated with timing functionality.
exchanger_func_moved If A is a Time_accumulator, then exchanger_func_moved() must return the perf::duration_rep_t currently stored in A and – as atomically as possible – store 0 in A before returning that. More specifically, if Time_accumulator is an atomic, then use .exchange(0); if it's simply perf::duration_rep_t, then it can save the value, set it to 0, then return the saved thing (as concurrency is not a concern).
Definition at line 290 of file timed_concurrent_task_loop.hpp.
Member Function Documentation
accumulated_time()
template<typename Time_accumulator > perf::Duration flow::async::Timed_concurrent_task_loop_impl< Time_accumulator >::accumulated_time
Returns the accumulated time spent on tasks this thread pool handles since its last invocation; and reset the accumulated time.
See also
Constructor which controls the behavior of the timing.
Returns
See above.
Definition at line 385 of file timed_concurrent_task_loop.hpp.
Referenced by flow::async::Timed_single_thread_task_loop::accumulated_time().
asio_handler_timed()
template<typename Time_accumulator > template<typename Handler > auto flow::async::Timed_concurrent_task_loop_impl< Time_accumulator >::asio_handler_timed (Handler && handler_moved)
Given a boost.asio completion handler handler for a boost.asio async_*() action on some boost.asio I/O object to be initiated in the immediate near future, returns a wrapped handler with the same signature to be passed as the handler arg to that async_*() action, so that handler() will be properly timed.
The mechanics of using this are explained in the class doc header. Using this in any other fashion leads to undefined behavior.
Template Parameters
Handler See asio_handler_via_op(): same here.
Parameters
handler_moved Completion handler for the boost.asio async_*() operation to be initiated soon. It may be moved and saved.
Returns
A completion handler that will act as handler() but with the addition of timing as returned by accumulated_time().
Definition at line 392 of file timed_concurrent_task_loop.hpp.
References flow::perf::timed_handler().
Referenced by flow::async::Timed_single_thread_task_loop::asio_handler_timed().
create_op()
template<typename Time_accumulator > Op flow::async::Timed_concurrent_task_loop_impl< Time_accumulator >::create_op override virtual
Implements superclass API.
Returns
See superclass API.
Implements flow::async::Concurrent_task_loop.
Definition at line 320 of file timed_concurrent_task_loop.hpp.
n_threads()
template<typename Time_accumulator > size_t flow::async::Timed_concurrent_task_loop_impl< Time_accumulator >::n_threads override virtual
Implements superclass API.
Returns
See superclass API.
Implements flow::async::Concurrent_task_loop.
Definition at line 314 of file timed_concurrent_task_loop.hpp.
per_thread_ops()
template<typename Time_accumulator > const Op_list & flow::async::Timed_concurrent_task_loop_impl< Time_accumulator >::per_thread_ops override virtual
Implements superclass API.
Returns
See superclass API.
Implements flow::async::Concurrent_task_loop.
Definition at line 326 of file timed_concurrent_task_loop.hpp.
post() [1/2]
template<typename Time_accumulator > void flow::async::Timed_concurrent_task_loop_impl< Time_accumulator >::post (const Op & op, Task && task, Synchronicity synchronicity = Synchronicity::S_ASYNC) override virtual
Implements superclass API.
In this implementation: task will execute as soon as a thread is available, because no other applicable work is forthcoming, plus one more constraint: It will not allow task to execute concurrently to any other Task also associated with op. The latter is accomplished on account of Op internally being associated with a util::Strand.
Parameters
op See superclass API.
task See superclass API.
synchronicity See superclass API.
Implements flow::async::Concurrent_task_loop.
Definition at line 339 of file timed_concurrent_task_loop.hpp.
References flow::perf::timed_function().
post() [2/2]
template<typename Time_accumulator > void flow::async::Timed_concurrent_task_loop_impl< Time_accumulator >::post (Task && task, Synchronicity synchronicity = Synchronicity::S_ASYNC) override virtual
Implements superclass API.
In this implementation: task will execute as soon as a thread is available, because no other applicable work is forthcoming.
Parameters
task See superclass API.
synchronicity See superclass API.
Implements flow::async::Concurrent_task_loop.
Definition at line 332 of file timed_concurrent_task_loop.hpp.
References flow::perf::timed_function().
Referenced by flow::async::Timed_single_thread_task_loop::post().
schedule_at() [1/2]
template<typename Time_accumulator > util::Scheduled_task_handle flow::async::Timed_concurrent_task_loop_impl< Time_accumulator >::schedule_at (const Fine_time_pt & at, Scheduled_task && task) override virtual
Implements superclass API.
Parameters
at See superclass API.
task See superclass API.
Returns
See superclass API.
Implements flow::async::Concurrent_task_loop.
Definition at line 355 of file timed_concurrent_task_loop.hpp.
References flow::perf::timed_function().
Referenced by flow::async::Timed_single_thread_task_loop::schedule_at().
schedule_at() [2/2]
template<typename Time_accumulator > util::Scheduled_task_handle flow::async::Timed_concurrent_task_loop_impl< Time_accumulator >::schedule_at (const Op & op, const Fine_time_pt & at, Scheduled_task && task) override virtual
See superclass API.
Parameters
op See superclass API.
at See superclass API.
task See superclass API.
Returns
See superclass API.
Implements flow::async::Concurrent_task_loop.
Definition at line 371 of file timed_concurrent_task_loop.hpp.
References flow::perf::timed_function().
schedule_from_now() [1/2]
template<typename Time_accumulator > util::Scheduled_task_handle flow::async::Timed_concurrent_task_loop_impl< Time_accumulator >::schedule_from_now (const Fine_duration & from_now, Scheduled_task && task) override virtual
Implements superclass API.
Parameters
from_now See superclass API.
task See superclass API.
Returns
See superclass API.
Implements flow::async::Concurrent_task_loop.
Definition at line 347 of file timed_concurrent_task_loop.hpp.
References flow::perf::timed_function().
Referenced by flow::async::Timed_single_thread_task_loop::schedule_from_now().
schedule_from_now() [2/2]
template<typename Time_accumulator > util::Scheduled_task_handle flow::async::Timed_concurrent_task_loop_impl< Time_accumulator >::schedule_from_now (const Op & op, const Fine_duration & from_now, Scheduled_task && task) override virtual
Implements superclass API.
Parameters
op See superclass API.
from_now See superclass API.
task See superclass API.
Returns
See superclass API.
Implements flow::async::Concurrent_task_loop.
Definition at line 363 of file timed_concurrent_task_loop.hpp.
References flow::perf::timed_function().
start()
template<typename Time_accumulator > void flow::async::Timed_concurrent_task_loop_impl< Time_accumulator >::start (Task && init_task_or_empty = Task(), const Thread_init_func & thread_init_func_or_empty = Thread_init_func()) override virtual
Implements superclass API.
Parameters
init_task_or_empty See superclass API.
thread_init_func_or_empty See superclass API.
Implements flow::async::Concurrent_task_loop.
Definition at line 301 of file timed_concurrent_task_loop.hpp.
stop()
template<typename Time_accumulator > void flow::async::Timed_concurrent_task_loop_impl< Time_accumulator >::stop override virtual
Implements superclass API.
Implements flow::async::Concurrent_task_loop.
Definition at line 308 of file timed_concurrent_task_loop.hpp.
task_engine()
template<typename Time_accumulator > Task_engine_ptr flow::async::Timed_concurrent_task_loop_impl< Time_accumulator >::task_engine override virtual
See superclass API.
Returns
See superclass API.
Implements flow::async::Concurrent_task_loop.
Definition at line 379 of file timed_concurrent_task_loop.hpp.
Member Data Documentation
m_clock_type
template<typename Time_accumulator > const flow::perf::Clock_type flow::async::Timed_concurrent_task_loop_impl< Time_accumulator >::m_clock_type private
See constructor.
Definition at line 227 of file timed_concurrent_task_loop.hpp.
m_exhanger_func
template<typename Time_accumulator > const Exchanger_func flow::async::Timed_concurrent_task_loop_impl< Time_accumulator >::m_exhanger_func private
See constructor.
Definition at line 233 of file timed_concurrent_task_loop.hpp.
m_loop
template<typename Time_accumulator > Concurrent_task_loop* const flow::async::Timed_concurrent_task_loop_impl< Time_accumulator >::m_loop private
See constructor.
Definition at line 230 of file timed_concurrent_task_loop.hpp.
m_time_accumulator
template<typename Time_accumulator > Time_accumulator flow::async::Timed_concurrent_task_loop_impl< Time_accumulator >::m_time_accumulator private
Accumulates time ticks, of clock type m_clock_type, spent in tasks posted onto m_loop.
Definition at line 236 of file timed_concurrent_task_loop.hpp.
The documentation for this class was generated from the following files:
async/async_fwd.hpp
async/timed_concurrent_task_loop.hpp