Flow: flow::net_flow::asio::Server_socket Class Reference
flow::net_flow::asio::Server_socket Class Reference
A net_flow::Server_socket that adds integration with boost.asio.
#include <server_socket.hpp>
Public Types
using Ptr = boost::shared_ptr< Server_socket >
Short-hand for shared_ptr to Server_socket.
Public Types inherited from flow::net_flow::Server_socket
enum class State { S_LISTENING , S_CLOSING , S_CLOSED }
State of a Server_socket.
using Peer_socket_ptr = boost::shared_ptr< Peer_socket >
Equivalent to Peer_socket::Ptr, but can't use that due to C++'s circular reference nonsense.
Public Types inherited from flow::util::Shared_ptr_alias_holder< boost::shared_ptr< Server_socket > >
using Ptr = boost::shared_ptr< Server_socket >
Short-hand for ref-counted pointer to mutable values of type Target_type::element_type (a-la T*).
using Const_ptr = Const_target_ptr
Short-hand for ref-counted pointer to immutable values of type Target_type::element_type (a-la T const *).
Public Member Functions
~Server_socket () override
Boring virtual destructor as in superclass. See notes there.
util::Task_engine * async_task_engine ()
Pointer (possibly null) for the flow::util::Task_engine used by any coming async I/O calls and inherited by any subsequently generated Peer_socket objects.
const util::Task_engine & async_task_engine_cref () const
Read-only version of async_task_engine().
void set_async_task_engine (util::Task_engine *target_async_task_engine)
Overwrites the value to be returned by next async_task_engine().
template<typename Rep , typename Period , typename Handler >
void async_accept (const boost::chrono::duration< Rep, Period > &max_wait, bool reactor_pattern, const Handler &on_result)
boost.asio-style asynchronous version that essentially performs net_flow::Server_socket::sync_accept() in the background and invokes the given handler via the saved Task_engine *(async_task_engine()), as if by Task_engine::post().
template<typename Handler >
void async_accept (const Handler &on_result)
Equivalent to async_accept(duration::max(), false, on_result); i.e., async_accept() with no timeout and in normal – non-reactor-pattern – handler mode.
template<typename Rep , typename Period , typename Handler >
void async_accept (const boost::chrono::duration< Rep, Period > &max_wait, const Handler &on_result)
Equivalent to async_accept(max_wait, false, on_result); i.e., async_accept() with in normal – non-reactor-pattern – handler mode.
template<typename Handler >
void async_accept (bool reactor_pattern, const Handler &on_result)
Equivalent to async_accept(duration::max(), reactor_pattern, on_result); i.e., async_accept() with no timeout.
Public Member Functions inherited from flow::net_flow::Server_socket
~Server_socket () override
Boring virtual destructor. Note that deletion is to be handled exclusively via shared_ptr, never explicitly.
State state () const
Current State of the socket.
Node * node () const
Node that produced this Server_socket.
flow_port_t local_port () const
The local Flow-protocol port on which this server is or was listening.
Peer_socket_ptr accept (Error_code *err_code=0)
Non-blocking accept: obtain socket for the least recently established not-yet-obtained peer connection on this server.
template<typename Rep , typename Period >
Peer_socket_ptr sync_accept (const boost::chrono::duration< Rep, Period > &max_wait, bool reactor_pattern=false, Error_code *err_code=0)
Blocking (synchronous) version of accept().
Peer_socket_ptr sync_accept (bool reactor_pattern=false, Error_code *err_code=0)
Equivalent to sync_accept(duration::max(), reactor_pattern, err_code); i.e., sync_accept() with no user timeout.
Error_code disconnect_cause () const
The error code that perviously caused state() to become State::S_CLOSED, or success code if state is not CLOSED.
Public Member Functions inherited from flow::util::Null_interface
virtual ~Null_interface ()=0
Boring virtual destructor.
Public Member Functions inherited from flow::log::Log_context
Log_context (Logger *logger=0)
Constructs Log_context by storing the given pointer to a Logger and a null Component.
template<typename Component_payload >
Log_context (Logger *logger, Component_payload component_payload)
Constructs Log_context by storing the given pointer to a Logger and a new Component storing the specified generically typed payload (an enum value).
Log_context (const Log_context &src)
Copy constructor that stores equal Logger* and Component values as the source.
Log_context (Log_context &&src)
Move constructor that makes this equal to src, while the latter becomes as-if default-constructed.
Log_context & operator= (const Log_context &src)
Assignment operator that behaves similarly to the copy constructor.
Log_context & operator= (Log_context &&src)
Move assignment operator that behaves similarly to the move constructor.
void swap (Log_context &other)
Swaps Logger pointers and Component objects held by *this and other.
Logger * get_logger () const
Returns the stored Logger pointer, particularly as many FLOW_LOG_*() macros expect.
const Component & get_log_component () const
Returns reference to the stored Component object, particularly as many FLOW_LOG_*() macros expect.
Static Public Member Functions
static Ptr cast (net_flow::Server_socket::Ptr serv)
Convenience method that polymorphically casts from net_flow::Server_socket::Ptr to subclass pointer net_flow::asio::Server_socket::Ptr.
Static Public Member Functions inherited from flow::util::Shared_ptr_alias_holder< boost::shared_ptr< Server_socket > >
static Ptr ptr_cast (const From_ptr &ptr_to_cast)
Provides syntactic-sugary way to perform a static_pointer_cast<> from a compatible smart pointer type From_ptr, typically From_ptr::element_type being in the same class hierarchy as Target_ptr::element_type.
static Const_ptr const_ptr_cast (const From_ptr &ptr_to_cast)
Identical to ptr_cast() but adds const-ness (immutability) to the pointed-to type.
static Ptr dynamic_ptr_cast (const From_ptr &ptr_to_cast)
Equivalent to ptr_cast() but a dynamic_pointer_cast instead of static.
static Const_ptr dynamic_const_ptr_cast (const From_ptr &ptr_to_cast)
Identical to const_ptr_cast() but a dynamic_pointer_cast instead of static.
Private Types
using Handler_func = Function< void(const Error_code &err_code, Peer_socket::Ptr new_sock)>
Short-hand for the Task_engine-compatible accept Handler concrete type for class-internal code.
Private Member Functions
Server_socket (log::Logger *logger, const Peer_socket_options *child_sock_opts)
Constructs object.
void async_accept_impl (Handler_func &&on_result, const Fine_time_pt &wait_until, bool reactor_pattern)
De-templated implementation of all async_accept() methods.
template<typename Handler >
Handler_func handler_func (Handler &&on_result)
Returns a functor that essentially performs post() on_result onto *async_task_engine() in a way suitable for a boost.asio-compatible async-op.
Private Attributes
util::Task_engine * m_target_task_engine
See async_task_engine().
Friends
class Node
Similarly to the equivalent friend in net_flow::Peer_socket.
class net_flow::Node
As of this writing, it is needed for Node::serv_create_forward_plus_ctor_args().
Related Functions
(Note that these are not member functions.)
std::ostream & operator<< (std::ostream &os, const Server_socket *serv)
Prints string representation of given socket to given standard ostream and returns the latter.
Related Functions inherited from flow::net_flow::Server_socket
std::ostream & operator<< (std::ostream &os, const Server_socket *serv)
Prints string representation of given socket to given standard ostream and returns the latter.
std::ostream & operator<< (std::ostream &os, Server_socket::State state)
Prints string representation of given socket state to given standard ostream and returns the latter.
Additional Inherited Members
Protected Member Functions inherited from flow::net_flow::Server_socket
Server_socket (log::Logger *logger, const Peer_socket_options *child_sock_opts)
Constructs object; initializes most values to well-defined (0, empty, etc.) but not necessarily meaningful values.
Detailed Description
A net_flow::Server_socket that adds integration with boost.asio.
See net_flow::Node for a discussion of the topic of boost.asio integration. A net_flow::asio::Server_socket is a net_flow::Server_socket with all that functionality, plus APIs (mainly async_accept()) that accomplish boost.asio-style asynchronous operations with a standard boost::asio::io_service.
As of this writing, asio::Server_socket::Ptrs are generated by net_flow::Node::listen() and any derivatives. The underlying io_service (a/k/a flow::util::Task_engine) is carried forward from the net_flow::asio::Node factory object that generated and returned the Ptr. It can be overwritten via set_async_task_engine().
Definition at line 38 of file server_socket.hpp.
Member Typedef Documentation
Handler_func
using flow::net_flow::asio::Server_socket::Handler_func = Function<void (const Error_code& err_code, Peer_socket::Ptr new_sock)> private
Short-hand for the Task_engine-compatible accept Handler concrete type for class-internal code.
Definition at line 204 of file server_socket.hpp.
Ptr
using flow::net_flow::asio::Server_socket::Ptr = boost::shared_ptr<Server_socket>
Short-hand for shared_ptr to Server_socket.
Definition at line 46 of file server_socket.hpp.
Constructor & Destructor Documentation
~Server_socket()
flow::net_flow::asio::Server_socket::~Server_socket () override
Boring virtual destructor as in superclass. See notes there.
Definition at line 36 of file server_socket.cpp.
References FLOW_LOG_TRACE.
Server_socket()
flow::net_flow::asio::Server_socket::Server_socket (log::Logger * logger, const Peer_socket_options * child_sock_opts) explicit private
Constructs object.
Parameters
logger See superclass.
child_sock_opts See superclass.
Definition at line 28 of file server_socket.cpp.
References FLOW_LOG_TRACE.
Referenced by async_accept_impl().
Member Function Documentation
async_accept() [1/4]
template<typename Handler > void flow::net_flow::asio::Server_socket::async_accept (bool reactor_pattern, const Handler & on_result)
Equivalent to async_accept(duration::max(), reactor_pattern, on_result); i.e., async_accept() with no timeout.
Template Parameters
Handler See other async_accept().
Parameters
on_result See other async_accept().
reactor_pattern See other async_accept().
Definition at line 276 of file server_socket.hpp.
References async_accept_impl().
async_accept() [2/4]
template<typename Rep , typename Period , typename Handler > void flow::net_flow::asio::Server_socket::async_accept (const boost::chrono::duration< Rep, Period > & max_wait, bool reactor_pattern, const Handler & on_result)
boost.asio-style asynchronous version that essentially performs net_flow::Server_socket::sync_accept() in the background and invokes the given handler via the saved Task_engine *(async_task_engine()), as if by Task_engine::post().
The semantics are identical to the similar sync_accept(), except that the operation does not block the calling thread; and the results are delivered to the supplied handler on_result instead of to the caller.
Template Parameters
Rep See net_flow::Server_socket::accept().
Period See net_flow::Server_socket::accept().
Handler A type such that if Handler h, then a function equivalent to { h(err_code, sock); } can be post()ed onto an Task_engine, with const Error_code& err_code and net_flow::asio::Peer_socket sock.
Parameters
on_result Handler to be executed asynchronously within the saved Task_engine. The error code and socket values passed to it, in that order, are identical to those out-arg/returned values in net_flow::Server_socket::sync_accept(). Note: Use bind_executor(S, F) to bind your handler to the util::Strand S.
reactor_pattern See net_flow::Server_socket::sync_accept().
max_wait See net_flow::Server_socket::sync_accept().
Definition at line 260 of file server_socket.hpp.
References async_accept_impl(), and flow::util::chrono_duration_from_now_to_fine_time_pt().
async_accept() [3/4]
template<typename Rep , typename Period , typename Handler > void flow::net_flow::asio::Server_socket::async_accept (const boost::chrono::duration< Rep, Period > & max_wait, const Handler & on_result)
Equivalent to async_accept(max_wait, false, on_result); i.e., async_accept() with in normal – non-reactor-pattern – handler mode.
Template Parameters
Handler See other async_accept().
Parameters
on_result See other async_accept().
max_wait See other async_accept().
Definition at line 282 of file server_socket.hpp.
References async_accept_impl(), and flow::util::chrono_duration_from_now_to_fine_time_pt().
async_accept() [4/4]
template<typename Handler > void flow::net_flow::asio::Server_socket::async_accept (const Handler & on_result)
Equivalent to async_accept(duration::max(), false, on_result); i.e., async_accept() with no timeout and in normal – non-reactor-pattern – handler mode.
Template Parameters
Handler See other async_accept().
Parameters
on_result See other async_accept().
Definition at line 270 of file server_socket.hpp.
References async_accept_impl().
async_accept_impl()
void flow::net_flow::asio::Server_socket::async_accept_impl (Handler_func && on_result, const Fine_time_pt & wait_until, bool reactor_pattern) private
De-templated implementation of all async_accept() methods.
Parameters
on_result handler_func(on_result), where on_result is the user's async_*() method arg.
wait_until See max_wait arg on the originating async_accept() method. This is absolute timeout time point derived from it; zero-valued if no timeout.
reactor_pattern See async_accept().
Definition at line 60 of file server_socket.cpp.
References flow::net_flow::asio::Peer_socket::cast(), cast(), flow::net_flow::Server_socket::disconnect_cause(), FLOW_LOG_WARNING, m_target_task_engine, flow::net_flow::Server_socket::node(), flow::net_flow::Event_set::S_SERVER_SOCKET_ACCEPTABLE, and Server_socket().
Referenced by async_accept().
async_task_engine()
util::Task_engine * flow::net_flow::asio::Server_socket::async_task_engine ()
Pointer (possibly null) for the flow::util::Task_engine used by any coming async I/O calls and inherited by any subsequently generated Peer_socket objects.
One, this is used by this->async_accept() I/O calls, both synchronously and during the async phases of such calls, whenever placing a user-supplied handler routine onto an Task_engine. Whatever async_task_engine() returns at that time is the Task_engine used.
Two, when sync_accept() creates Peer_socket, at that moment this is used. Hence, the initial value returned by Peer_socket::async_task_engine() is thus inherited from the factory Server_socket's async_task_engine() result.
Thread safety (operating on a given Node)
set_async_task_engine() is the only way to change the returned value, upon construction.
It is not safe to call set_async_task_engine() at the same time as async_task_engine().
Define "any async op" as Server_socket::async_accept() and all its variants, including actions it takes in the background (asynchronously).
async_task_engine() must return the same value – and not null – throughout "any async op."
Define "any async inheriting op" as any (non-blocking) Server_socket::accept() method (which creates a Peer_socket.
async_task_engine() must return the same value – possibly null – throughout "any async inheriting op."
Put simply, a null Task_engine can be inherited by a generated socket, but a null cannot be used when performing an async op. Furthermore, set_async_task_engine() is unsafe through any of those and through async_task_engine() itself.
Informal tip: Typically you'd never call set_async_task_engine(), hence there is no problem. If you DO need to call it, even then normally it's easy to ensure one does this before any actual async calls are made. Trouble only begins if one calls set_async_task_engine() "in the middle" of operating the socket. There is no way to add outside locking to make that work, either, due to async "tails" of some calls.
Returns
Null or non-null pointer to Task_engine.
Definition at line 41 of file server_socket.cpp.
References m_target_task_engine.
Referenced by handler_func().
async_task_engine_cref()
const util::Task_engine & flow::net_flow::asio::Server_socket::async_task_engine_cref () const
Read-only version of async_task_engine().
Returns
Reference to read-only *(async_task_engine()).
Definition at line 47 of file server_socket.cpp.
References m_target_task_engine.
Referenced by operator<<().
cast()
Server_socket::Ptr flow::net_flow::asio::Server_socket::cast (net_flow::Server_socket::Ptr serv) static
Convenience method that polymorphically casts from net_flow::Server_socket::Ptr to subclass pointer net_flow::asio::Server_socket::Ptr.
Behavior undefined if serv is not actually of the latter type. With this, one needn't do verbose static_[pointer_]cast<> or similar conversions. For example: auto serv = asio::Server_socket::cast(node.listen(...)); where node is a net_flow::asio::Node&, and serv is auto-typed as net_flow::asio::Server_socket::Ptr.
Parameters
serv Handle to a serv such that the true underlying concrete type is net_flow::asio::Server_socket.
Returns
See above.
Definition at line 107 of file server_socket.cpp.
Referenced by async_accept_impl().
handler_func()
template<typename Handler > Server_socket::Handler_func flow::net_flow::asio::Server_socket::handler_func (Handler && on_result) private
Returns a functor that essentially performs post() on_result onto *async_task_engine() in a way suitable for a boost.asio-compatible async-op.
Rationale
See asio::Peer_socket::handler_func().
Template Parameters
Handler See async_accept().
Parameters
on_result See async_accept().
Returns
Function to call from any context that will properly post() on_result(); onto *async_task_engine().
Definition at line 291 of file server_socket.hpp.
References async_task_engine().
set_async_task_engine()
void flow::net_flow::asio::Server_socket::set_async_task_engine (util::Task_engine * target_async_task_engine)
Overwrites the value to be returned by next async_task_engine().
See async_task_engine() doc header before using this.
Parameters
target_async_task_engine See async_task_engine().
Definition at line 52 of file server_socket.cpp.
References FLOW_LOG_INFO, and m_target_task_engine.
Referenced by flow::net_flow::asio::Node::serv_create().
Friends And Related Function Documentation
net_flow::Node
friend class net_flow::Node friend
As of this writing, it is needed for Node::serv_create_forward_plus_ctor_args().
Definition at line 199 of file server_socket.hpp.
Node
friend class Node friend
Similarly to the equivalent friend in net_flow::Peer_socket.
Definition at line 197 of file server_socket.hpp.
operator<<()
std::ostream & operator<< (std::ostream & os, const Server_socket * serv) related
Prints string representation of given socket to given standard ostream and returns the latter.
The representation includes the local and remote endpoints and the hex pointer value.
Note
shared_ptr forwards ostream output to the underlying pointer type, so this will affect Ptr output as well.
Parameters
os Stream to print to.
serv Object to serialize. May be null.
Returns
os.
Definition at line 128 of file server_socket.cpp.
References async_task_engine_cref().
Member Data Documentation
m_target_task_engine
util::Task_engine* flow::net_flow::asio::Server_socket::m_target_task_engine private
See async_task_engine().
Definition at line 252 of file server_socket.hpp.
Referenced by async_accept_impl(), async_task_engine(), async_task_engine_cref(), and set_async_task_engine().
The documentation for this class was generated from the following files:
net_flow/asio/server_socket.hpp
net_flow/asio/server_socket.cpp
net_flow/net_flow_fwd.hpp