Flow: flow::net_flow::asio::Node Class Reference
flow::net_flow::asio::Node Class Reference
A subclass of net_flow::Node that adds the ability to easily and directly use net_flow sockets in general boost.asio event loops.
#include <node.hpp>
Public Member Functions
Node (log::Logger *logger, util::Task_engine *target_async_task_engine, const util::Udp_endpoint &low_lvl_endpoint, Net_env_simulator *net_env_sim=0, Error_code *err_code=0, const Node_options &opts=Node_options())
Constructs Node.
util::Task_engine * async_task_engine ()
Pointer (possibly null) for the flow::util::Task_engine used by any coming async I/O calls and inherited by any subsequently generated Server_socket and Peer_socket objects.
void set_async_task_engine (util::Task_engine *target_async_task_engine)
Overwrites the value to be returned by next async_task_engine().
template<typename Rep , typename Period , typename Handler >
void async_connect (const Remote_endpoint &to, const Handler &on_result, const boost::chrono::duration< Rep, Period > &max_wait, const Peer_socket_options *opts=0)
The boost.asio asynchronous version of sync_connect(), performing any necessary wait and connection in the background, and queueing the user-provided callback on the given boost.asio flow::util::Task_engine.
template<typename Rep , typename Period , typename Handler >
void async_connect_with_metadata (const Remote_endpoint &to, const Handler &on_result, const boost::chrono::duration< Rep, Period > &max_wait, const boost::asio::const_buffer &serialized_metadata, const Peer_socket_options *opts=0)
A combination of async_connect() and connect_with_metadata() (asynchronously blocking connect, with supplied metadata).
template<typename Handler >
void async_connect (const Remote_endpoint &to, const Handler &on_result, const Peer_socket_options *opts=0)
Equivalent to async_connect(to, on_result, duration::max(), opts); i.e., async_connect() with no user timeout.
template<typename Handler >
void async_connect_with_metadata (const Remote_endpoint &to, const Handler &on_result, const boost::asio::const_buffer &serialized_metadata, const Peer_socket_options *opts=0)
Equivalent to async_connect_with_metadata(to, on_result, duration::max(), serialized_metadata, opts); i.e., async_connect_with_metadata() with no user timeout.
Public Member Functions inherited from flow::net_flow::Node
Node (log::Logger *logger, const util::Udp_endpoint &low_lvl_endpoint, Net_env_simulator *net_env_sim=0, Error_code *err_code=0, const Node_options &opts=Node_options())
Constructs Node.
~Node () override
Destroys Node.
bool running () const
Returns true if and only if the Node is operating.
const util::Udp_endpoint & local_low_lvl_endpoint () const
Return the UDP endpoint (IP address and UDP port) which will be used for receiving incoming and sending outgoing Flow traffic in this Node.
Peer_socket::Ptr connect (const Remote_endpoint &to, Error_code *err_code=0, const Peer_socket_options *opts=0)
Initiates an active connect to the specified remote Flow server.
Peer_socket::Ptr connect_with_metadata (const Remote_endpoint &to, const boost::asio::const_buffer &serialized_metadata, Error_code *err_code=0, const Peer_socket_options *opts=0)
Same as connect() but sends, as part of the connection handshake, the user-supplied metadata, which the other side can access via Peer_socket::get_connect_metadata() after accepting the connection.
template<typename Rep , typename Period >
Peer_socket::Ptr sync_connect (const Remote_endpoint &to, const boost::chrono::duration< Rep, Period > &max_wait, Error_code *err_code=0, const Peer_socket_options *opts=0)
The blocking (synchronous) version of connect().
template<typename Rep , typename Period >
Peer_socket::Ptr sync_connect_with_metadata (const Remote_endpoint &to, const boost::chrono::duration< Rep, Period > &max_wait, const boost::asio::const_buffer &serialized_metadata, Error_code *err_code=0, const Peer_socket_options *opts=0)
A combination of sync_connect() and connect_with_metadata() (blocking connect, with supplied metadata).
Peer_socket::Ptr sync_connect (const Remote_endpoint &to, Error_code *err_code=0, const Peer_socket_options *opts=0)
Equivalent to sync_connect(to, duration::max(), err_code, opt)s; i.e., sync_connect() with no user timeout.
Peer_socket::Ptr sync_connect_with_metadata (const Remote_endpoint &to, const boost::asio::const_buffer &serialized_metadata, Error_code *err_code=0, const Peer_socket_options *opts=0)
Equivalent to sync_connect_with_metadata(to, duration::max(), serialized_metadata, err_code, opts); i.e., sync_connect_with_metadata() with no user timeout.
Server_socket::Ptr listen (flow_port_t local_port, Error_code *err_code=0, const Peer_socket_options *child_sock_opts=0)
Sets up a server on the given local Flow port and returns Server_socket which can be used to accept subsequent incoming connections to this server.
Event_set::Ptr event_set_create (Error_code *err_code=0)
Creates a new Event_set in Event_set::State::S_INACTIVE state with no sockets/events stored; returns this Event_set.
void interrupt_all_waits (Error_code *err_code=0)
Interrupts any blocking operation, a/k/a wait, and informs the invoker of that operation that the blocking operation's outcome was being interrupted.
bool set_options (const Node_options &opts, Error_code *err_code=0)
Dynamically replaces the current options set (options()) with the given options set.
Node_options options () const
Copies this Node's option set and returns that copy.
size_t max_block_size () const
The maximum number of bytes of user data per received or sent block on connections generated from this Node, unless this value is overridden in the Peer_socket_options argument to listen() or connect() (or friend).
Public Member Functions inherited from flow::util::Null_interface
virtual ~Null_interface ()=0
Boring virtual destructor.
Public Member Functions inherited from flow::log::Log_context
Log_context (Logger *logger=0)
Constructs Log_context by storing the given pointer to a Logger and a null Component.
template<typename Component_payload >
Log_context (Logger *logger, Component_payload component_payload)
Constructs Log_context by storing the given pointer to a Logger and a new Component storing the specified generically typed payload (an enum value).
Log_context (const Log_context &src)
Copy constructor that stores equal Logger* and Component values as the source.
Log_context (Log_context &&src)
Move constructor that makes this equal to src, while the latter becomes as-if default-constructed.
Log_context & operator= (const Log_context &src)
Assignment operator that behaves similarly to the copy constructor.
Log_context & operator= (Log_context &&src)
Move assignment operator that behaves similarly to the move constructor.
void swap (Log_context &other)
Swaps Logger pointers and Component objects held by *this and other.
Logger * get_logger () const
Returns the stored Logger pointer, particularly as many FLOW_LOG_*() macros expect.
const Component & get_log_component () const
Returns reference to the stored Component object, particularly as many FLOW_LOG_*() macros expect.
Private Types
using Handler_func = Function< void(const Error_code &err_code, Peer_socket::Ptr new_sock)>
Short-hand for the Task_engine-compatible connect Handler concrete type for class-internal code.
Private Member Functions
net_flow::Peer_socket * sock_create (const Peer_socket_options &opts) override
Implements superclass API.
net_flow::Server_socket * serv_create (const Peer_socket_options *child_sock_opts) override
Implements superclass API.
template<typename Socket , typename Base_socket , typename Non_blocking_func_ret_type >
void async_op (typename Socket::Ptr sock, Function< Non_blocking_func_ret_type(Error_code *)> &&non_blocking_func, Non_blocking_func_ret_type would_block_ret_val, Event_set::Event_type ev_type, const Fine_time_pt &wait_until, Function< void(const Error_code &, Non_blocking_func_ret_type)> &&on_result)
Implementation of core asynchronous transfer methods, namely asio::Peer_socket::async_send(), asio::Peer_socket::async_receive(), and asio::Server_socket::async_accept(), once the asio::Node has been obtain from socket in any one of those methods.
void async_connect_impl (const Remote_endpoint &to, const Fine_duration &max_wait, const boost::asio::const_buffer &serialized_metadata, const Peer_socket_options *opts, Handler_func &&on_result)
Implementation core of async_connect*() that gets rid of templated or missing arguments thereof.
template<typename Handler >
Handler_func handler_func (Handler &&on_result)
Returns a functor that essentially performs post() on_result onto *async_task_engine() in a way suitable for a boost.asio-compatible async-op.
Private Attributes
util::Task_engine * m_target_task_engine
See async_task_engine().
Friends
class Peer_socket
Peer_socket must be able to forward to async_op(), etc.
class Server_socket
Server_socket must be able to forward to async_op(), etc.
Additional Inherited Members
Static Public Attributes inherited from flow::net_flow::Node
static const size_t & S_NUM_PORTS = Port_space::S_NUM_PORTS
Total number of Flow ports in the port space, including S_PORT_ANY.
static const size_t & S_NUM_SERVICE_PORTS = Port_space::S_NUM_SERVICE_PORTS
Total number of Flow "service" ports (ones that can be reserved by number with Node::listen()).
static const size_t & S_NUM_EPHEMERAL_PORTS = Port_space::S_NUM_EPHEMERAL_PORTS
Total number of Flow "ephemeral" ports (ones reserved locally at random with Node::listen(S_PORT_ANY) or Node::connect()).
static const flow_port_t & S_FIRST_SERVICE_PORT = Port_space::S_FIRST_SERVICE_PORT
The port number of the lowest service port, making the range of service ports [S_FIRST_SERVICE_PORT, S_FIRST_SERVICE_PORT + S_NUM_SERVICE_PORTS - 1].
static const flow_port_t & S_FIRST_EPHEMERAL_PORT = Port_space::S_FIRST_EPHEMERAL_PORT
The port number of the lowest ephemeral Flow port, making the range of ephemeral ports [S_FIRST_EPHEMERAL_PORT, S_FIRST_EPHEMERAL_PORT + S_NUM_EPHEMERAL_PORTS - 1].
Protected Member Functions inherited from flow::net_flow::Node
template<typename Peer_socket_impl_type >
Peer_socket * sock_create_forward_plus_ctor_args (const Peer_socket_options &opts)
Returns a raw pointer to newly created Peer_socket or sub-instance like asio::Peer_socket, depending on the template parameter.
template<typename Server_socket_impl_type >
Server_socket * serv_create_forward_plus_ctor_args (const Peer_socket_options *child_sock_opts)
Like sock_create_forward_plus_ctor_args() but for Server_sockets.
Static Protected Attributes inherited from flow::net_flow::Node
static const uint8_t S_DEFAULT_CONN_METADATA = 0
Type and value to supply as user-supplied metadata in SYN, if user chooses to use [[a]sync_]connect() instead of [[a]sync_]connect_with_metadata().
Detailed Description
A subclass of net_flow::Node that adds the ability to easily and directly use net_flow sockets in general boost.asio event loops.
net_flow::Node, the superclass, provides the vast bulk of the functionality in this library, but the sockets it generates directly or indirectly (net_flow::Peer_socket, net_flow::Server_socket) cannot be used directly in a boost.asio event loop (see reference below for background). It is possible to use the vanilla net_flow::Node, etc., with any asynchronous event loop (boost.asio or native epoll or select()...) – notably by using a glue socket, as explained in Event_set doc header. However, for those using the boost.asio io_context as the app's core main loop, this is not as easy as what one might desire. (Side note: I personally strongly recommend using boost.asio event loops instead of rolling one's own or the many alternatives I have seen. It is also on its way to ending up in the C++ standard library. Lastly, such a loop is used internally to implement net_flow, so you know I like it, for what that's worth.)
Basically, if you use this asio::Node instead of net_flow::Node, then you get everything in the latter plus the ability to use Flow-protocol sockets {Server|Peer}_socket with boost.asio as easily as and similarly to how one uses boost::asio::ip::tcp::acceptor::async_*() and boost::asio::ip::tcp::socket::async_*(), respectively.
The usage pattern is simple, assuming you understand tha basics of net_flow::Node, net_flow::Server_socket, and net_flow::Peer_socket – and especially if you are familiar with boost.asio's built-in tcp::acceptor and tcp::socket (and, of course, boost::asio::io_context that ties them and many more I/O objects together).
First, simply create an asio::Node using the same form of constructor as you would with net_flow::Node, plus an arg that's a pointer to the subsequently used target boost.asio flow::util::Task_engine, which is memorized.
All facilities from the regular net_flow::Node are available on this object (plus some minor boost.asio ones).
Upon obtaining a net_flow::Server_socket::Ptr via listen(), cast it to its true polymorphic equivalent asio::Server_socket::Ptr, via convenience method net_flow::asio::Server_socket::cast(): auto serv = asio::Server_socket::cast(node.listen(...));.
All facilities from the superclass net_flow::Server_socket are available (plus some minor boost.asio ones).
Similarly cast any net_flow::Peer_socket::Ptr to asio equivalent for any peer socket returned by asio::Server_socket::accept() and asio::Node::connect() and similar.
All facilities from the superclass net_flow::Peer_socket are available (plus some minor boost.asio ones).
All Server_socket and Peer_socket objects created by the Node subsequently will inherit the Task_engine* supplied in Node constructor. However, you may overwrite these (or remove them, by setting to null) at any time via Node::set_async_task_engine(), Server_socket::set_async_task_engine(), Peer_socket::set_async_task_engine().
The only rule is this: net_flow::asio::X::async_task_engine() must not be null whenever one calls net_flow::asio::X::async_F(), where X is Node, Server_socket, or Peer_socket; and async_F() is some async operation added on top of base class net_flow::X (which typically features net_flow::X::F() and net_flow::X::sync_F() – the non-blocking and thread-blocking versions of F, respectively).
The automatic inheriting of Task_engine pointer is as follows: Node -listen-> Server_socket -accept-> Peer_socket <-connect- Node.
For each op inside an "arrow," I mean to include all forms of it (F includes: F(), sync_F(), async_F()).
This pattern is more practical/reasonable for us than the boost.asio pattern of each object memorizing its io_context reference in its explicit constructor. That is because we fully embrace the factory-of-shared-pointers pattern, and boost.asio doesn't use that pattern. We also provide an explicit mutator however.
We also allow for a null Task_engine* – except when async_*() is actually performed. (boost.asio I/O objects seem to require a real flow::util::Task_engine, even if not planning to do anything async. Note, though, that if you don't plan to do anything async with net_flow, then you can just use vanilla net_flow::Node. Bottom line, you have (on this topic) at least as much flexibility as with boost.asio built-in I/O objects.)
Having thus obtained asio::Server_socket and asio::Peer_socket objects (and assigned each their desired boost.asio io_context loop(s) – essentially as one does with, e.g., tcp::acceptor and tcp::socket respectively) – you many now use the full range of I/O operations. Here is a bird's eye view of all operations available in the entire hierarchy. Note that conceptually this is essentially identical to boost.asio tcp I/O objects, but nomenclature and API decisions are in some cases somewhat different (I contend: with good reason).
Non-blocking operations:
net_flow::Node::listen() -> net_flow::Server_socket: Create an object listening for connections.
Equivalent: tcp::acceptor constructor that takes a local endpoint arg.
net_flow::Server_socket::accept() -> net_flow::Peer_socket: Return a fully connected peer socket object, if one is immediately ready due to the listening done so far.
Equivalent: tcp::acceptor::accept() after ensuring tcp::acceptor::non_blocking(true). NetFlow null return value <-> TCP "would-block" error code.
net_flow::Node::connect() -> net_flow::Peer_socket: Return a connectING peer socket object immediately, as it tries to connected to the server socket on the remote side.
Equivalent: tcp::socket::connect() after ensuring tcp::socket::non_blocking(true).
Variations: see also *_with_metadata() for an added feature without direct TCP equivalent.
net_flow::Peer_socket::send(): Queue up at least 1 of the N given bytes to send to peer ASAP; or indicate no bytes could be immediately queued.
Equivalent: tcp::socket::send() after ensuring tcp::socket::non_blocking(true). NetFlow 0 return value <-> TCP "would-block" error code.
net_flow::Peer_socket::receive(): Dequeue at least 1 of the desired N bytes earlier received from peer; or indicate none were immediately available.
Equivalent: tcp::socket::receive() after ensuring tcp::socket::non_blocking(true). NetFlow 0 return value <-> TCP "would-block" error code.
Blocking operations:
net_flow::Server_socket::sync_accept() -> net_flow::Peer_socket: Return a fully connected peer socket object, blocking thread if necessary to wait for a connection to come in and fully establish.
Equivalent: tcp::acceptor::accept() after ensuring tcp::acceptor::non_blocking(false).
Variations: optional timeout can be specified.
Variations: reactor_pattern mode, where the accept() call itself is left to aftermath of sync_accept().
net_flow::Node::sync_connect() -> net_flow::Peer_socket: Return a connected peer socket object, blocking thread as needed to reach the remote server and fully establish connection.
Equivalent: tcp::socket::connect() after ensuring tcp::socket::non_blocking(false).
Variations: see also *_with_metadata() as above.
net_flow::Peer_socket::sync_send(): Queue up at least 1 of the N given bytes to send to peer ASAP, blocking thread if necessary to wait for this to become possible (internally, as determined by such things as flow control, congestion control, buffer size limits).
Equivalent: tcp::socket::send() after ensuring tcp::socket::non_blocking(false).
Variations: optional timeout can be specified.
Variations: nullptr_t mode, where the send() call itself is left to aftermath of sync_send().
net_flow::Peer_socket::sync_receive(): Dequeue at least 1 of the desired N bytes from peer, blocking thread if necessary to wait for this to arrive from said remote peer.
Equivalent: tcp::socket::receive() after ensuring tcp::socket::non_blocking(false).
Variations: optional timeout can be specified.
Variations: nullptr_t mode, where the receive() call itself is left to aftermath of sync_receive().
Asynchronous operations (asio::* classes provide these):
asio::Server_socket::async_accept() -> asio::Peer_socket: Obtain a fully connected peer socket object, waiting as necessary in background for a connection to come in and fully establish, then invoking user-provided callback as if by post(io_context&).
Equivalent: tcp::acceptor::async_accept().
Variations: optional timeout can be specified.
Variations: reactor_pattern mode, where the accept() call itself is left to user handler.
asio::Node::async_connect() -> net_flow::Peer_socket: Return a fully connected peer socket object, waiting as necessary in background to reach the remote server and fully establish connection, then invoking user-provided callback as if by post(io_context&).
Equivalent: tcp::socket::async_connect().
Variations: optional timeout can be specified.
Variations: see also *_with_metadata() as above.
asio::Peer_socket::async_send(): Queue up at least 1 of the N given bytes to send to peer ASAP, waiting as necessary in background for this to become possible (as explained above), then invoking user-provided callback as if by post(io_context&).
Equivalent: tcp::socket::async_send().
Variations: optional timeout can be specified.
Variations: nullptr_t mode, where the send() call itself is left to user handler.
asio::Peer_socket::async_receive(): Dequeue at least 1 of the desired N bytes from peer, waiting as necessary in background for this to arrive from said remote peer, then invoking user-provided callback as if by post(io_context&).
Equivalent: tcp::socket::async_receive().
Variations: optional timeout can be specified.
Variations: nullptr_t mode, where the receive() call itself is left to user handler.
Awaiting socket events (status):
Note that this is both a fundamental building block making much of the above work and simultaneously best to avoid using directly. In particular, boost.asio is (subjectively speaking) a way to write a cleaner event loop, and "Asynchronous operations" above allow Flow-protocol use with boost.asio proactors.
Event_set::add_wanted_socket(), Event_set::remove_wanted_socket(), Event_set::swap_wanted_sockets(), Event_set::clear_wanted_sockets(), and related: Specify the precise socket(s) for which to check on particular status; and the status(es) for which to wait (e.g., Readable, Writable, Acceptable).
Equivalent (select()): FD_SET(), FD_CLR(), FD_ZERO(), etc.
Equivalent (poll()): The input events array.
Event_set::sync_wait(): Synchronous I/O multiplexing, with indefinite blocking or finite timeout blocking.
Equivalent: select() with null timeout (indefinite) or non-null, non-zero timeout (finite).
Equivalent: poll() with -1 timeout (indefinite) or positive timeout (finite).
Event_set::poll(): Non-blocking I/O multiplexing, with an instant check for the socket status(es) of interest.
Equivalent: select() with non-null, zero timeout.
Equivalent: poll() with 0 timeout.
Event_set::async_wait(): Asynchronous I/O multiplixing, like sync_wait() but waits in background and executes user-provided callback from an unspecified thread. (A typical callback might set a future result; post(io_context&) a task to some boost.asio event loop; perhaps set a flag that is periodically checked by some user thread; or send a byte over some quick IPC mechanism like a POSIX domain socket or loopback UDP socket – or even a condition variable.)
Equivalents: none in POSIX, that I know of. Windows "overlapped" async I/O sounds vaguely like a distant cousin. boost.asio tcp::socket::async_* (async_wait() if relevant) can simulate it also, but that's like using a modern PC to emulate an old graphing calculator... it's only conceivably useful if you need to work with some old-school 3rd party I/O library perhaps.
Thread safety
See net_flow::Node thread safety notes.
The one exception to the "concurrent write access to one Node is thread-safe without added locking" is for set_async_task_engine(). See doc headers for async_task_engine() and set_async_task_engine() for more.
Thread safety of destructor
See net_flow::Node thready safety notes. Note, in particular, however, that as of this writing you may not let asio::Node destruct if there are outstanding {Node|Server|Peer}_socket::async_*() operations. The ability to early-destruct during sync_*() does not extend to async_*().
See also
boost.asio doc: https://www.boost.org/doc/libs/1_63_0/doc/html/boost_asio.html.
Superclass net_flow::Node, companion classes asio::Peer_socket and asio::Server_socket.
Todo:
To enable reactor-style async_*() operations, meaning waiting for readability/writability/etc. but not performing the actual operation before calling the user handler, we provide a nullptr_t-style interface; like newer boost.asio versions we should deprecate this in favor of simpler async_wait() APIs. This would apply to net_flow::asio::Peer_socket and net_flow::asio::Server_socket APIs. Similarly consider doing this for the sync_*() operations in the non-asio superclasses net_flow::Peer_socket and net_flow::Server_socket. Note that Event_set::async_wait() and Event_set::sync_wait() already exist; they are powerful but a bit complex to use in these simple situations. Hence the following hypothetical wrappers would be welcome replacements for the deprecated nullptr_t and "reactor-style" APIs in these classes: net_flow::Peer_socket::sync_wait(Event_set::Event_type), net_flow::asio::Peer_socket::async_wait(Event_set::Event_type), net_flow::Server_socket::sync_wait(), net_flow::Server_socket::async_wait(). (Timeout-arg versions would be desired also, as they exist now.)
The decision to make set_async_task_engine() thread-unsafe, by refusing to put locking around internal uses of m_target_task_engine – and in contrast to the rest of the main classes, which are generally thread-safe in this sense – was taken for the following reasons.
Less mandatory locking = avoids potential performance loss.
Realistically, set_async_task_engine() is not commonly used; and if it is used, it's tough to contrive a situation where one needs to call it while other threads are carrying on async operations – so potential performance loss would be to provide a guarantee that wouldn't be very useful.
Furthermore, it seems wrong to encourage wildly changing around the service throughout the socket's life. Just don't.
There are counter-arguments.
Saying Node is safe for concurrent access is easier and cleaner than saying that EXCEPT certain methods.
Well, that's a shame, but it's only a comment ultimately.
If one wanted to use set_async_task_engine() concurrently with the methods against which it is thread-unsafe, they couldn't: async operations would require access to async_task_engine() during their background work, and there's no good way to let user lock around those parts. In other words, we're not merely leaving locking to user; no user locking solution could possibly fully work.
That's a true concern, but on balance it is defeated by reasons 2 and 3 above. (Realistically – doubt anyone would care; and don't want to encourage them to do strange stuff.)
Todo:
The sync_*() early-destruction functionality explained in "Thread safety of destructor" above could be extended to async_*(). This is not a huge deal but would be nice for consistency. Not allowing it currently is really a result of internal implementation concerns (it is easier to not account for this corner case). Alternatively, maybe we should go the other way and not support the somewhat-weird corner case in sync_*().
Definition at line 234 of file node.hpp.
Member Typedef Documentation
Handler_func
using flow::net_flow::asio::Node::Handler_func = Function<void (const Error_code& err_code, Peer_socket::Ptr new_sock)> private
Short-hand for the Task_engine-compatible connect Handler concrete type for class-internal code.
Definition at line 462 of file node.hpp.
Constructor & Destructor Documentation
Node()
flow::net_flow::asio::Node::Node (log::Logger * logger, util::Task_engine * target_async_task_engine, const util::Udp_endpoint & low_lvl_endpoint, Net_env_simulator * net_env_sim = 0, Error_code * err_code = 0, const Node_options & opts = Node_options()) explicit
Constructs Node.
All docs from net_flow::Node::Node super-constructor apply.
The difference is you may supply a flow::util::Task_engine. More details below.
Parameters
logger See net_flow::Node::Node().
target_async_task_engine Initial value for async_task_engine(). For the effect this has see async_task_engine() doc header.
low_lvl_endpoint See net_flow::Node::Node().
net_env_sim See net_flow::Node::Node().
err_code See net_flow::Node::Node().
opts See net_flow::Node::Node().
Definition at line 29 of file node.cpp.
References FLOW_LOG_INFO.
Member Function Documentation
async_connect() [1/2]
template<typename Rep , typename Period , typename Handler > void flow::net_flow::asio::Node::async_connect (const Remote_endpoint & to, const Handler & on_result, const boost::chrono::duration< Rep, Period > & max_wait, const Peer_socket_options * opts = 0)
The boost.asio asynchronous version of sync_connect(), performing any necessary wait and connection in the background, and queueing the user-provided callback on the given boost.asio flow::util::Task_engine.
Acts just like connect() but instead of returning a connecting socket immediately, it returns and asycnhronously waits until the initial handshake either succeeds or fails, and then invokes the given callback (in manner equivalent to boost.asio post(Task_engine&)), passing to it the connected socket or null, respectively, along with a success Error_code or otherwise, respectively. Additionally, you can specify a timeout; not completing the connection by that time is a specific Error_code.
See subtleties about connect timeouts in Node::sync_connect() doc header.
The following are the possible outcomes, in ALL cases ending with an on_result() invocation post()ed onto Task_engine* async_task_engine() as follows: on_result(const Error_code& err_code, asio::Peer_socket::Ptr), with the 2 args determined as follows.
Connection succeeds before the given timeout expires (or succeeds, if no timeout given). Socket is at least Writable at time of return. The new socket and a success code are passed to callback.
Connection fails before the given timeout expires (or fails, if no timeout given). null is passed in, and a non-success Error_code is set to reason for connection failure and passed in. (Note that a built-in handshake timeout – NOT the given user timeout, if any – falls under this category.) Error_code error::Code::S_WAIT_INTERRUPTED means the wait was interrupted (similarly to POSIX's EINTR).
A user timeout is given, and the connection does not succeed before it expires. Reported similarly to 2, with specific code error::Code::S_WAIT_USER_TIMEOUT. (Rationale: consistent with Server_socket::sync_accept(), Peer_socket::sync_receive(), Peer_socket::sync_send() behavior.)
On success, the asio::Peer_socket::Ptr sock passed to on_result() will have sock->async_task_engine() == N->async_task_engine(), where N is the current Node. You can overwrite it subsequently if desired.
Tip: Typical types you might use for max_wait: boost::chrono::milliseconds, boost::chrono::seconds, boost::chrono::high_resolution_clock::duration.
Corner case: *this Node must exist throughout the async op, including when on_result() is actually executed in the appropriate thread.
error::Code other than success passed to on_result(): error::Code::S_WAIT_INTERRUPTED, error::Code::S_WAIT_USER_TIMEOUT, error::Code::S_NODE_NOT_RUNNING, error::Code::S_CANNOT_CONNECT_TO_IP_ANY, error::Code::S_OUT_OF_PORTS, error::Code::S_INTERNAL_ERROR_PORT_COLLISION, error::Code::S_CONN_TIMEOUT, error::Code::S_CONN_REFUSED, error::Code::S_CONN_RESET_BY_OTHER_SIDE, error::Code::S_NODE_SHUTTING_DOWN, error::Code::S_OPTION_CHECK_FAILED.
Template Parameters
Rep See boost::chrono::duration documentation (and see above tip).
Period See boost::chrono::duration documentation (and see above tip).
Handler A type such that if Handler h, then a function equivalent to { h(err_code, sock); } can be post()ed onto an Task_engine, with const Error_code& err_code and asio::Peer_socket::Ptr sock.
Parameters
to See connect().
on_result Callback whose invocation as explained above to add to *async_task_engine() as if by post(). Note: Use bind_executor(S, F) to bind your handler to the util::Strand S.
max_wait The maximum amount of time from now to wait before giving up on the wait and invoking on_result() with a timeout error code. "duration<Rep, Period>::max()" will eliminate the time limit and cause indefinite wait – however, not really, as there is a built-in connection timeout that will expire.
opts See connect().
Definition at line 916 of file node.hpp.
References async_connect_impl(), handler_func(), and flow::net_flow::Node::S_DEFAULT_CONN_METADATA.
async_connect() [2/2]
template<typename Handler > void flow::net_flow::asio::Node::async_connect (const Remote_endpoint & to, const Handler & on_result, const Peer_socket_options * opts = 0)
Equivalent to async_connect(to, on_result, duration::max(), opts); i.e., async_connect() with no user timeout.
Template Parameters
Handler See other async_connect().
Parameters
to See other async_connect().
on_result See other async_connect().
opts See other async_connect().
Definition at line 930 of file node.hpp.
References async_connect_impl(), handler_func(), and flow::net_flow::Node::S_DEFAULT_CONN_METADATA.
async_connect_impl()
void flow::net_flow::asio::Node::async_connect_impl (const Remote_endpoint & to, const Fine_duration & max_wait, const boost::asio::const_buffer & serialized_metadata, const Peer_socket_options * opts, Handler_func && on_result) private
Implementation core of async_connect*() that gets rid of templated or missing arguments thereof.
E.g., the API would wrap this and supply a Fine_duration instead of generic duration; and supply Fine_duration::max() if user omitted the timeout argument; and convert a generic function object into a concrete Function<> object. Code bloat and possible circular definition issues are among the reasons for this "de-templating" pattern.
Parameters
to See connect().
max_wait See the public async_connect(timeout). "duration<Rep, Period>::max()" maps to the value Fine_duration::max() for this argument.
serialized_metadata See connect_with_metadata().
opts See connect().
on_result handler_func(on_result), where on_result is the user's async_*() method arg.
Definition at line 171 of file peer_socket.cpp.
References async_task_engine(), flow::net_flow::asio::Peer_socket::cast(), flow::net_flow::Node::connect_with_metadata(), FLOW_LOG_TRACE, flow::net_flow::Peer_socket::S_CLOSED, and flow::net_flow::error::S_WAIT_USER_TIMEOUT.
Referenced by async_connect(), and async_connect_with_metadata().
async_connect_with_metadata() [1/2]
template<typename Handler > void flow::net_flow::asio::Node::async_connect_with_metadata (const Remote_endpoint & to, const Handler & on_result, const boost::asio::const_buffer & serialized_metadata, const Peer_socket_options * opts = 0)
Equivalent to async_connect_with_metadata(to, on_result, duration::max(), serialized_metadata, opts); i.e., async_connect_with_metadata() with no user timeout.
Template Parameters
Handler See other async_connect_with_metadata().
Parameters
to See other async_connect_with_metadata().
on_result See other async_connect_with_metadata().
serialized_metadata See other async_connect_with_metadata().
opts See other async_connect_with_metadata().
Definition at line 955 of file node.hpp.
References async_connect_impl(), and handler_func().
async_connect_with_metadata() [2/2]
template<typename Rep , typename Period , typename Handler > void flow::net_flow::asio::Node::async_connect_with_metadata (const Remote_endpoint & to, const Handler & on_result, const boost::chrono::duration< Rep, Period > & max_wait, const boost::asio::const_buffer & serialized_metadata, const Peer_socket_options * opts = 0)
A combination of async_connect() and connect_with_metadata() (asynchronously blocking connect, with supplied metadata).
Template Parameters
Rep See async_connect().
Period See async_connect().
Handler See async_connect().
Parameters
to See async_connect().
on_result See async_connect().
max_wait See async_connect().
serialized_metadata See connect_with_metadata().
opts See async_connect().
Definition at line 943 of file node.hpp.
References async_connect_impl(), and handler_func().
async_op()
template<typename Socket , typename Base_socket , typename Non_blocking_func_ret_type > void flow::net_flow::asio::Node::async_op (typename Socket::Ptr sock, Function< Non_blocking_func_ret_type(Error_code *)> && non_blocking_func, Non_blocking_func_ret_type would_block_ret_val, Event_set::Event_type ev_type, const Fine_time_pt & wait_until, Function< void(const Error_code &, Non_blocking_func_ret_type)> && on_result) private
Implementation of core asynchronous transfer methods, namely asio::Peer_socket::async_send(), asio::Peer_socket::async_receive(), and asio::Server_socket::async_accept(), once the asio::Node has been obtain from socket in any one of those methods.
It is inspired by design of net_flow::Node::sync_op().
Note the precise nature of on_result (see below).
Template Parameters
Socket Underlying object of the transfer operation (asio::Peer_socket or asio::Server_socket).
Base_socket Superclass of Socket.
Non_blocking_func_ret_type The return type of the calling transfer operation (size_t or asio::Peer_socket::Ptr).
Parameters
sock Socket on which user called async_*().
non_blocking_func When this method believes it should attempt a non-blocking transfer op, it will execute non_blocking_func(&err_code) with some Error_code err_code existing. If non_blocking_func.empty(), do not call non_blocking_func() – invoke on_result() indicating no error so far, and let them do actual operation, if they want; we just tell them it should be ready for them. This is known as reactor pattern mode. Otherwise, do the operation and then invoke on_result() with the resulting error code, possibly success. This is the proactor pattern mode and arguably more typical.
would_block_ret_val The value that non_blocking_func() returns to indicate it was unable to perform the non-blocking operation (i.e., no data/sockets available).
ev_type Event type applicable to the type of operation this is. See Event_set::Event_type doc header.
wait_until See max_wait argument on the originating async_*() method. This is absolute timeout time point derived from it; zero-valued if no timeout.
on_result A function that will properly post() the original on_result() from the originating async_*() method onto *async_task_engine(). This must be done carefully, preserving any associated executor of that original on_result handler.
Definition at line 581 of file node.hpp.
References async_op(), flow::net_flow::Node::event_set_create(), FLOW_ERROR_EMIT_ERROR, FLOW_LOG_INFO, FLOW_LOG_TRACE, flow::log::Log_context::get_logger(), flow::net_flow::error::S_WAIT_INTERRUPTED, flow::net_flow::error::S_WAIT_USER_TIMEOUT, flow::util::schedule_task_at(), and flow::util::scheduled_task_cancel().
Referenced by async_op().
async_task_engine()
util::Task_engine * flow::net_flow::asio::Node::async_task_engine ()
Pointer (possibly null) for the flow::util::Task_engine used by any coming async I/O calls and inherited by any subsequently generated Server_socket and Peer_socket objects.
One, this is used by Node::async_*() I/O calls, namely Node::async_connect() and all its variants, both synchronously and during the async phases of such calls, whenever placing a user-supplied handler routine onto an Task_engine. Whatever async_task_engine() returns at that time is the Task_engine used.
Two, when listen() creates Server_socket, or connect() creates Peer_socket, at that moment this is used. (Recall: [a]sync_connect() and variants will all call connect() internally.) Hence, the initial value returned by Peer_socket::async_task_engine() and Server_socket::async_task_engine() is thus inherited from the factory Node's async_task_engine() result.
Thread safety (operating on a given Node)
set_async_task_engine() is the only way to change the returned value, upon Node construction.
It is not safe to call set_async_task_engine() at the same time as async_task_engine().
Define "any Node async op" as Node::async_connect() and all its variants, including actions it takes in the background (asynchronously).
async_task_engine() must return the same value – and not null – throughout "any Node async op."
Define "any Node async inheriting op" as any non-blocking Node method that creates a Peer_socket or Server_socket (namely, connect(), listen(), and any variants).
Note that [a]sync_connect() (and variants) each invokes this non-blocking connect() at the start.
async_task_engine() must return the same value – possibly null – throughout "any Node async inheriting op."
Put simply, a null Task_engine can be inherited by a generated socket, but a null cannot be used when performing an async op. Furthermore, set_async_task_engine() is unsafe through any of those and through async_task_engine() itself.
Informal tip: Typically you'd never call set_async_task_engine(), hence there is no problem. If you DO need to call it, even then normally it's easy to ensure one does this before any actual async calls are made. Trouble only begins if one calls set_async_task_engine() "in the middle" of operating the socket. There is no way to add outside locking to make that work, either, due to async "tails" of some calls.
Returns
Null or non-null pointer to flow::util::Task_engine.
Definition at line 40 of file node.cpp.
References m_target_task_engine.
Referenced by async_connect_impl(), and handler_func().
handler_func()
template<typename Handler > Node::Handler_func flow::net_flow::asio::Node::handler_func (Handler && on_result) private
Returns a functor that essentially performs post() on_result onto *async_task_engine() in a way suitable for a boost.asio-compatible async-op.
Rationale
See asio::Peer_socket::handler_func().
Template Parameters
Handler See async_connect().
Parameters
on_result See async_connect().
Returns
Function to call from any context that will properly post() on_result(); onto *async_task_engine().
Definition at line 966 of file node.hpp.
References async_task_engine().
Referenced by async_connect(), and async_connect_with_metadata().
serv_create()
net_flow::Server_socket * flow::net_flow::asio::Node::serv_create (const Peer_socket_options * child_sock_opts) override private virtual
Implements superclass API.
Parameters
child_sock_opts See superclass API.
Returns
See superclass API.
Reimplemented from flow::net_flow::Node.
Definition at line 115 of file server_socket.cpp.
References m_target_task_engine, and flow::net_flow::asio::Server_socket::set_async_task_engine().
set_async_task_engine()
void flow::net_flow::asio::Node::set_async_task_engine (util::Task_engine * target_async_task_engine)
Overwrites the value to be returned by next async_task_engine().
See async_task_engine() doc header before using this.
Parameters
target_async_task_engine See async_task_engine().
Definition at line 46 of file node.cpp.
References FLOW_LOG_INFO, and m_target_task_engine.
sock_create()
net_flow::Peer_socket * flow::net_flow::asio::Node::sock_create (const Peer_socket_options & opts) override private virtual
Implements superclass API.
Parameters
opts See superclass API.
Returns
See superclass API.
Reimplemented from flow::net_flow::Node.
Definition at line 160 of file peer_socket.cpp.
References m_target_task_engine, and flow::net_flow::asio::Peer_socket::set_async_task_engine().
Friends And Related Function Documentation
Peer_socket
friend class Peer_socket friend
Peer_socket must be able to forward to async_op(), etc.
Definition at line 455 of file node.hpp.
Server_socket
friend class Server_socket friend
Server_socket must be able to forward to async_op(), etc.
Definition at line 457 of file node.hpp.
Member Data Documentation
m_target_task_engine
util::Task_engine* flow::net_flow::asio::Node::m_target_task_engine private
See async_task_engine().
Definition at line 575 of file node.hpp.
Referenced by async_task_engine(), serv_create(), set_async_task_engine(), and sock_create().
The documentation for this class was generated from the following files:
net_flow/asio/node.hpp
net_flow/asio/node.cpp
net_flow/asio/peer_socket.cpp
net_flow/asio/server_socket.cpp