Flow: flow::net_flow::Congestion_control_selector Class Reference
flow::net_flow::Congestion_control_selector Class Reference
Namespace-like class that enables an enum-based selection of the Congestion_control_strategy interface implementation to use for a given socket (for programmatic socket options) and facilitates stream I/O of these enums (allowing parsing and outputting these socket options).
#include <cong_ctl.hpp>
Public Types
using Strategy_choice = Peer_socket_options::Congestion_control_strategy_choice
Short-hand for Peer_socket_options::Congestion_control_strategy.
Static Public Member Functions
static Congestion_control_strategy * create_strategy (Strategy_choice strategy_choice, log::Logger *logger_ptr, Peer_socket::Const_ptr sock)
Factory method that, given an enum identifying the desired strategy, allocates the appropriate Congestion_control_strategy subclass instance on the heap and returns a pointer to it.
static void get_ids (std::vector< std::string > *ids)
Returns a list of strings, called IDs, each of which textually represents a distinct Congestion_control_strategy subclass.
Private Member Functions
Congestion_control_selector ()=delete
Forbid all instantiation.
Static Private Attributes
static const std::map< std::string, Strategy_choice > S_ID_TO_STRATEGY_MAP
Maps each ID to the corresponding Strategy_choice enum value.
static const std::map< Strategy_choice, std::string > S_STRATEGY_TO_ID_MAP
The inverse of S_ID_TO_STRATEGY_MAP.
Friends
std::istream & operator>> (std::istream &is, Congestion_control_selector::Strategy_choice &strategy_choice)
Deserializes a Peer_socket_options::Congestion_control_strategy_choice enum from a standard input stream.
std::ostream & operator<< (std::ostream &os, const Congestion_control_selector::Strategy_choice &strategy_choice)
Serializes a Peer_socket_options::Congestion_control_strategy_choice enum to a standard ostream – the reverse of operator>>().
Detailed Description
Namespace-like class that enables an enum-based selection of the Congestion_control_strategy interface implementation to use for a given socket (for programmatic socket options) and facilitates stream I/O of these enums (allowing parsing and outputting these socket options).
Provided facilities
Create Congestion_control_strategy subclass instance based on enum value;
Return set of possible text IDs, each representing a distinct enum value;
Read such an ID from an istream into an enum value; write an ID from an enum value to an ostream.
Definition at line 446 of file cong_ctl.hpp.
Member Typedef Documentation
Strategy_choice
using flow::net_flow::Congestion_control_selector::Strategy_choice = Peer_socket_options::Congestion_control_strategy_choice
Short-hand for Peer_socket_options::Congestion_control_strategy.
Definition at line 453 of file cong_ctl.hpp.
Member Function Documentation
create_strategy()
Congestion_control_strategy * flow::net_flow::Congestion_control_selector::create_strategy (Strategy_choice strategy_choice, log::Logger * logger_ptr, Peer_socket::Const_ptr sock) static
Factory method that, given an enum identifying the desired strategy, allocates the appropriate Congestion_control_strategy subclass instance on the heap and returns a pointer to it.
Parameters
strategy_choice The type of strategy (congestion control algorithm) to use.
logger_ptr The Logger implementation to use subsequently.
sock The Peer_socket for which this module will control congestion policy.
Returns
Pointer to newly allocated instance.
Definition at line 100 of file cong_ctl.cpp.
References flow::net_flow::Peer_socket_options::S_CLASSIC, and flow::net_flow::Peer_socket_options::S_CLASSIC_BANDWIDTH_ESTIMATED.
Referenced by flow::net_flow::Node::connect_worker(), and flow::net_flow::Node::handle_syn_to_listening_server().
get_ids()
void flow::net_flow::Congestion_control_selector::get_ids (std::vector< std::string > * ids) static
Returns a list of strings, called IDs, each of which textually represents a distinct Congestion_control_strategy subclass.
You can output this in socket option help text as the possible choices for congestion control strategy. They will match the possible text inputs to operator>>(istream&, Strategy_choice&).
Parameters
ids The vector of strings to clear and fill with the above.
Definition at line 115 of file cong_ctl.cpp.
References S_ID_TO_STRATEGY_MAP.
Referenced by flow::net_flow::Peer_socket_options::setup_config_parsing_helper().
Friends And Related Function Documentation
operator<<
std::ostream & operator<< (std::ostream & os, const Congestion_control_selector::Strategy_choice & strategy_choice) friend
Serializes a Peer_socket_options::Congestion_control_strategy_choice enum to a standard ostream – the reverse of operator>>().
Writes a space-less token to the given stream based on the given strategy enum value. This enables a few key things to work, including output of defaults and values in the help via Peer_socket_options, and conversion to string via boost::lexical_cast.
Parameters
os Stream to which to serialize.
strategy_choice Value to serialize.
Returns
os.
Definition at line 146 of file cong_ctl.cpp.
operator>>
std::istream & operator>> (std::istream & is, Congestion_control_selector::Strategy_choice & strategy_choice) friend
Deserializes a Peer_socket_options::Congestion_control_strategy_choice enum from a standard input stream.
Reads a single space-delimited token from the given stream. Maps that token to an aforementioned enumeration value. If the token is not recognized or cannot be read, some reasonable default strategy is chosen. This enables a few key things to work, including parsing from config file/command line via and conversion from string via boost::lexical_cast.
Parameters
is Stream from which to deserialize.
strategy_choice Reference to enum value which to set to the mapped strategy.
Returns
is.
Todo:
Peer_socket_options::Congestion_control_strategy_choice stream inserter << and >> operators should use the flow::util::istream_to_enum() pattern which is much easier than the overwrought old thing in there now involving two maps. Perhaps add a generic enum_to_strings() to provide the body for net_flow::Congestion_control_selector::get_ids().
Definition at line 124 of file cong_ctl.cpp.
Member Data Documentation
S_ID_TO_STRATEGY_MAP
const std::map< std::string, Congestion_control_selector::Strategy_choice > flow::net_flow::Congestion_control_selector::S_ID_TO_STRATEGY_MAP static private
Maps each ID to the corresponding Strategy_choice enum value.
Definition at line 496 of file cong_ctl.hpp.
Referenced by get_ids().
S_STRATEGY_TO_ID_MAP
const std::map< Congestion_control_selector::Strategy_choice, std::string > flow::net_flow::Congestion_control_selector::S_STRATEGY_TO_ID_MAP static private
The inverse of S_ID_TO_STRATEGY_MAP.
Definition at line 498 of file cong_ctl.hpp.
The documentation for this class was generated from the following files:
net_flow/detail/cong_ctl.hpp
net_flow/detail/cong_ctl.cpp