Flow: flow::net_flow::Congestion_control_classic Class Reference
flow::net_flow::Congestion_control_classic Class Reference
Classic congestion control, based on Reno (TCP RFC 5681), with congestion avoidance, slow start, and congestion window halving (etc.) upon a loss event.
#include <cong_ctl_classic.hpp>
Public Member Functions
Congestion_control_classic (log::Logger *logger_ptr, Peer_socket::Const_ptr sock)
Constructs object by setting up logging and saving a pointer to the containing Peer_socket.
size_t congestion_window_bytes () const override
Implements Congestion_control_strategy::congestion_window_bytes() API.
void on_acks (size_t bytes, size_t packets) override
Implements Congestion_control_strategy::on_acks() API.
void on_loss_event (size_t bytes, size_t packets) override
Implements Congestion_control_strategy::on_loss_event() API.
void on_drop_timeout (size_t bytes, size_t packets) override
Implements Congestion_control_strategy::on_drop_timeout() API.
void on_idle_timeout () override
Implements Congestion_control_strategy::on_idle_timeout() API.
Public Member Functions inherited from flow::net_flow::Congestion_control_strategy
virtual size_t congestion_window_bytes () const =0
Returns the maximal number of bytes (with respect to m_data field of DATA packets) that this socket should allow to be In-flight at this time.
virtual void on_acks (size_t bytes, size_t packets)
Informs the congestion control strategy that 1 or more previously sent packets whose status was In-flight just received acknowledgments, thus changing their state from In-flight to Acknowledged.
virtual void on_loss_event (size_t bytes, size_t packets)
Informs the congestion control strategy that 1 or more previously sent packets whose status was In-flight have just been inferred to be Dropped by receiving acknowledgments of packets that were sent later than the now-Dropped packets.
virtual void on_individual_ack (const Fine_duration &packet_rtt, const size_t bytes, const size_t sent_cwnd_bytes)
Informs the congestion control strategy that exactly 1 previously sent packet whose status was In-flight is now known to have the given round trip time (RTT), via acknowledgment.
virtual void on_drop_timeout (size_t bytes, size_t packets)
Informs the congestion control strategy that 1 or more previously sent packets whose status was In-flight have just been inferred to be Dropped because of the Drop Timer expiring.
virtual void on_idle_timeout ()
Informs the congestion control strategy that Node considers the connection to be "idle" by virtue of no desired send activity on the part of the user application for some period of time.
Public Member Functions inherited from flow::util::Null_interface
virtual ~Null_interface ()=0
Boring virtual destructor.
Public Member Functions inherited from flow::log::Log_context
Log_context (Logger *logger=nullptr)
Constructs Log_context by storing the given pointer to a Logger and a null Component.
template<typename Component_payload >
Log_context (Logger *logger, Component_payload component_payload)
Constructs Log_context by storing the given pointer to a Logger and a new Component storing the specified generically typed payload (an enum value).
Log_context (const Log_context &src)
Copy constructor that stores equal Logger* and Component values as the source.
Log_context (Log_context &&src)
Move constructor that makes this equal to src, while the latter becomes as-if default-constructed.
Log_context & operator= (const Log_context &src)
Assignment operator that behaves similarly to the copy constructor.
Log_context & operator= (Log_context &&src)
Move assignment operator that behaves similarly to the move constructor.
void swap (Log_context &other)
Swaps Logger pointers and Component objects held by *this and other.
Logger * get_logger () const
Returns the stored Logger pointer, particularly as many FLOW_LOG_*() macros expect.
Logger * set_logger (Logger *logger)
Sets the value to be returned by the next get_logger() call; returns get_logger() from before the change.
const Component & get_log_component () const
Returns reference to the stored Component object, particularly as many FLOW_LOG_*() macros expect.
Private Member Functions
unsigned int congestion_window_decay () const
Returns the decay (as a percentage) to apply to the congestion window upon encounterling loss.
Private Attributes
Congestion_control_classic_data m_classic_data
The Reno CWND/SSTHRESH-changing engine and CWND/SSTHRESH storage.
Additional Inherited Members
Protected Member Functions inherited from flow::net_flow::Congestion_control_strategy
Congestion_control_strategy (log::Logger *logger_ptr, Peer_socket::Const_ptr sock)
Constructs object by setting up logging and saving a pointer to the containing Peer_socket.
Peer_socket::Const_ptr socket () const
Utility for subclasses that returns a handle to the containing Peer_socket.
Detailed Description
Classic congestion control, based on Reno (TCP RFC 5681), with congestion avoidance, slow start, and congestion window halving (etc.) upon a loss event.
Implements Congestion_control_strategy abstract API.
The basic idea is: start with a narrow pipe. With each acknowledgment, grow the width of the pipe exponentially (a/k/a "slow start"). Eventually this will either hit the maximum width or cause loss. Once loss is detected, guess that the "steady-state" pipe width is about half of that at the point where loss occurred, set the pipe to that width and increase the pipe width but slowly (linearly) as acknowledgments arrive (a/k/a "congestion avoidance"). Eventually this will cause loss again: again guess pipe is half that width and start at that width and increase linearly (congestion avoidance again). Continue indefinitely. This results in the characteristic CWND vs. time graph, where CWND first explodes up, then goes up diagonally and vertically down, up, down, up, down, like a saw edge.
Additionally, on major loss (Drop Timeout), guess the steady state pipe width as above but reset the actual pipe width to its narrowest value. This will cause exponential growth again until the steady state pipe width is reached, then linear growth.
On idle timeout (when connection is seen as idle in the send direction), reset the pipe to its original narrow width but make no change to the steady-state pipe width.
The strength of this algorithm is that it's time-tested and saved the Internet from collapsing. The weakness is that once it encounters loss – which may well be random loss and not a sign of congestion – it backs off very conservatively (half). This means in a somewhat lossy environment one flow like this will fail to take advantage of the available bandwidth.
Note
The above refers to "half" the pipe width being used when backing off due to loss, as in classic Reno, but actually we make it configurable through socket options.
See also
Congestion_control_classic_with_bandwidth_est that acts similarly but instead of backing off conservatively to half (etc.) the pipe, backs off to an estimate as to the available pipe width based on a bandwidth estimator.
Definition at line 63 of file cong_ctl_classic.hpp.
Constructor & Destructor Documentation
Congestion_control_classic()
flow::net_flow::Congestion_control_classic::Congestion_control_classic (log::Logger * logger_ptr, Peer_socket::Const_ptr sock) explicit
Constructs object by setting up logging and saving a pointer to the containing Peer_socket.
Congestion window is chosen to be some small initial value, and an exponential congestion window growth is set up to continue indefinitely, until a loss event, drop timeout, or idle timeout.
Only a weak pointer of sock is stored: the shared_ptr itself is not saved, so the reference count of sock does not increase. This avoids a circular shared_ptr situation that would arise from *this pointing to sock, and sock pointing to *this (the two objects do need access to each other, as explained in class Congestion_control_strategy doc header).
Parameters
logger_ptr The Logger implementation to use subsequently.
sock The Peer_socket for which this module will control congestion policy.
Definition at line 25 of file cong_ctl_classic.cpp.
Member Function Documentation
congestion_window_bytes()
size_t flow::net_flow::Congestion_control_classic::congestion_window_bytes () const override virtual
Implements Congestion_control_strategy::congestion_window_bytes() API.
Returns
See Congestion_control_strategy::congestion_window_bytes().
Implements flow::net_flow::Congestion_control_strategy.
Definition at line 33 of file cong_ctl_classic.cpp.
References flow::net_flow::Congestion_control_classic_data::congestion_window_bytes(), and m_classic_data.
congestion_window_decay()
unsigned int flow::net_flow::Congestion_control_classic::congestion_window_decay () const private
Returns the decay (as a percentage) to apply to the congestion window upon encounterling loss.
RFC 5681-3.2.1 and formula (4) say this should 50 (i.e., halve it); but we make it configurable by a socket option.
Returns
A percentage in the range [1, 100].
Definition at line 164 of file cong_ctl_classic.cpp.
References flow::net_flow::Congestion_control_strategy::socket().
Referenced by on_drop_timeout(), and on_loss_event().
on_acks()
void flow::net_flow::Congestion_control_classic::on_acks (size_t bytes, size_t packets) override virtual
Implements Congestion_control_strategy::on_acks() API.
Congestion window grows either linearly (in congestion avoidance mode) or exponentially (in slow start mode). There is no congestion avoidance mode until at least one of on_loss_event() or on_drop_timeout() occurs; at least until then slow start is in effect.
Additional Peer_socket state used: none.
Parameters
bytes See Congestion_control_strategy::on_acks().
packets See Congestion_control_strategy::on_acks().
Reimplemented from flow::net_flow::Congestion_control_strategy.
Definition at line 38 of file cong_ctl_classic.cpp.
References m_classic_data, and flow::net_flow::Congestion_control_classic_data::on_acks().
on_drop_timeout()
void flow::net_flow::Congestion_control_classic::on_drop_timeout (size_t bytes, size_t packets) override virtual
Implements Congestion_control_strategy::on_drop_timeout() API.
Congestion window is set to a low value, while the next slow start session is set to end at roughly half (or some configurable constant fraction) of the current (pre-decrease) congestion window. Thus a slow start session begins.
Additional Peer_socket state used: Peer_socket::m_snd_flying_bytes (the # of bytes still In-flight after the loss event implied by the timeout).
Parameters
bytes See Congestion_control_strategy::on_drop_timeout().
packets See Congestion_control_strategy::on_drop_timeout().
Reimplemented from flow::net_flow::Congestion_control_strategy.
Definition at line 126 of file cong_ctl_classic.cpp.
References congestion_window_decay(), FLOW_LOG_TRACE, m_classic_data, flow::net_flow::Congestion_control_classic_data::on_drop_timeout(), and flow::net_flow::Congestion_control_strategy::socket().
on_idle_timeout()
void flow::net_flow::Congestion_control_classic::on_idle_timeout () override virtual
Implements Congestion_control_strategy::on_idle_timeout() API.
Congestion window is set to a low value. Thus a slow start session begins.
Additional Peer_socket state used: none.
Reimplemented from flow::net_flow::Congestion_control_strategy.
Definition at line 176 of file cong_ctl_classic.cpp.
References m_classic_data, and flow::net_flow::Congestion_control_classic_data::on_idle_timeout().
on_loss_event()
void flow::net_flow::Congestion_control_classic::on_loss_event (size_t bytes, size_t packets) override virtual
Implements Congestion_control_strategy::on_loss_event() API.
Congestion window changes to some configurable constant fraction (like half) of its current value, and the next slow start (if any, e.g., on a later Drop Timeout) will end once the congestion window exceeds this value. Thus after this call congestion avoidance mode begins anew.
Additional Peer_socket state used: Peer_socket::m_snd_flying_bytes (the # of bytes still In-flight after the loss event).
Parameters
bytes See Congestion_control_strategy::on_loss_event().
packets See Congestion_control_strategy::on_loss_event().
Reimplemented from flow::net_flow::Congestion_control_strategy.
Definition at line 46 of file cong_ctl_classic.cpp.
References congestion_window_decay(), FLOW_LOG_TRACE, m_classic_data, flow::net_flow::Congestion_control_classic_data::on_congestion_event(), and flow::net_flow::Congestion_control_strategy::socket().
Member Data Documentation
m_classic_data
Congestion_control_classic_data flow::net_flow::Congestion_control_classic::m_classic_data private
The Reno CWND/SSTHRESH-changing engine and CWND/SSTHRESH storage.
Definition at line 165 of file cong_ctl_classic.hpp.
Referenced by congestion_window_bytes(), on_acks(), on_drop_timeout(), on_idle_timeout(), and on_loss_event().
The documentation for this class was generated from the following files:
net_flow/detail/cong_ctl/cong_ctl_classic.hpp
net_flow/detail/cong_ctl/cong_ctl_classic.cpp