Flow: flow::net_flow::Congestion_control_classic_data Class Reference
flow::net_flow::Congestion_control_classic_data Class Reference
Utility class for use by Congestion_control_strategy implementations that implements congestion window and slow start threshold storage and classic Reno-style "slow start" and "congestion avoidance" algorithms.
#include <cong_ctl_util.hpp>
Public Member Functions
Congestion_control_classic_data (log::Logger *logger_ptr, Peer_socket::Const_ptr sock)
Constructs object by setting up logging and saving a pointer to the containing Peer_socket, setting CWND to a reasonable initial value (also known as Initial Window or IW) per classic TCP RFCs, and setting SSTHRESH to infinity (ditto).
size_t congestion_window_bytes () const
Return current stored CWND value in bytes.
size_t slow_start_threshold_bytes () const
Return current stored SSTHRESH value in bytes.
size_t init_congestion_window_bytes () const
The value to which the constructor set the stored CWND value (also known as Initial Window or IW).
void on_acks (size_t bytes)
Adjusts state, including potentially CWND, based on either "congestion avoidance" or "slow start" algorithm, given that packets with the given amount of data were just converted from In-flight to Acknowledged (i.e., were newly acknowledged).
void on_congestion_event (size_t new_slow_start_thresh_bytes, size_t new_cong_wnd_bytes)
Sets internally stored SSHTRESH and CWND to the given values; appropriately resets internal state so that on_acks() CWND accounting will continue to work properly.
void on_drop_timeout (size_t new_slow_start_thresh_bytes)
Adjust state, including CWND and SSTHRESH, assuming a Drop Timeout just occurred.
void on_idle_timeout ()
Adjust state, namely CWND, assuming an Idle Timeout just occurred.
Public Member Functions inherited from flow::log::Log_context
Log_context (Logger *logger=0)
Constructs Log_context by storing the given pointer to a Logger and a null Component.
template<typename Component_payload >
Log_context (Logger *logger, Component_payload component_payload)
Constructs Log_context by storing the given pointer to a Logger and a new Component storing the specified generically typed payload (an enum value).
Log_context (const Log_context &src)
Copy constructor that stores equal Logger* and Component values as the source.
Log_context (Log_context &&src)
Move constructor that makes this equal to src, while the latter becomes as-if default-constructed.
Log_context & operator= (const Log_context &src)
Assignment operator that behaves similarly to the copy constructor.
Log_context & operator= (Log_context &&src)
Move assignment operator that behaves similarly to the move constructor.
void swap (Log_context &other)
Swaps Logger pointers and Component objects held by *this and other.
Logger * get_logger () const
Returns the stored Logger pointer, particularly as many FLOW_LOG_*() macros expect.
const Component & get_log_component () const
Returns reference to the stored Component object, particularly as many FLOW_LOG_*() macros expect.
Private Member Functions
bool in_slow_start () const
Return true if and only if CWND < SSTHRESH.
bool congestion_window_at_limit () const
Returns true if and only if the stored CWND is >= a certain constant maximum value.
void clamp_congestion_window ()
If congestion_window_at_limit(), sets CWND to the limit value.
void log_state (const std::string &context) const
Logs, in a TRACE message, all internal state values.
Peer_socket::Const_ptr socket () const
Analogous to Congestion_control_strategy::socket().
Static Private Member Functions
static bool in_slow_start (size_t cong_wnd_bytes, size_t slow_start_thresh_bytes)
Helper that returns true if and only if the given CWND < the given SSTHRESH.
Private Attributes
boost::weak_ptr< Peer_socket::Const_ptr::element_type > m_sock
Same meaning as in Congestion_control_strategy.
size_t m_cong_wnd_bytes
Current value of CWND.
const size_t m_init_cong_wnd_bytes
Initial value of CWND in constructor.
size_t m_slow_start_thresh_bytes
Current value of SSTRESH.
size_t m_acked_bytes_since_window_update
While in congestion avoidance mode (!in_slow_start()), the # of acked bytes reported to on_acks() that have not yet been accounted for in a CWND increase.
Static Private Attributes
static const size_t S_MAX_SLOW_START_CWND_INCREMENT_BLOCKS = std::numeric_limits<size_t>::max()
The constant that limits how much CWND can grow in slow start for a single ack group.
Detailed Description
Utility class for use by Congestion_control_strategy implementations that implements congestion window and slow start threshold storage and classic Reno-style "slow start" and "congestion avoidance" algorithms.
While all (most?) congestion control algorithms store a CWND value, how each one computes or stores it is entirely up to the particular implementation. Thus each Congestion_control_strategy subclass can just store its own CWND data member, possibly an SSTHRESH data member, and re-implement slow start and congestion avoidance as needed.
However, many (most?) congestion control algorithms use the classic TCP congestion control (Reno) slow start and congestion avoidance algorithms. That is, upon acknowledgment, CWND increases either linearly (if CWND >= SSTRESH) or exponentially (CWND < SSTHRESH); these are "congestion avoidance" and "slow start" modes respectively. Where most (all?) Reno-based algorithms (e.g., Westwood+) differ is what they do to CWND when loss is detected; they may halve SSTHRESH and CWND or do some other thing. However, in almost all cases, at least in some situations CWND grows according to either SS or CA based on SSTHRESH. Therefore, for code reuse among the various Congestion_control_strategy implementations, this class stores CWND and SSTHRESH, increases the former when asked to (based on CWND vs. SSTHRESH), and sets SSTHRESH and CWND to arbitrary given values when asked to.
The Linux TCP implementation is kind of based on the same idea, wherein a Reno-style struct storing CWND, SSTHRESH, and acked-bytes-so-far values also has a pointer to a "polymorphic" struct corresponding to the custom congestion control implementation (e.g., a Westwood-specific struct storing its bandwidth estimation variables). Then when Westwood CC is enabled, its event handlers are set to Reno functions when classic SS and CA are to be performed and to Westwood functions when a Westwood-specific action is to be performed (set CWND to the bandwidth estimate * RTT-min). It's hard to put into words, but while the idea is the same, it's not really executed quite as cleanly as it could be. The Linux-equivalent implementation in our framework would be to have Congestion_control_classic store CWND and SSTHRESH and implement classic SS/CA as well as CWND/SSTHRESH halving, then add Congestion_control_classic_with_bandwidth_est deriving from this and try to alter the superclass's behavior through inheritance (CWND setting to bandwidth-based value). Instead of forcing this IS-A relationship (as Linux kind of does), it seems cleaner and more flexible to use a HAS-A relationship: Congestion_control_classic HAS-A Congestion_control_classic_data (and reuses all of its code, and adds SSTHRESH/CWND halving on loss); Congestion_control_classic_with_bandwidth_est HAS-A Congestion_control_classic_data (and reuses all of its code, plus adds setting SSTHRESH/CWND to a bandwidth-based value).
Documentation
Because this class explicitly implements Reno-style CWND growth, upon which any user class must be able to rely exactly, this class is uncharacteristically white-boxy in terms of its API and API documentation. Each method documents exactly what happens to CWND and SSTHRESH; and no CWND/SSTHRESH changes are allowed except as documented.
Thread safety
Same as Congestion_control_strategy.
Definition at line 76 of file cong_ctl_util.hpp.
Constructor & Destructor Documentation
Congestion_control_classic_data()
flow::net_flow::Congestion_control_classic_data::Congestion_control_classic_data (log::Logger * logger_ptr, Peer_socket::Const_ptr sock) explicit
Constructs object by setting up logging and saving a pointer to the containing Peer_socket, setting CWND to a reasonable initial value (also known as Initial Window or IW) per classic TCP RFCs, and setting SSTHRESH to infinity (ditto).
Parameters
logger_ptr The Logger implementation to use subsequently.
sock The Peer_socket.
Definition at line 33 of file cong_ctl_util.cpp.
References log_state().
Member Function Documentation
clamp_congestion_window()
void flow::net_flow::Congestion_control_classic_data::clamp_congestion_window () private
If congestion_window_at_limit(), sets CWND to the limit value.
Definition at line 352 of file cong_ctl_util.cpp.
References FLOW_LOG_TRACE, m_cong_wnd_bytes, and socket().
Referenced by on_acks(), and on_congestion_event().
congestion_window_at_limit()
bool flow::net_flow::Congestion_control_classic_data::congestion_window_at_limit () const private
Returns true if and only if the stored CWND is >= a certain constant maximum value.
Returns
Ditto.
Definition at line 345 of file cong_ctl_util.cpp.
References m_cong_wnd_bytes, and socket().
Referenced by on_acks().
congestion_window_bytes()
size_t flow::net_flow::Congestion_control_classic_data::congestion_window_bytes () const
Return current stored CWND value in bytes.
This corresponds to Congestion_control_strategy::congestion_window_bytes().
Returns
Ditto.
Definition at line 61 of file cong_ctl_util.cpp.
References m_cong_wnd_bytes.
Referenced by flow::net_flow::Congestion_control_classic::congestion_window_bytes(), and flow::net_flow::Congestion_control_classic_with_bandwidth_est::congestion_window_bytes().
in_slow_start() [1/2]
bool flow::net_flow::Congestion_control_classic_data::in_slow_start () const private
Return true if and only if CWND < SSTHRESH.
Returns
Ditto.
Definition at line 365 of file cong_ctl_util.cpp.
References in_slow_start(), m_cong_wnd_bytes, and m_slow_start_thresh_bytes.
Referenced by in_slow_start(), log_state(), on_acks(), and on_congestion_event().
in_slow_start() [2/2]
bool flow::net_flow::Congestion_control_classic_data::in_slow_start (size_t cong_wnd_bytes, size_t slow_start_thresh_bytes) static private
Helper that returns true if and only if the given CWND < the given SSTHRESH.
Parameters
cong_wnd_bytes CWND.
slow_start_thresh_bytes SSTHRESH.
Returns
See above.
Definition at line 370 of file cong_ctl_util.cpp.
init_congestion_window_bytes()
size_t flow::net_flow::Congestion_control_classic_data::init_congestion_window_bytes () const
The value to which the constructor set the stored CWND value (also known as Initial Window or IW).
This is provided, because some congestion control algorithms may want to manually set CWND back to this value on events like Idle Timeout.
Returns
See above.
Definition at line 66 of file cong_ctl_util.cpp.
References m_init_cong_wnd_bytes.
log_state()
void flow::net_flow::Congestion_control_classic_data::log_state (const std::string & context) const private
Logs, in a TRACE message, all internal state values.
Parameters
context A brief description of where the caller is. Preferably this should be lower-case letters with dashes separating words. We add this to the log message. Example: "ack-before".
Definition at line 375 of file cong_ctl_util.cpp.
References FLOW_LOG_TRACE, in_slow_start(), m_acked_bytes_since_window_update, m_cong_wnd_bytes, m_slow_start_thresh_bytes, and socket().
Referenced by Congestion_control_classic_data(), on_acks(), and on_congestion_event().
on_acks()
void flow::net_flow::Congestion_control_classic_data::on_acks (size_t bytes)
Adjusts state, including potentially CWND, based on either "congestion avoidance" or "slow start" algorithm, given that packets with the given amount of data were just converted from In-flight to Acknowledged (i.e., were newly acknowledged).
CWND may change. SSTHRESH will not change.
Specifically: If CWND < SSTHRESH, then each byte of acked data causes CWND to increase by that many bytes. If CWND >= SSTHRESH, then each CWND bytes of acked data causes CWND to be increased by N * max-block-size bytes (in max-block-size-at-a-time increments), where N is configurable by socket options (N = 1 is the value mandated by RFC 5681). State is internally maintained to enable the latter to work. This is inspired by the classic TCP congestion control combined with Appropriate Byte Counting (ABC).
Parameters
bytes Same meaning as for Congestion_Congestion_control_strategy::on_acks().
Definition at line 76 of file cong_ctl_util.cpp.
References clamp_congestion_window(), congestion_window_at_limit(), FLOW_LOG_INFO, FLOW_LOG_TRACE, in_slow_start(), log_state(), m_acked_bytes_since_window_update, m_cong_wnd_bytes, S_MAX_SLOW_START_CWND_INCREMENT_BLOCKS, and socket().
Referenced by flow::net_flow::Congestion_control_classic::on_acks(), and flow::net_flow::Congestion_control_classic_with_bandwidth_est::on_acks().
on_congestion_event()
void flow::net_flow::Congestion_control_classic_data::on_congestion_event (size_t new_slow_start_thresh_bytes, size_t new_cong_wnd_bytes)
Sets internally stored SSHTRESH and CWND to the given values; appropriately resets internal state so that on_acks() CWND accounting will continue to work properly.
See details inside the method if needed, but basically since the value of (CWND < SSTHRESH) may be changed by this assignment, we may move from congestion avoidance to slow start. If CWND changes at all, then a new congestion avoidance session begins if one is in progress. On the other hand if neither is true, then congestion avoidance or slow start will continue undisturbed in the next on_acks() call.
Parameters
new_slow_start_thresh_bytes New value for SSHTRESH. (May be unchanged.)
new_cong_wnd_bytes New value for CWND. (May be unchanged.)
Definition at line 228 of file cong_ctl_util.cpp.
References clamp_congestion_window(), in_slow_start(), log_state(), m_acked_bytes_since_window_update, m_cong_wnd_bytes, and m_slow_start_thresh_bytes.
Referenced by on_drop_timeout(), on_idle_timeout(), flow::net_flow::Congestion_control_classic::on_loss_event(), and flow::net_flow::Congestion_control_classic_with_bandwidth_est::on_loss_event().
on_drop_timeout()
void flow::net_flow::Congestion_control_classic_data::on_drop_timeout (size_t new_slow_start_thresh_bytes)
Adjust state, including CWND and SSTHRESH, assuming a Drop Timeout just occurred.
This is typically treated similarly in most (all?) congestion control strategies, so it is factored out into a method. (The caller can of course choose to perform additional steps before or after.) Both CWND and SSTHRESH will change.
Specifically: Sets CWND to a low value, since Drop Timeout indicates a major loss event and possibly major congestion; sets SSTHRESH to the given value (which is highly dependent on the caller congestion control strategy). The CWND part is taken from classic TCP congestion control.
Logging: logs the before/after states of the change, but caller is encouraged to explain what it is about to do (e.g., halve SSTHRESH in case of classic Reno).
Parameters
new_slow_start_thresh_bytes New value for SSHTRESH. (May be unchanged.)
Definition at line 293 of file cong_ctl_util.cpp.
References on_congestion_event(), and socket().
Referenced by flow::net_flow::Congestion_control_classic::on_drop_timeout(), and flow::net_flow::Congestion_control_classic_with_bandwidth_est::on_drop_timeout().
on_idle_timeout()
void flow::net_flow::Congestion_control_classic_data::on_idle_timeout ()
Adjust state, namely CWND, assuming an Idle Timeout just occurred.
This is typically treated similarly in most (all?) congestion control strategies, so it is factored out into a method. (The caller can of course choose to perform additional steps before or after.) CWND will change. SSTHRESH will not change.
Specifically: Sets CWND to a low value (the initial window), thus in effect restarting the connection (except SSTHRESH is left alone). The policy is taken from classic TCP congestion control.
Logs fully.
Definition at line 312 of file cong_ctl_util.cpp.
References FLOW_LOG_TRACE, m_cong_wnd_bytes, m_init_cong_wnd_bytes, m_slow_start_thresh_bytes, on_congestion_event(), and socket().
Referenced by flow::net_flow::Congestion_control_classic::on_idle_timeout(), and flow::net_flow::Congestion_control_classic_with_bandwidth_est::on_idle_timeout().
slow_start_threshold_bytes()
size_t flow::net_flow::Congestion_control_classic_data::slow_start_threshold_bytes () const
Return current stored SSTHRESH value in bytes.
When congestion_window_bytes() >= this value, it grows according to congestion avoidance mode (linearly). Otherwise it grows according to slow start mode (exponentially).
Returns
See above. Infinity is "numeric_limits<size_t>::max()".
Definition at line 71 of file cong_ctl_util.cpp.
References m_slow_start_thresh_bytes.
socket()
Peer_socket::Const_ptr flow::net_flow::Congestion_control_classic_data::socket () const private
Analogous to Congestion_control_strategy::socket().
Returns
Ditto.
Definition at line 390 of file cong_ctl_util.cpp.
References m_sock.
Referenced by clamp_congestion_window(), congestion_window_at_limit(), log_state(), on_acks(), on_drop_timeout(), and on_idle_timeout().
Member Data Documentation
m_acked_bytes_since_window_update
size_t flow::net_flow::Congestion_control_classic_data::m_acked_bytes_since_window_update private
While in congestion avoidance mode (!in_slow_start()), the # of acked bytes reported to on_acks() that have not yet been accounted for in a CWND increase.
This corresponds to the bytes_acked variable in TCP RFC 3465-2.1. When in_slow_start(), this value is zero and unused.
More formally, the congestion avoidance (CA) algorithm with Appropriate Byte Counting (ABC), as implemented here, works as follows. When CA is entered, m_acked_bytes_since_window_update = 0. Then, in every on_acks() call, it is incremented by bytes. Once it exceeds CWND, CWND bytes are "converted" into a CWND increase of N * max-block-size bytes, by performing said CWND increment and subtracting the pre-increment CWND value from m_acked_bytes_since_window_update. The remainder of this operation is less than CWND and is in m_acked_bytes_since_window_update. The latter is then incremented in the next on_acks(), and so on, until CA ends (something causes in_slow_start()).
Definition at line 277 of file cong_ctl_util.hpp.
Referenced by log_state(), on_acks(), and on_congestion_event().
m_cong_wnd_bytes
size_t flow::net_flow::Congestion_control_classic_data::m_cong_wnd_bytes private
Current value of CWND.
Definition at line 255 of file cong_ctl_util.hpp.
Referenced by clamp_congestion_window(), congestion_window_at_limit(), congestion_window_bytes(), in_slow_start(), log_state(), on_acks(), on_congestion_event(), and on_idle_timeout().
m_init_cong_wnd_bytes
const size_t flow::net_flow::Congestion_control_classic_data::m_init_cong_wnd_bytes private
Initial value of CWND in constructor.
Definition at line 258 of file cong_ctl_util.hpp.
Referenced by init_congestion_window_bytes(), and on_idle_timeout().
m_slow_start_thresh_bytes
size_t flow::net_flow::Congestion_control_classic_data::m_slow_start_thresh_bytes private
Current value of SSTRESH.
Definition at line 261 of file cong_ctl_util.hpp.
Referenced by in_slow_start(), log_state(), on_congestion_event(), on_idle_timeout(), and slow_start_threshold_bytes().
m_sock
boost::weak_ptr<Peer_socket::Const_ptr::element_type> flow::net_flow::Congestion_control_classic_data::m_sock private
Same meaning as in Congestion_control_strategy.
Definition at line 252 of file cong_ctl_util.hpp.
Referenced by socket().
S_MAX_SLOW_START_CWND_INCREMENT_BLOCKS
const size_t flow::net_flow::Congestion_control_classic_data::S_MAX_SLOW_START_CWND_INCREMENT_BLOCKS = std::numeric_limits<size_t>::max() static private
The constant that limits how much CWND can grow in slow start for a single ack group.
In on_acks(), while in_slow_start(), each byte acknowledged increments CWND by 1 byte. However, if the total number of such bytes exceeds this constant, CWND only increments by this constant times max-block-size.
Definition at line 247 of file cong_ctl_util.hpp.
Referenced by on_acks().
The documentation for this class was generated from the following files:
net_flow/detail/cong_ctl/cong_ctl_util.hpp
net_flow/detail/cong_ctl/cong_ctl_util.cpp