Flow: flow::net_flow::asio::Peer_socket Class Reference
flow::net_flow::asio::Peer_socket Class Reference
A net_flow::Peer_socket that adds integration with boost.asio.
#include <peer_socket.hpp>
Public Types
using Ptr = boost::shared_ptr< Peer_socket >
Short-hand for shared_ptr to Peer_socket.
Public Types inherited from flow::net_flow::Peer_socket
enum class State { S_OPEN , S_CLOSED }
State of a Peer_socket.
enum class Open_sub_state { S_CONNECTING , S_CONNECTED , S_DISCONNECTING }
The sub-state of a Peer_socket when state is State::S_OPEN.
Public Types inherited from flow::util::Shared_ptr_alias_holder< boost::shared_ptr< Peer_socket > >
using Ptr = boost::shared_ptr< Peer_socket >
Short-hand for ref-counted pointer to mutable values of type Target_type::element_type (a-la T*).
using Const_ptr = Const_target_ptr
Short-hand for ref-counted pointer to immutable values of type Target_type::element_type (a-la T const *).
Public Member Functions
~Peer_socket () override
Boring virtual destructor as in superclass. See notes there.
util::Task_engine * async_task_engine ()
Pointer (possibly null) for the flow::util::Task_engine used by any coming async_*() I/O calls.
const util::Task_engine & async_task_engine_cref () const
Read-only version of async_task_engine().
void set_async_task_engine (util::Task_engine *target_async_task_engine)
Overwrites the value to be returned by next async_task_engine().
template<typename Rep , typename Period , typename Mutable_buffer_sequence , typename Handler >
void async_receive (const Mutable_buffer_sequence &target, const boost::chrono::duration< Rep, Period > &max_wait, Handler &&on_result)
boost.asio-style asynchronous version that essentially performs non-nullptr_t net_flow::Peer_socket::sync_receive() in the background and invokes the given handler via the saved Task_engine *(async_task_engine()), as if by post(Task_engine&).
template<typename Rep , typename Period , typename Handler >
void async_receive (std::nullptr_t, const boost::chrono::duration< Rep, Period > &max_wait, Handler &&on_result)
boost.asio-style asynchronous version that essentially performs a nullptr_t net_flow::Peer_socket::sync_receive() in the background and invokes the given handler via the saved Task_engine *(async_task_engine()), as if by post(Task_engine&).
template<typename Mutable_buffer_sequence , typename Handler >
void async_receive (const Mutable_buffer_sequence &target, Handler &&on_result)
Equivalent to async_receive(target, duration::max(), on_result); i.e., async_receive() with no timeout.
template<typename Handler >
void async_receive (std::nullptr_t, Handler &&on_result)
Equivalent to async_receive(nullptr, duration::max(), on_result); i.e., async_receive(nullptr) with no timeout.
template<typename Rep , typename Period , typename Const_buffer_sequence , typename Handler >
void async_send (const Const_buffer_sequence &source, const boost::chrono::duration< Rep, Period > &max_wait, Handler &&on_result)
boost.asio-style asynchronous version that essentially performs non-nullptr_t net_flow::Peer_socket::sync_send() in the background and invokes the given handler via the saved Task_engine *(async_task_engine()), as if by post(Task_engine&).
template<typename Rep , typename Period , typename Handler >
void async_send (std::nullptr_t, const boost::chrono::duration< Rep, Period > &max_wait, Handler &&on_result)
boost.asio-style asynchronous version that essentially performs a nullptr_t net_flow::Peer_socket::sync_send() in the background and invokes the given handler via the saved Task_engine *(async_task_engine()), as if by post(Task_engine&).
template<typename Const_buffer_sequence , typename Handler >
void async_send (const Const_buffer_sequence &source, Handler &&on_result)
Equivalent to async_send(target, duration::max(), on_result); i.e., async_send() with no timeout.
template<typename Handler >
void async_send (std::nullptr_t, Handler &&on_result)
Equivalent to async_send(nullptr, duration::max(), on_result); i.e., async_send(nullptr) with no timeout.
Public Member Functions inherited from flow::net_flow::Peer_socket
~Peer_socket () override
Boring virtual destructor. Note that deletion is to be handled exclusively via shared_ptr, never explicitly.
State state (Open_sub_state *open_sub_state=0) const
Current State of the socket.
Node * node () const
Node that produced this Peer_socket.
const Remote_endpoint & remote_endpoint () const
Intended other side of the connection (regardless of success, failure, or current State).
flow_port_t local_port () const
The local Flow-protocol port chosen by the Node (if active or passive open) or user (if passive open) for this side of the connection.
size_t get_connect_metadata (const boost::asio::mutable_buffer &buffer, Error_code *err_code=0) const
Obtains the serialized connect metadata, as supplied by the user during the connection handshake.
template<typename Const_buffer_sequence >
size_t send (const Const_buffer_sequence &data, Error_code *err_code=0)
Sends (adds to the Send buffer) the given bytes of data up to a maximum internal buffer size; and asynchronously sends them to the other side.
template<typename Rep , typename Period , typename Const_buffer_sequence >
size_t sync_send (const Const_buffer_sequence &data, const boost::chrono::duration< Rep, Period > &max_wait, Error_code *err_code=0)
Blocking (synchronous) version of send().
template<typename Rep , typename Period >
bool sync_send (std::nullptr_t, const boost::chrono::duration< Rep, Period > &max_wait, Error_code *err_code=0)
sync_send() operating in nullptr_t mode, wherein – if Writable state is reached – the actual data are not moved out of any buffer, leaving that to the caller to do if desired.
template<typename Const_buffer_sequence >
size_t sync_send (const Const_buffer_sequence &data, Error_code *err_code=0)
Equivalent to sync_send(data, duration::max(), err_code); i.e., sync_send() with no timeout.
bool sync_send (std::nullptr_t, Error_code *err_code=0)
Equivalent to sync_send(nullptr, duration::max(), err_code); i.e., sync_send(nullptr_t) with no timeout.
template<typename Mutable_buffer_sequence >
size_t receive (const Mutable_buffer_sequence &target, Error_code *err_code=0)
Receives (consumes from the Receive buffer) bytes of data, up to a given maximum cumulative number of bytes as inferred from size of provided target buffer sequence.
template<typename Rep , typename Period , typename Mutable_buffer_sequence >
size_t sync_receive (const Mutable_buffer_sequence &target, const boost::chrono::duration< Rep, Period > &max_wait, Error_code *err_code=0)
Blocking (synchronous) version of receive().
template<typename Rep , typename Period >
bool sync_receive (std::nullptr_t, const boost::chrono::duration< Rep, Period > &max_wait, Error_code *err_code=0)
sync_receive() operating in nullptr_t mode, wherein – if Readable state is reached – the actual data are not moved into any buffer, leaving that to the caller to do if desired.
template<typename Mutable_buffer_sequence >
size_t sync_receive (const Mutable_buffer_sequence &target, Error_code *err_code=0)
Equivalent to sync_receive(target, duration::max(), err_code); i.e., sync_receive() with no timeout.
bool sync_receive (std::nullptr_t, Error_code *err_code=0)
Equivalent to sync_receive(nullptr, duration::max(), err_code); i.e., sync_receive(nullptr_t) with no timeout.
void close_abruptly (Error_code *err_code=0)
Acts as if fatal error error::Code::S_USER_CLOSED_ABRUPTLY has been discovered on the connection.
bool set_options (const Peer_socket_options &opts, Error_code *err_code=0)
Dynamically replaces the current options set (options()) with the given options set.
Peer_socket_options options () const
Copies this socket's option set and returns that copy.
Peer_socket_info info () const
Returns a structure containing the most up-to-date stats about this connection.
size_t max_block_size () const
The maximum number of bytes of user data per received or sent packet on this connection.
Error_code disconnect_cause () const
The error code that perviously caused state() to become State::S_CLOSED, or success code if state is not CLOSED.
Public Member Functions inherited from flow::util::Null_interface
virtual ~Null_interface ()=0
Boring virtual destructor.
Public Member Functions inherited from flow::log::Log_context
Log_context (Logger *logger=0)
Constructs Log_context by storing the given pointer to a Logger and a null Component.
template<typename Component_payload >
Log_context (Logger *logger, Component_payload component_payload)
Constructs Log_context by storing the given pointer to a Logger and a new Component storing the specified generically typed payload (an enum value).
Log_context (const Log_context &src)
Copy constructor that stores equal Logger* and Component values as the source.
Log_context (Log_context &&src)
Move constructor that makes this equal to src, while the latter becomes as-if default-constructed.
Log_context & operator= (const Log_context &src)
Assignment operator that behaves similarly to the copy constructor.
Log_context & operator= (Log_context &&src)
Move assignment operator that behaves similarly to the move constructor.
void swap (Log_context &other)
Swaps Logger pointers and Component objects held by *this and other.
Logger * get_logger () const
Returns the stored Logger pointer, particularly as many FLOW_LOG_*() macros expect.
const Component & get_log_component () const
Returns reference to the stored Component object, particularly as many FLOW_LOG_*() macros expect.
Static Public Member Functions
static Ptr cast (net_flow::Peer_socket::Ptr sock)
Convenience method that polymorphically casts from net_flow::Peer_socket::Ptr to subclass pointer net_flow::asio::Peer_socket::Ptr.
Static Public Member Functions inherited from flow::util::Shared_ptr_alias_holder< boost::shared_ptr< Peer_socket > >
static Ptr ptr_cast (const From_ptr &ptr_to_cast)
Provides syntactic-sugary way to perform a static_pointer_cast<> from a compatible smart pointer type From_ptr, typically From_ptr::element_type being in the same class hierarchy as Target_ptr::element_type.
static Const_ptr const_ptr_cast (const From_ptr &ptr_to_cast)
Identical to ptr_cast() but adds const-ness (immutability) to the pointed-to type.
static Ptr dynamic_ptr_cast (const From_ptr &ptr_to_cast)
Equivalent to ptr_cast() but a dynamic_pointer_cast instead of static.
static Const_ptr dynamic_const_ptr_cast (const From_ptr &ptr_to_cast)
Identical to const_ptr_cast() but a dynamic_pointer_cast instead of static.
Private Types
using Target_bufs = std::vector< boost::asio::mutable_buffer >
Short-hand for the Mutable_buffer_sequence concrete type for class-internal code.
using Target_bufs_ptr = boost::shared_ptr< Target_bufs >
Short-hand for a low-cost-copyable smart pointer of Target_bufs.
using Source_bufs = std::vector< boost::asio::const_buffer >
Short-hand for the Const_buffer_sequence concrete type for class-internal code.
using Source_bufs_ptr = boost::shared_ptr< Source_bufs >
Short-hand for a low-cost-copyable smart pointer of Source_bufs.
using Handler_func = Function< void(const Error_code &err_code, size_t op_result)>
Short-hand for the Task_engine-compatible send and receive Handler concrete type for class-internal code.
Private Member Functions
Peer_socket (log::Logger *logger_ptr, util::Task_engine *task_engine, const Peer_socket_options &opts)
Constructs object.
void async_receive_impl (Target_bufs_ptr target, Handler_func &&on_result, const Fine_time_pt &wait_until)
De-templated implementation of all async_receive() methods.
void async_send_impl (Source_bufs_ptr source, Handler_func &&on_result, const Fine_time_pt &wait_until)
De-templated implementation of all async_send() methods.
Node * node_or_post_error (Handler_func &&on_result)
Helper that returns the net_flow::asio::Node that generated *this; unless *this is closed; in which case it returns null after posting an error-case invocation of the user handler on_result.
template<typename Handler >
Handler_func handler_func (Handler &&on_result)
Returns a functor that essentially performs post() on_result onto *async_task_engine() in a way suitable for a boost.asio-compatible async-op.
Private Attributes
util::Task_engine * m_target_task_engine
See async_task_engine().
Friends
class Node
Similarly to the equivalent friend in net_flow::Peer_socket.
class net_flow::Node
As of this writing, it is needed for Node::sock_create_forward_plus_ctor_args().
std::ostream & operator<< (std::ostream &os, const Peer_socket *sock)
Prints string representation of given socket to given standard ostream and returns the latter.
Related Functions
(Note that these are not member functions.)
std::ostream & operator<< (std::ostream &os, const Peer_socket *sock)
Prints string representation of given socket to given standard ostream and returns the latter.
Related Functions inherited from flow::net_flow::Peer_socket
std::ostream & operator<< (std::ostream &os, const Peer_socket *sock)
Prints string representation of given socket to given standard ostream and returns the latter.
Additional Inherited Members
Protected Member Functions inherited from flow::net_flow::Peer_socket
Peer_socket (log::Logger *logger_ptr, util::Task_engine *task_engine, const Peer_socket_options &opts)
Constructs object; initializes most values to well-defined (0, empty, etc.) but not necessarily meaningful values.
Detailed Description
A net_flow::Peer_socket that adds integration with boost.asio.
See net_flow::Node for a discussion of the topic of boost.asio integration. A net_flow::asio::Peer_socket is a net_flow::Peer_socket with all that functionality, plus APIs (such as async_send(), async_receive()) that accomplish boost.asio-style asynchronous operations with a standard boost::asio::io_context (a/k/a flow::util::Task_engine).
As of this writing, asio::Peer_socket::Ptrs are generated by asio::Node::connect(), asio::Server_socket::accept(), and their derivatives. The underlying io_context (a/k/a flow::util::Task_engine) is carried forward from the factory object that generated and returned the Ptr. It can be overwritten via set_async_task_engine().
Definition at line 38 of file peer_socket.hpp.
Member Typedef Documentation
Handler_func
using flow::net_flow::asio::Peer_socket::Handler_func = Function<void (const Error_code& err_code, size_t op_result)> private
Short-hand for the Task_engine-compatible send and receive Handler concrete type for class-internal code.
Definition at line 309 of file peer_socket.hpp.
Ptr
using flow::net_flow::asio::Peer_socket::Ptr = boost::shared_ptr<Peer_socket>
Short-hand for shared_ptr to Peer_socket.
Definition at line 46 of file peer_socket.hpp.
Source_bufs
using flow::net_flow::asio::Peer_socket::Source_bufs = std::vector<boost::asio::const_buffer> private
Short-hand for the Const_buffer_sequence concrete type for class-internal code.
Definition at line 305 of file peer_socket.hpp.
Source_bufs_ptr
using flow::net_flow::asio::Peer_socket::Source_bufs_ptr = boost::shared_ptr<Source_bufs> private
Short-hand for a low-cost-copyable smart pointer of Source_bufs.
Definition at line 307 of file peer_socket.hpp.
Target_bufs
using flow::net_flow::asio::Peer_socket::Target_bufs = std::vector<boost::asio::mutable_buffer> private
Short-hand for the Mutable_buffer_sequence concrete type for class-internal code.
Definition at line 301 of file peer_socket.hpp.
Target_bufs_ptr
using flow::net_flow::asio::Peer_socket::Target_bufs_ptr = boost::shared_ptr<Target_bufs> private
Short-hand for a low-cost-copyable smart pointer of Target_bufs.
Definition at line 303 of file peer_socket.hpp.
Constructor & Destructor Documentation
~Peer_socket()
flow::net_flow::asio::Peer_socket::~Peer_socket () override
Boring virtual destructor as in superclass. See notes there.
Definition at line 37 of file peer_socket.cpp.
References FLOW_LOG_TRACE.
Peer_socket()
flow::net_flow::asio::Peer_socket::Peer_socket (log::Logger * logger_ptr, util::Task_engine * task_engine, const Peer_socket_options & opts) explicit private
Constructs object.
Parameters
logger_ptr See superclass.
task_engine See superclass.
opts See superclass.
Definition at line 28 of file peer_socket.cpp.
References FLOW_LOG_TRACE.
Referenced by async_receive_impl(), and async_send_impl().
Member Function Documentation
async_receive() [1/4]
template<typename Rep , typename Period , typename Mutable_buffer_sequence , typename Handler > void flow::net_flow::asio::Peer_socket::async_receive (const Mutable_buffer_sequence & target, const boost::chrono::duration< Rep, Period > & max_wait, Handler && on_result)
boost.asio-style asynchronous version that essentially performs non-nullptr_t net_flow::Peer_socket::sync_receive() in the background and invokes the given handler via the saved Task_engine *(async_task_engine()), as if by post(Task_engine&).
The semantics are identical to the similar sync_receive(), except that the operation does not block the calling thread; and the results are delivered to the supplied handler on_result instead of to the caller.
Template Parameters
Rep See net_flow::Peer_socket::receive().
Period See net_flow::Peer_socket::receive().
Mutable_buffer_sequence See net_flow::Peer_socket::receive().
Handler A type such that if Handler h, then a function equivalent to { h(err_code, n); } can be post()ed onto an Task_engine, with const Error_code& err_code and size_t n.
Parameters
target See net_flow::Peer_socket::receive().
on_result Handler to be executed asynchronously within the saved Task_engine. The error code and bytes-transmitted values passed to it, in that order, are identical to those out-arg/returned values in net_flow::Peer_socket::sync_receive(). Note: This overload corresponds to the non-nullptr_t sync_receive() overload. Note: Use bind_executor(S, F) to bind your handler to the util::Strand S.
max_wait See net_flow::Peer_socket::sync_receive().
Definition at line 411 of file peer_socket.hpp.
References async_receive_impl(), flow::util::chrono_duration_from_now_to_fine_time_pt(), and handler_func().
async_receive() [2/4]
template<typename Mutable_buffer_sequence , typename Handler > void flow::net_flow::asio::Peer_socket::async_receive (const Mutable_buffer_sequence & target, Handler && on_result)
Equivalent to async_receive(target, duration::max(), on_result); i.e., async_receive() with no timeout.
Template Parameters
Mutable_buffer_sequence See other async_receive().
Handler See other async_receive().
Parameters
target See other async_receive().
on_result See other async_receive().
Definition at line 431 of file peer_socket.hpp.
References async_receive_impl(), and handler_func().
async_receive() [3/4]
template<typename Rep , typename Period , typename Handler > void flow::net_flow::asio::Peer_socket::async_receive (std::nullptr_t , const boost::chrono::duration< Rep, Period > & max_wait, Handler && on_result)
boost.asio-style asynchronous version that essentially performs a nullptr_t net_flow::Peer_socket::sync_receive() in the background and invokes the given handler via the saved Task_engine *(async_task_engine()), as if by post(Task_engine&).
The semantics are identical to the similar sync_receive(), except that the operation does not block the calling thread; and the results are delivered to the supplied handler on_result instead of to the caller.
Template Parameters
Rep See net_flow::Peer_socket::receive().
Period See net_flow::Peer_socket::receive().
Handler A type such that if Handler h, then a function equivalent to { h(err_code, n); } can be post()ed onto an Task_engine, with const Error_code& err_code and size_t n.
Parameters
on_result Handler to be executed asynchronously within the saved Task_engine. The error code and bytes-transmitted values passed to it, in that order, are identical to those out-arg/returned values in net_flow::Peer_socket::sync_receive(). Note: This overload corresponds to the nullptr_t sync_receive() overload. Therefore, the bytes-transmitted value passed to the handler is always 0. Note: Use bind_executor(S, F) to bind your handler to the util::Strand S.
max_wait See net_flow::Peer_socket::sync_receive().
Definition at line 422 of file peer_socket.hpp.
References async_receive_impl(), flow::util::chrono_duration_from_now_to_fine_time_pt(), and handler_func().
async_receive() [4/4]
template<typename Handler > void flow::net_flow::asio::Peer_socket::async_receive (std::nullptr_t , Handler && on_result)
Equivalent to async_receive(nullptr, duration::max(), on_result); i.e., async_receive(nullptr) with no timeout.
Template Parameters
Handler See other async_receive().
Parameters
on_result See other async_receive().
Definition at line 440 of file peer_socket.hpp.
References async_receive_impl(), and handler_func().
async_receive_impl()
void flow::net_flow::asio::Peer_socket::async_receive_impl (Target_bufs_ptr target, Handler_func && on_result, const Fine_time_pt & wait_until) private
De-templated implementation of all async_receive() methods.
Parameters
target Ref-counted pointer to copy of target arg for non-nullptr_t async_receive() methods; or null in the case of async_receive(nullptr_t) methods.
on_result handler_func(on_result), where on_result is the user's async_*() method arg.
wait_until See max_wait arg on the originating async_receive() method. This is absolute timeout time point derived from it; zero-valued if no timeout.
Definition at line 61 of file peer_socket.cpp.
References cast(), node_or_post_error(), Peer_socket(), and flow::net_flow::Event_set::S_PEER_SOCKET_READABLE.
Referenced by async_receive().
async_send() [1/4]
template<typename Rep , typename Period , typename Const_buffer_sequence , typename Handler > void flow::net_flow::asio::Peer_socket::async_send (const Const_buffer_sequence & source, const boost::chrono::duration< Rep, Period > & max_wait, Handler && on_result)
boost.asio-style asynchronous version that essentially performs non-nullptr_t net_flow::Peer_socket::sync_send() in the background and invokes the given handler via the saved Task_engine *(async_task_engine()), as if by post(Task_engine&).
The semantics are identical to the similar sync_send(), except that the operation does not block the calling thread; and the results are delivered to the supplied handler on_result instead of to the caller.
Template Parameters
Rep See net_flow::Peer_socket::send().
Period See net_flow::Peer_socket::send().
Const_buffer_sequence See net_flow::Peer_socket::send().
Handler A type such that if Handler h, then a function equivalent to { h(err_code, n); } can be post()ed onto an Task_engine, with const Error_code& err_code and size_t n.
Parameters
source See net_flow::Peer_socket::send().
on_result Handler to be executed asynchronously within the saved Task_engine. The error code and bytes-transmitted values passed to it, in that order, are identical to those out-arg/returned values in net_flow::Peer_socket::sync_send(). Note: This overload corresponds to the non-nullptr_t sync_send() overload. Note: Use bind_executor(S, F) to bind your handler to the util::Strand S.
max_wait See net_flow::Peer_socket::sync_send().
Definition at line 446 of file peer_socket.hpp.
References async_send_impl(), flow::util::chrono_duration_from_now_to_fine_time_pt(), and handler_func().
async_send() [2/4]
template<typename Const_buffer_sequence , typename Handler > void flow::net_flow::asio::Peer_socket::async_send (const Const_buffer_sequence & source, Handler && on_result)
Equivalent to async_send(target, duration::max(), on_result); i.e., async_send() with no timeout.
Template Parameters
Const_buffer_sequence See other async_send().
Handler See other async_send().
Parameters
source See other async_send().
on_result See other async_send().
Definition at line 466 of file peer_socket.hpp.
References async_send_impl(), and handler_func().
async_send() [3/4]
template<typename Rep , typename Period , typename Handler > void flow::net_flow::asio::Peer_socket::async_send (std::nullptr_t , const boost::chrono::duration< Rep, Period > & max_wait, Handler && on_result)
boost.asio-style asynchronous version that essentially performs a nullptr_t net_flow::Peer_socket::sync_send() in the background and invokes the given handler via the saved Task_engine *(async_task_engine()), as if by post(Task_engine&).
The semantics are identical to the similar sync_send(), except that the operation does not block the calling thread; and the results are delivered to the supplied handler on_result instead of to the caller.
Template Parameters
Rep See net_flow::Peer_socket::send().
Period See net_flow::Peer_socket::send().
Handler A type such that if Handler h, then a function equivalent to { h(err_code, n); } can be post()ed onto an Task_engine, with const Error_code& err_code and size_t n.
Parameters
on_result Handler to be executed asynchronously within the saved Task_engine. The error code and bytes-transmitted values passed to it, in that order, are identical to those out-arg/returned values in net_flow::Peer_socket::sync_send(). Note: This overload corresponds to the nullptr_t sync_send() overload. Therefore, the bytes-transmitted value passed to the handler is always 0. Note: Use bind_executor(S, F) to bind your handler to the util::Strand S.
max_wait See net_flow::Peer_socket::sync_send().
Definition at line 457 of file peer_socket.hpp.
References async_send_impl(), flow::util::chrono_duration_from_now_to_fine_time_pt(), and handler_func().
async_send() [4/4]
template<typename Handler > void flow::net_flow::asio::Peer_socket::async_send (std::nullptr_t , Handler && on_result)
Equivalent to async_send(nullptr, duration::max(), on_result); i.e., async_send(nullptr) with no timeout.
Template Parameters
Handler See other async_send().
Parameters
on_result See other async_send().
Definition at line 475 of file peer_socket.hpp.
References async_send_impl(), and handler_func().
async_send_impl()
void flow::net_flow::asio::Peer_socket::async_send_impl (Source_bufs_ptr source, Handler_func && on_result, const Fine_time_pt & wait_until) private
De-templated implementation of all async_send() methods.
Parameters
source Ref-counted pointer to copy of source arg for non-nullptr_t async_send() methods; or an empty sequence in the case of async_send(nullptr_t) methods.
on_result handler_func(on_result), where on_result is the user's async_*() method arg.
wait_until See max_wait arg on the originating async_send() method. This is absolute timeout time point derived from it; zero-valued if no timeout.
Definition at line 102 of file peer_socket.cpp.
References cast(), node_or_post_error(), Peer_socket(), and flow::net_flow::Event_set::S_PEER_SOCKET_WRITABLE.
Referenced by async_send().
async_task_engine()
util::Task_engine * flow::net_flow::asio::Peer_socket::async_task_engine ()
Pointer (possibly null) for the flow::util::Task_engine used by any coming async_*() I/O calls.
Thread safety (operating on a given Node)
set_async_task_engine() is the only way to change the returned value, upon construction.
It is not safe to call set_async_task_engine() at the same time as async_task_engine().
Define "any async op" as async_*() in this class, including actions it takes in the background (asynchronously).
async_task_engine() must return the same value – and not null – throughout "any async op."
Put simply, a null Task_engine is allowed, but a null cannot be used when performing an async op. Furthermore, set_async_task_engine() is unsafe through any of those and through async_task_engine() itself.
Informal tip: Same as in doc header for Node::async_task_engine().
Returns
Null or non-null pointer to flow::util::Task_engine.
Definition at line 42 of file peer_socket.cpp.
References m_target_task_engine.
Referenced by handler_func(), and node_or_post_error().
async_task_engine_cref()
const util::Task_engine & flow::net_flow::asio::Peer_socket::async_task_engine_cref () const
Read-only version of async_task_engine().
Returns
Reference to read-only *(async_task_engine()).
Definition at line 48 of file peer_socket.cpp.
References m_target_task_engine.
cast()
Peer_socket::Ptr flow::net_flow::asio::Peer_socket::cast (net_flow::Peer_socket::Ptr sock) static
Convenience method that polymorphically casts from net_flow::Peer_socket::Ptr to subclass pointer net_flow::asio::Peer_socket::Ptr.
Behavior undefined if sock is not actually of the latter type. With this, one needn't do verbose static_[pointer_]cast<> or similar conversions.
Parameters
sock Handle to a sock such that the true underlying concrete type is net_flow::asio::Peer_socket.
Returns
See above.
Definition at line 152 of file peer_socket.cpp.
Referenced by flow::net_flow::asio::Server_socket::async_accept_impl(), flow::net_flow::asio::Node::async_connect_impl(), async_receive_impl(), and async_send_impl().
handler_func()
template<typename Handler > Peer_socket::Handler_func flow::net_flow::asio::Peer_socket::handler_func (Handler && on_result) private
Returns a functor that essentially performs post() on_result onto *async_task_engine() in a way suitable for a boost.asio-compatible async-op.
Rationale
Why not simply create use Handler_func(on_result)? After all they have the same signature, so if the idea is to de-template our internal implementation of the various async_*() APIs, then that would be sufficient. Answer:
We are aiming to implement a boost.asio-compatible async-op, so one way or another we'll need to post() a no-arg wrapper of on_result(...);. handler_func() returning a function that does that alone would be potentially useful in its own right. That, however, is still insufficient – though that may not be obvious even to experienced boost.asio users. Handler and on_result may be associated with an executor, such as a util::Strand, which a proper boost.asio async-op API must respect when post()ing it onto the util::Task_engine. handler_func() takes care of that too (details omitted here; see body).
Note: Failing to do the executor stuff will build, and work – but it won't work "all the way," if on_result is bound to an executor like a strand. In the latter case it would result in executing on_result() outside the associated strand – and hence potential thread-unsafety.
Template Parameters
Handler See async_receive() and others.
Parameters
on_result See async_receive() and others.
Returns
Function to call from any context that will properly post() on_result(); onto *async_task_engine().
Definition at line 482 of file peer_socket.hpp.
References async_task_engine().
Referenced by async_receive(), and async_send().
node_or_post_error()
Node * flow::net_flow::asio::Peer_socket::node_or_post_error (Handler_func && on_result) private
Helper that returns the net_flow::asio::Node that generated *this; unless *this is closed; in which case it returns null after posting an error-case invocation of the user handler on_result.
Parameters
on_result handler_func(on_result), where on_result is the user's async_*() method arg. This will be executed if and only if null is returned. The reason for why the latter occurred is passed as the error code argument to on_result().
Returns
Non-null pointer to owning Node, if and only if it is available.
Definition at line 132 of file peer_socket.cpp.
References async_task_engine(), flow::net_flow::Peer_socket::disconnect_cause(), FLOW_LOG_WARNING, and flow::net_flow::Peer_socket::node().
Referenced by async_receive_impl(), and async_send_impl().
set_async_task_engine()
void flow::net_flow::asio::Peer_socket::set_async_task_engine (util::Task_engine * target_async_task_engine)
Overwrites the value to be returned by next async_task_engine().
See async_task_engine() doc header before using this.
Parameters
target_async_task_engine See async_task_engine().
Definition at line 53 of file peer_socket.cpp.
References FLOW_LOG_INFO, and m_target_task_engine.
Referenced by flow::net_flow::asio::Node::sock_create().
Friends And Related Function Documentation
net_flow::Node
friend class net_flow::Node friend
As of this writing, it is needed for Node::sock_create_forward_plus_ctor_args().
Definition at line 293 of file peer_socket.hpp.
Node
friend class Node friend
Similarly to the equivalent friend in net_flow::Peer_socket.
Definition at line 291 of file peer_socket.hpp.
operator<< [1/2]
std::ostream & operator<< (std::ostream & os, const Peer_socket * sock) friend
Prints string representation of given socket to given standard ostream and returns the latter.
The representation includes the local and remote endpoints and the hex pointer value.
Note
shared_ptr forwards ostream output to the underlying pointer type, so this will affect Ptr output as well.
Parameters
os Stream to print to.
sock Object to serialize. May be null.
Returns
os.
Definition at line 249 of file peer_socket.cpp.
operator<<() [2/2]
std::ostream & operator<< (std::ostream & os, const Peer_socket * sock) related
Prints string representation of given socket to given standard ostream and returns the latter.
The representation includes the local and remote endpoints and the hex pointer value.
Note
shared_ptr forwards ostream output to the underlying pointer type, so this will affect Ptr output as well.
Parameters
os Stream to print to.
sock Object to serialize. May be null.
Returns
os.
Definition at line 249 of file peer_socket.cpp.
Member Data Documentation
m_target_task_engine
util::Task_engine* flow::net_flow::asio::Peer_socket::m_target_task_engine private
See async_task_engine().
Definition at line 403 of file peer_socket.hpp.
Referenced by async_task_engine(), async_task_engine_cref(), and set_async_task_engine().
The documentation for this class was generated from the following files:
net_flow/asio/peer_socket.hpp
net_flow/asio/peer_socket.cpp
net_flow/net_flow_fwd.hpp