Flow: flow::log::Ostream_log_msg_writer Class Reference
flow::log::Ostream_log_msg_writer Class Reference
Utility class, each object of which wraps a given ostream and outputs discrete messages to it adorned with time stamps and other formatting such as separating newlines.
#include <ostream_log_msg_writer.hpp>
Public Member Functions
Ostream_log_msg_writer (const Config &config, std::ostream &os)
Constructs object wrapping the given ostream.
~Ostream_log_msg_writer () noexcept
Restores formatting state of os to how it was before entry to constructor.
void log (const Msg_metadata &metadata, util::String_view msg)
Logs to the wrapped ostream the given message and associated metadata like severity and time stamp; plus a newline.
Private Types
using Ostream_state = boost::io::ios_all_saver
Short-hand for an ostream state saver.
Private Member Functions
void do_log_with_epoch_time_stamp (const Msg_metadata &metadata, util::String_view msg)
log() implementation with time stamp = seconds.microseconds since Epoch.
void do_log_with_human_friendly_time_stamp (const Msg_metadata &metadata, util::String_view msg)
log() implementation with time stamp = date/time with microsecond+ resolution/time zone, in current OS time zone.
void log_past_time_stamp (const Msg_metadata &metadata, util::String_view msg)
Remainder of log() functionality after either do_log_with_epoch_time_stamp() or do_log_with_human_friendly_time_stamp(), once either has logged the time stamp.
Private Attributes
const Config & m_config
Reference to the config object passed to constructor. See notes on thread safety.
const Function< void(Ostream_log_msg_writer *, const Msg_metadata &, util::String_view)> m_do_log_func
Pointer to function that log() will forward to when invoked.
std::ostream & m_os
Reference to stream to which to log messages.
Ostream_state m_clean_os_state
Formatter state of m_os at construction. Used at least in destructor (as of this writing) to restore it.
std::array< char, S_HUMAN_FRIENDLY_TIME_STAMP_MIN_SZ_TEMPLATE.size()+S_HUMAN_FRIENDLY_TIME_STAMP_REST_SZ_TEMPLATE.size()+1 > m_last_human_friendly_time_stamp_str
Buffer storing the last log() time stamp in human-friendly form, including a NUL at the end.
size_t m_last_human_friendly_time_stamp_str_sz
Length of string in m_last_human_friendly_time_stamp_str (excluding any NUL).
std::chrono::time_point< std::chrono::system_clock, std::chrono::seconds > m_cached_rounded_time_stamp
As used in the caching-for-perf algorithm in do_log_with_human_friendly_time_stamp(), this is the seconds-precision version of high-precision Msg_metadata::m_called_when, when do_log_with_human_friendly_time_stamp() last had to perform full formatted-output into m_last_human_friendly_time_stamp_str.
Static Private Attributes
static const std::vector< util::String_view > S_SEV_STRS
Mapping from Sev to its brief string description.
static const boost::chrono::system_clock::time_point S_POSIX_EPOCH = boost::chrono::system_clock::from_time_t(0)
Jan 1, 1970, 00:00.
static constexpr util::String_view S_HUMAN_FRIENDLY_TIME_STAMP_MIN_SZ_TEMPLATE {"2024-02-05 22:09:"}
Example human-readable time stamp output, up to but excluding seconds, for compile-time size calculations.
static constexpr util::String_view S_HUMAN_FRIENDLY_TIME_STAMP_REST_SZ_TEMPLATE {"31.357246045 +0000 "}
Example human-readable time stamp output, starting with seconds, for compile-time size calculations.
Detailed Description
Utility class, each object of which wraps a given ostream and outputs discrete messages to it adorned with time stamps and other formatting such as separating newlines.
A Config object controls certain aspects of its behavior; pass this to the constructor. The Config may come from the user as passed to the Logger (if any) using *this; or that Logger (if any) can make its own from scratch.
It is assumed that between the first and last calls to log() no other code whatsoever writes to the underlying stream (as passed to ctor) at any point – including any formatters. At *this destruction formatter state is restored.
Rationale
This optional (but recommended for most Logger implementations, though technically not limited to their use) utility class typically sits between some "physical" output medium – a buffer in memory, a file, etc. – that can be written to using an ostream (e.g., std::ostringstream, util::String_ostream, std::ofstream); and a Logger implementation that promises to output log messages to that output medium. When Logger::do_log() is called, the message string passed to it will contain the user's original message plus various Msg_metadata nuggets (like time stamp, severity, source code location) either generated by FLOW_LOG_WITHOUT_CHECKING() implementation or provided by user. The idea is the Logger is to decide on the output format of the various metadata plus the message. Therefore, the present class outputs all those pieces (as appropriate) plus separating newlines. Any Logger is free to use any format it wants; and some Loggers might not even generate any output character stream but rather forward everything elsewhere (maybe even over the network); but Ostream_log_msg_writer provides a reasonable output format to a character stream, to be used or not as desired.
Thread safety
For a given *this, the class is not safe for concurrent calls to log(). The using code must provide any such guarantees.
See thread safety notes and to-dos regarding config in Simple_ostream_logger doc header. These apply here also.
Impl notes
Human-readable time stamps, caching
At least optionally, log() adds a human-readable time stamp readout with the date, time (including seconds.usec or better), and time zone. Just getting that in a decent, predictable form, without localized weirdness, and with sub-second precision can be non-trivial; std::chrono does not do it as of C++17; boost.chrono does but only as of a certain quietly added features called time-point I/O v2 (as opposed to v1). That in itself was workable; however:
When logging volume is very high, processor use by logging can be high, and as a percentage of cycles used, we noticed that a high proportion was used in formatting the time_point into the ostream by boost.chrono. Therefore we eventually moved to fmt, an output formatting library that is lightning-fast and whose API is now folded into C++20 standard lib (as of this writing we are on C++17); not unlike boost.chrono long ago became std::chrono. fmt provides flexibly formattable time_point output as well, so we can get everything we want just how we want it (in contrast with boost.chrono where it was merely a stroke of luck that the output was acceptable).
Moreover, we accomplish a slight additional speedup by caching the formatted output across log() calls; in each log() printing it up to but excluding seconds; then adding the seconds plus sub-seconds in a separate, less expensive fmt call. The cached output needs to be updated once the previous cached value is no longer applicable even up to the precision that is actually used.
Why standard library time-points instead of boost.chrono?
In the rest of Flow we tend to prefer boost.chrono to std::chrono; they are extremely similar, but boost.chrono adds a few features including some extra clocks which are useful. However fmt accepts std::chrono time points, so for this specific purpose we store an std::chrono time point in Msg_metadata. At that point it was also reasonable to just use std::chrono for other time-related needs in this small class.
Definition at line 102 of file ostream_log_msg_writer.hpp.
Member Typedef Documentation
Ostream_state
using flow::log::Ostream_log_msg_writer::Ostream_state = boost::io::ios_all_saver private
Short-hand for an ostream state saver.
Definition at line 147 of file ostream_log_msg_writer.hpp.
Constructor & Destructor Documentation
Ostream_log_msg_writer()
flow::log::Ostream_log_msg_writer::Ostream_log_msg_writer (const Config & config, std::ostream & os) explicit
Constructs object wrapping the given ostream.
Does not write any characters to stream (so, for instance, if it happens to be an ofstream then it is fine if it's not yet open or even associated with a path). It may however do stateful things such as format setting.
If any non-default formatting has been applied to os, subsequent behavior is undefined.
Parameters
config Controls behavior of *this. See thread safety notes in class doc header. This is saved by reference inside *this; it must remain valid through the last log() call.
os Stream to which to write subsequently via log().
Definition at line 38 of file ostream_log_msg_writer.cpp.
References m_config, m_os, and flow::log::Config::m_use_human_friendly_time_stamps.
~Ostream_log_msg_writer()
flow::log::Ostream_log_msg_writer::~Ostream_log_msg_writer () noexcept
Restores formatting state of os to how it was before entry to constructor.
Definition at line 70 of file ostream_log_msg_writer.cpp.
Member Function Documentation
do_log_with_epoch_time_stamp()
void flow::log::Ostream_log_msg_writer::do_log_with_epoch_time_stamp (const Msg_metadata & metadata, util::String_view msg) private
log() implementation with time stamp = seconds.microseconds since Epoch.
Parameters
metadata See log().
msg See log().
Definition at line 79 of file ostream_log_msg_writer.cpp.
References log_past_time_stamp(), flow::log::Msg_metadata::m_called_when, and m_os.
do_log_with_human_friendly_time_stamp()
void flow::log::Ostream_log_msg_writer::do_log_with_human_friendly_time_stamp (const Msg_metadata & metadata, util::String_view msg) private
log() implementation with time stamp = date/time with microsecond+ resolution/time zone, in current OS time zone.
Parameters
metadata See log().
msg See log().
Definition at line 105 of file ostream_log_msg_writer.cpp.
References log_past_time_stamp(), m_cached_rounded_time_stamp, flow::log::Msg_metadata::m_called_when, m_last_human_friendly_time_stamp_str, m_last_human_friendly_time_stamp_str_sz, m_os, and S_HUMAN_FRIENDLY_TIME_STAMP_MIN_SZ_TEMPLATE.
log()
void flow::log::Ostream_log_msg_writer::log (const Msg_metadata & metadata, util::String_view msg)
Logs to the wrapped ostream the given message and associated metadata like severity and time stamp; plus a newline.
Parameters
metadata See *metadata in Logger::do_log().
msg The message. No terminating newline is assumed (though there is no rule against it; but if one is present, a blank line will appear in wrapped ostream).
Definition at line 74 of file ostream_log_msg_writer.cpp.
References m_do_log_func.
Referenced by flow::log::Buffer_logger::do_log(), and flow::log::Serial_file_logger::do_log().
log_past_time_stamp()
void flow::log::Ostream_log_msg_writer::log_past_time_stamp (const Msg_metadata & metadata, util::String_view msg) private
Remainder of log() functionality after either do_log_with_epoch_time_stamp() or do_log_with_human_friendly_time_stamp(), once either has logged the time stamp.
Parameters
metadata See log().
msg See log().
Definition at line 165 of file ostream_log_msg_writer.cpp.
References FLOW_UTIL_WHERE_AM_I_FROM_ARGS, flow::log::Msg_metadata::m_call_thread_id, flow::log::Msg_metadata::m_call_thread_nickname, m_config, flow::log::Msg_metadata::m_msg_component, flow::log::Msg_metadata::m_msg_sev, flow::log::Msg_metadata::m_msg_src_file, flow::log::Msg_metadata::m_msg_src_function, flow::log::Msg_metadata::m_msg_src_line, m_os, flow::log::Config::output_component_to_ostream(), and flow::log::S_NONE.
Referenced by do_log_with_epoch_time_stamp(), and do_log_with_human_friendly_time_stamp().
Member Data Documentation
m_cached_rounded_time_stamp
std::chrono::time_point<std::chrono::system_clock, std::chrono::seconds> flow::log::Ostream_log_msg_writer::m_cached_rounded_time_stamp private
As used in the caching-for-perf algorithm in do_log_with_human_friendly_time_stamp(), this is the seconds-precision version of high-precision Msg_metadata::m_called_when, when do_log_with_human_friendly_time_stamp() last had to perform full formatted-output into m_last_human_friendly_time_stamp_str.
Definition at line 237 of file ostream_log_msg_writer.hpp.
Referenced by do_log_with_human_friendly_time_stamp().
m_clean_os_state
Ostream_state flow::log::Ostream_log_msg_writer::m_clean_os_state private
Formatter state of m_os at construction. Used at least in destructor (as of this writing) to restore it.
Definition at line 221 of file ostream_log_msg_writer.hpp.
m_config
const Config& flow::log::Ostream_log_msg_writer::m_config private
Reference to the config object passed to constructor. See notes on thread safety.
Definition at line 212 of file ostream_log_msg_writer.hpp.
Referenced by log_past_time_stamp(), and Ostream_log_msg_writer().
m_do_log_func
const Function<void (Ostream_log_msg_writer*, const Msg_metadata&, util::String_view)> flow::log::Ostream_log_msg_writer::m_do_log_func private
Pointer to function that log() will forward to when invoked.
Definition at line 215 of file ostream_log_msg_writer.hpp.
Referenced by log().
m_last_human_friendly_time_stamp_str
std::array<char, S_HUMAN_FRIENDLY_TIME_STAMP_MIN_SZ_TEMPLATE.size() + S_HUMAN_FRIENDLY_TIME_STAMP_REST_SZ_TEMPLATE.size() + 1> flow::log::Ostream_log_msg_writer::m_last_human_friendly_time_stamp_str private
Buffer storing the last log() time stamp in human-friendly form, including a NUL at the end.
Definition at line 226 of file ostream_log_msg_writer.hpp.
Referenced by do_log_with_human_friendly_time_stamp().
m_last_human_friendly_time_stamp_str_sz
size_t flow::log::Ostream_log_msg_writer::m_last_human_friendly_time_stamp_str_sz private
Length of string in m_last_human_friendly_time_stamp_str (excluding any NUL).
Definition at line 229 of file ostream_log_msg_writer.hpp.
Referenced by do_log_with_human_friendly_time_stamp().
m_os
std::ostream& flow::log::Ostream_log_msg_writer::m_os private
Reference to stream to which to log messages.
Definition at line 218 of file ostream_log_msg_writer.hpp.
Referenced by do_log_with_epoch_time_stamp(), do_log_with_human_friendly_time_stamp(), log_past_time_stamp(), and Ostream_log_msg_writer().
S_HUMAN_FRIENDLY_TIME_STAMP_MIN_SZ_TEMPLATE
constexpr util::String_view flow::log::Ostream_log_msg_writer::S_HUMAN_FRIENDLY_TIME_STAMP_MIN_SZ_TEMPLATE {"2024-02-05 22:09:"} static constexpr private
Example human-readable time stamp output, up to but excluding seconds, for compile-time size calculations.
Definition at line 192 of file ostream_log_msg_writer.hpp.
Referenced by do_log_with_human_friendly_time_stamp().
S_HUMAN_FRIENDLY_TIME_STAMP_REST_SZ_TEMPLATE
constexpr util::String_view flow::log::Ostream_log_msg_writer::S_HUMAN_FRIENDLY_TIME_STAMP_REST_SZ_TEMPLATE {"31.357246045 +0000 "} static constexpr private
Example human-readable time stamp output, starting with seconds, for compile-time size calculations.
Subtlety
fmt docs say S will use the precision "available"; in practice in our tested Linuxes it is nanoseconds; in the past I (ygoldfel) have also seen microseconds printed in this situation; might be some artifact of an internal time-formatting system API; whatever. However, it is unlikely it will in practice be better than nanoseconds; hence for our size-reserving purposes the template string with nanoseconds should suffice.
(It also says that if there is no sub-second value, then it won't print the sub-second portion; but this appears to be poorly worded documentation: It prints .000000000 just fine.)
Definition at line 207 of file ostream_log_msg_writer.hpp.
S_POSIX_EPOCH
const boost::chrono::system_clock::time_point flow::log::Ostream_log_msg_writer::S_POSIX_EPOCH = boost::chrono::system_clock::from_time_t(0) static private
Jan 1, 1970, 00:00.
Definition at line 189 of file ostream_log_msg_writer.hpp.
S_SEV_STRS
const std::vector< util::String_view > flow::log::Ostream_log_msg_writer::S_SEV_STRS static private
Mapping from Sev to its brief string description.
Definition at line 186 of file ostream_log_msg_writer.hpp.
The documentation for this class was generated from the following files:
log/ostream_log_msg_writer.hpp
log/ostream_log_msg_writer.cpp