Flow: flow::async::Timed_single_thread_task_loop Class Reference
flow::async::Timed_single_thread_task_loop Class Reference
Identical to Single_thread_task_loop, but all tasks posted through it are automatically timed, with the result accessible via accumulated_time().
#include <single_thread_task_loop.hpp>
Public Member Functions
Timed_single_thread_task_loop (log::Logger *logger_ptr, util::String_view nickname, perf::Clock_type clock_type=perf::Clock_type::S_CPU_THREAD_TOTAL_HI_RES)
Constructs object, similarly to Single_thread_task_loop ctor; but with timing capabilities a-la Timed_concurrent_task_loop ctor.
void post (Task &&task, Synchronicity synchronicity=Synchronicity::S_ASYNC) override
Implements superclass method but with the addition of timing of task, accessible through accumulated_time().
util::Scheduled_task_handle schedule_from_now (const Fine_duration &from_now, Scheduled_task &&task) override
Implements superclass method but with the addition of timing of task, accessible through accumulated_time().
util::Scheduled_task_handle schedule_at (const Fine_time_pt &at, Scheduled_task &&task) override
Implements superclass method but with the addition of timing of task, accessible through accumulated_time().
perf::Duration accumulated_time ()
See Timed_concurrent_task_loop_impl::accumulated_time().
template<typename Handler >
auto asio_handler_timed (Handler &&handler_moved)
See Timed_concurrent_task_loop_impl::asio_handler_timed().
Public Member Functions inherited from flow::async::Single_thread_task_loop
Single_thread_task_loop (log::Logger *logger_ptr, util::String_view nickname)
Constructs object, making it available for post() and similar work, but without starting any thread and hence without the ability to perform any work; call start() to spawn 1 thread and perform work.
~Single_thread_task_loop () override
Executes stop() – see its doc header please – and then cleans up any resources.
void start (Task &&init_task_or_empty=Task())
Starts the 1 thread in the thread pool; any queued post()ed (and similar) tasks may begin executing immediately; and any future posted work may execute in this thread.
void stop ()
Waits for the ongoing task/completion handler – if one is running – to return; then prevents any further-queued such tasks from running; then gracefully stops/joins the worker thread; and then returns.
virtual void post (Task &&task, Synchronicity synchronicity=Synchronicity::S_ASYNC)
Cause the given Task (function) to execute within the worker thread as soon as the thread is free of other queued tasks/completion handlers, in first-come-first-served fashion.
virtual util::Scheduled_task_handle schedule_from_now (const Fine_duration &from_now, Scheduled_task &&task)
Equivalent to post() but execution is scheduled for later, after the given time period passes.
virtual util::Scheduled_task_handle schedule_at (const Fine_time_pt &at, Scheduled_task &&task)
Equivalent to schedule_from_now() except one specifies an absolute time point instead of wait duration.
Task_engine_ptr task_engine ()
Returns a pointer to the internal util::Task_engine (a/k/a boost.asio io_service) for the purpose of performing a boost.asio async_*() action on some boost.asio I/O object in the immediate near future.
bool in_thread () const
Returns true if and only if the thread executing this call is the thread started by start().
Public Member Functions inherited from flow::log::Log_context
Log_context (Logger *logger=0)
Constructs Log_context by storing the given pointer to a Logger and a null Component.
template<typename Component_payload >
Log_context (Logger *logger, Component_payload component_payload)
Constructs Log_context by storing the given pointer to a Logger and a new Component storing the specified generically typed payload (an enum value).
Log_context (const Log_context &src)
Copy constructor that stores equal Logger* and Component values as the source.
Log_context (Log_context &&src)
Move constructor that makes this equal to src, while the latter becomes as-if default-constructed.
Log_context & operator= (const Log_context &src)
Assignment operator that behaves similarly to the copy constructor.
Log_context & operator= (Log_context &&src)
Move assignment operator that behaves similarly to the move constructor.
void swap (Log_context &other)
Swaps Logger pointers and Component objects held by *this and other.
Logger * get_logger () const
Returns the stored Logger pointer, particularly as many FLOW_LOG_*() macros expect.
const Component & get_log_component () const
Returns reference to the stored Component object, particularly as many FLOW_LOG_*() macros expect.
Public Member Functions inherited from flow::util::Null_interface
virtual ~Null_interface ()=0
Boring virtual destructor.
Private Attributes
Timed_concurrent_task_loop_impl< perf::duration_rep_t > m_timed_loop
The task-timing decorator of our superclass Single_thread_task_loop's protected superclass.
Additional Inherited Members
Protected Member Functions inherited from flow::async::Single_thread_task_loop
Concurrent_task_loop * underlying_loop ()
Returns the underlying work-horse Concurrent_task_loop.
Detailed Description
Identical to Single_thread_task_loop, but all tasks posted through it are automatically timed, with the result accessible via accumulated_time().
Using a Timed_single_thread_task_loop is identical to using Single_thread_task_loop; except – as with a Timed_concurrent_task_loop vs. plain Concurrent_task_loop – any "naked" handler F passed directly to a boost.asio async_...(..., F) operation should be wrapped by asio_handler_timed(), so that it too is timed. Hence it would become: async_...(..., L->asio_handler_timed(F)).
To access timing results use added API accumulated_time().
Definition at line 307 of file single_thread_task_loop.hpp.
Constructor & Destructor Documentation
Timed_single_thread_task_loop()
flow::async::Timed_single_thread_task_loop::Timed_single_thread_task_loop (log::Logger * logger_ptr, util::String_view nickname, perf::Clock_type clock_type = perf::Clock_type::S_CPU_THREAD_TOTAL_HI_RES) explicit
Constructs object, similarly to Single_thread_task_loop ctor; but with timing capabilities a-la Timed_concurrent_task_loop ctor.
Parameters
logger_ptr See Single_thread_task_loop ctor.
nickname See Single_thread_task_loop ctor.
clock_type See Timed_concurrent_task_loop_impl ctor.
Definition at line 90 of file single_thread_task_loop.cpp.
Member Function Documentation
accumulated_time()
perf::Duration flow::async::Timed_single_thread_task_loop::accumulated_time ()
See Timed_concurrent_task_loop_impl::accumulated_time().
Returns
See above.
Definition at line 117 of file single_thread_task_loop.cpp.
References flow::async::Timed_concurrent_task_loop_impl< Time_accumulator >::accumulated_time(), and m_timed_loop.
asio_handler_timed()
template<typename Handler > auto flow::async::Timed_single_thread_task_loop::asio_handler_timed (Handler && handler_moved)
See Timed_concurrent_task_loop_impl::asio_handler_timed().
Template Parameters
Handler See Timed_concurrent_task_loop_impl::asio_handler_timed().
Parameters
handler_moved See Timed_concurrent_task_loop_impl::asio_handler_timed().
Returns
See Timed_concurrent_task_loop_impl::asio_handler_timed().
Definition at line 400 of file single_thread_task_loop.hpp.
References flow::async::Timed_concurrent_task_loop_impl< Time_accumulator >::asio_handler_timed(), and m_timed_loop.
post()
void flow::async::Timed_single_thread_task_loop::post (Task && task, Synchronicity synchronicity = Synchronicity::S_ASYNC) override virtual
Implements superclass method but with the addition of timing of task, accessible through accumulated_time().
See also
Single_thread_task_loop::post() doc header for the essential documentation outside of timing.
Parameters
task See superclass method.
synchronicity See superclass method.
Reimplemented from flow::async::Single_thread_task_loop.
Definition at line 101 of file single_thread_task_loop.cpp.
References m_timed_loop, and flow::async::Timed_concurrent_task_loop_impl< Time_accumulator >::post().
schedule_at()
util::Scheduled_task_handle flow::async::Timed_single_thread_task_loop::schedule_at (const Fine_time_pt & at, Scheduled_task && task) override virtual
Implements superclass method but with the addition of timing of task, accessible through accumulated_time().
See also
Single_thread_task_loop::schedule_at() doc header for the essential documentation outside of timing.
Parameters
at See superclass method.
task See superclass method.
Returns
See superclass method.
Reimplemented from flow::async::Single_thread_task_loop.
Definition at line 112 of file single_thread_task_loop.cpp.
References m_timed_loop, and flow::async::Timed_concurrent_task_loop_impl< Time_accumulator >::schedule_at().
schedule_from_now()
util::Scheduled_task_handle flow::async::Timed_single_thread_task_loop::schedule_from_now (const Fine_duration & from_now, Scheduled_task && task) override virtual
Implements superclass method but with the addition of timing of task, accessible through accumulated_time().
See also
Single_thread_task_loop::schedule_from_now() doc header for the essential documentation outside of timing.
Parameters
from_now See superclass method.
task See superclass method.
Returns
See superclass method.
Reimplemented from flow::async::Single_thread_task_loop.
Definition at line 106 of file single_thread_task_loop.cpp.
References m_timed_loop, and flow::async::Timed_concurrent_task_loop_impl< Time_accumulator >::schedule_from_now().
Member Data Documentation
m_timed_loop
Timed_concurrent_task_loop_impl<perf::duration_rep_t> flow::async::Timed_single_thread_task_loop::m_timed_loop private
The task-timing decorator of our superclass Single_thread_task_loop's protected superclass.
As required, its lifetime (being a base class) is >= that of this decorating m_timed_loop.
Definition at line 394 of file single_thread_task_loop.hpp.
Referenced by accumulated_time(), asio_handler_timed(), post(), schedule_at(), and schedule_from_now().
The documentation for this class was generated from the following files:
async/single_thread_task_loop.hpp
async/single_thread_task_loop.cpp