Flow: flow::util::Basic_blob< Allocator, SHARING >::Deleter_raw Class Reference
flow::util::Basic_blob< Allocator, SHARING >::Deleter_raw Class Reference
Internal deleter functor used if and only if S_IS_VANILLA_ALLOC is false and therefore only with Buf_ptr being boost::interprocess::shared_ptr or deleter-parameterized unique_ptr.
Public Types
using Pointer_raw = typename std::allocator_traits< Allocator_raw >::pointer
Short-hand for the allocator's pointer type, pointing to Basic_blob::value_type.
using pointer = Pointer_raw
For boost::interprocess::shared_ptr and unique_ptr compliance (hence the irregular capitalization).
Public Member Functions
Deleter_raw ()
Default ctor: Deleter must never be invoked to delete anything in this state; suitable only for a null smart-pointer.
Deleter_raw (const Allocator_raw &alloc_raw_src, size_type buf_sz)
Constructs deleter by memorizing the allocator (of zero size if Allocator_raw is stateless, usually) used to allocate whatever shall be passed-to operator()(); and the size (in # of value_types) of the buffer allocated there.
Deleter_raw (Deleter_raw &&moved_src)
Move-construction which may be required when we are used in unique_ptr.
Deleter_raw (const Deleter_raw &src)
Copy-construction which may be required when we are used in boost::interprocess::shared_ptr which as of this writing requires copyable deleter in its .reset() and other places.
Deleter_raw & operator= (Deleter_raw &&moved_src)
Move-assignment which is required when we are used in unique_ptr.
Deleter_raw & operator= (const Deleter_raw &src)
Copy-assignment which is required when we are used in boost::interprocess::shared_ptr which as of this writing requires copyable deleter in its .reset() and other places.
void operator() (Pointer_raw to_delete)
Deallocates using Allocator_raw::deallocate(), passing-in the supplied pointer (to value_type) to_delete and the number of value_types to delete (from ctor).
Private Attributes
std::optional< Allocator_raw > m_alloc_raw
See ctor: the allocator that operator()() shall use to deallocate.
size_type m_buf_sz
See ctor and operator()(): the size of the buffer to deallocate.
Detailed Description
template<typename Allocator, bool SHARING>
class flow::util::Basic_blob< Allocator, SHARING >::Deleter_raw
Internal deleter functor used if and only if S_IS_VANILLA_ALLOC is false and therefore only with Buf_ptr being boost::interprocess::shared_ptr or deleter-parameterized unique_ptr.
Basically its task is to undo the alloc_raw().allocate() call made when allocating a buffer in reserve(); the result of that call is passed-to shared_ptr::reset() or unique_ptr::reset(); as is alloc_raw() (for any aux allocation needed, but only for shared_ptr – unique_ptr needs no aux data); as is an instance of this Deleter_raw (to specifically dealloc the buffer when the ref-count reaches 0). (In the unique_ptr case there is no ref-count per se; or one can think of it as a ref-count that equals 1.)
Note that Deleter_raw is used only to dealloc the buffer actually controlled by the shared_ptr group or unique_ptr. shared_ptr will use the Allocator_raw directly to dealloc aux data. (We guess Deleter_raw is a separate argument to shared_ptr to support array deletion; boost::interprocess:shared_ptr does not provide built-in support for U[] as the pointee type; but the deleter can do whatever it wants/needs.)
Note: this is not used except with custom Allocator_raw. With std::allocator the usual default delete[] behavior is fine.
How to delete using it
operator()() gets invoked by smart-pointer machinery; the pointer to delete is passed to it as an arg. So we need not memorize it ourselves.
How to initialize
Before operator()() will work, it has to be loaded with the buffer size and allocator (both items needed by that operator in addition to the pointer itself). There are 3 ways to do this:
Construct via 2-arg ctor that takes those values. As usual the allocator object is to be copied (if it's even stateful; else that's a no-op).
Move-construct from already-initialized Deleter_raw.
First, default-construct. Then, move-assign from an existing already-initialized other Deleter_raw.
For ~brevity we won't fully enumerate who uses these and when; but mainly wanted to place you attention on that last possibility. Basic_blob::reserve_impl(), in the non-sharing, non-vanilla-alloc case, when it does need to allocate buf_ptr(), will exercise that use-case. E.g., Basic_blob default-ctor would default-ct a Deleter_raw; then the next reserve_impl() would 2-arg-ct Deleter_raw and then move-assign it onto the default-cted Deleter_raw.
Definition at line 1291 of file basic_blob.hpp.
Member Typedef Documentation
pointer
template<typename Allocator , bool SHARING> using flow::util::Basic_blob< Allocator, SHARING >::Deleter_raw::pointer = Pointer_raw
For boost::interprocess::shared_ptr and unique_ptr compliance (hence the irregular capitalization).
Definition at line 1305 of file basic_blob.hpp.
Pointer_raw
template<typename Allocator , bool SHARING> using flow::util::Basic_blob< Allocator, SHARING >::Deleter_raw::Pointer_raw = typename std::allocator_traits<Allocator_raw>::pointer
Short-hand for the allocator's pointer type, pointing to Basic_blob::value_type.
This may or may not simply be value_type*; in cases including SHM-storing allocators without a constant cross-process vaddr scheme it needs to be a fancy-pointer type instead (e.g., boost::interprocess::offset_ptr<value_type>).
Definition at line 1302 of file basic_blob.hpp.
Constructor & Destructor Documentation
Deleter_raw() [1/4]
template<typename Allocator , bool SHARING> flow::util::Basic_blob< Allocator, SHARING >::Deleter_raw::Deleter_raw
Default ctor: Deleter must never be invoked to delete anything in this state; suitable only for a null smart-pointer.
Without this a unique_ptr<..., Deleter_Raw> cannot be default-cted.
Definition at line 2817 of file basic_blob.hpp.
Deleter_raw() [2/4]
template<typename Allocator , bool SHARING> flow::util::Basic_blob< Allocator, SHARING >::Deleter_raw::Deleter_raw (const Allocator_raw & alloc_raw_src, size_type buf_sz) explicit
Constructs deleter by memorizing the allocator (of zero size if Allocator_raw is stateless, usually) used to allocate whatever shall be passed-to operator()(); and the size (in # of value_types) of the buffer allocated there.
The latter is required, at least technically, because Allocator_raw::deallocate() requires the value count, equal to that when allocate() was called, to be passed-in. Many allocators probably don't really need this, as array size is typically recorded invisibly near the array itself, but formally this is not guaranteed for all allocators.
Parameters
alloc_raw_src Allocator to copy and store.
buf_sz See above.
Definition at line 2825 of file basic_blob.hpp.
Deleter_raw() [3/4]
template<typename Allocator , bool SHARING> flow::util::Basic_blob< Allocator, SHARING >::Deleter_raw::Deleter_raw (Deleter_raw && moved_src)
Move-construction which may be required when we are used in unique_ptr.
This is equivalent to default-construction followed by move-assignment. See move-assignment operator doc header regarding why we are defining both of these.
Parameters
moved_src Moved guy. For cleanliness it becomes as-if default-cted.
Definition at line 2835 of file basic_blob.hpp.
References flow::util::Basic_blob< Allocator, SHARING >::operator=().
Deleter_raw() [4/4]
template<typename Allocator , bool SHARING> flow::util::Basic_blob< Allocator, SHARING >::Deleter_raw::Deleter_raw (const Deleter_raw & src) default
Copy-construction which may be required when we are used in boost::interprocess::shared_ptr which as of this writing requires copyable deleter in its .reset() and other places.
Parameters
src Copied guy.
Member Function Documentation
operator()()
template<typename Allocator , bool SHARING> void flow::util::Basic_blob< Allocator, SHARING >::Deleter_raw::operator() (Pointer_raw to_delete)
Deallocates using Allocator_raw::deallocate(), passing-in the supplied pointer (to value_type) to_delete and the number of value_types to delete (from ctor).
Parameters
to_delete Pointer to buffer to delete as supplied by shared_ptr or unique_ptr internals.
Definition at line 2921 of file basic_blob.hpp.
operator=() [1/2]
template<typename Allocator , bool SHARING> Basic_blob< Allocator, SHARING >::Deleter_raw & flow::util::Basic_blob< Allocator, SHARING >::Deleter_raw::operator= (const Deleter_raw & src)
Copy-assignment which is required when we are used in boost::interprocess::shared_ptr which as of this writing requires copyable deleter in its .reset() and other places.
Parameters
src Copied guy.
Returns
*this.
Definition at line 2893 of file basic_blob.hpp.
References flow::util::Basic_blob< Allocator, SHARING >::Deleter_raw::m_alloc_raw, and flow::util::Basic_blob< Allocator, SHARING >::Deleter_raw::m_buf_sz.
operator=() [2/2]
template<typename Allocator , bool SHARING> Basic_blob< Allocator, SHARING >::Deleter_raw & flow::util::Basic_blob< Allocator, SHARING >::Deleter_raw::operator= (Deleter_raw && moved_src)
Move-assignment which is required when we are used in unique_ptr.
User might invoke move-construction or move-assignment of the Basic_blob; this reduces to Basic_blob::assign() (move overload); which will do a swap – that ultimately will move the stored Deleter_raw up to a few times.
As of this writing we also manually overwrite .get_deleter() in one case in Basic_blob::reserve_impl(); so this is useful for that too.
Parameters
moved_src Moved guy. For cleanliness it becomes as-if default-cted (unless it is the same object as *this).
Returns
*this.
Definition at line 2850 of file basic_blob.hpp.
References flow::util::Basic_blob< Allocator, SHARING >::swap(), and flow::util::swap().
Member Data Documentation
m_alloc_raw
template<typename Allocator , bool SHARING> std::optional<Allocator_raw> flow::util::Basic_blob< Allocator, SHARING >::Deleter_raw::m_alloc_raw private
See ctor: the allocator that operator()() shall use to deallocate.
For stateless allocators this typically has size zero.
What's with optional<>?
...Okay, so actually this has size (whatever optional adds, probably a bool) + sizeof(Allocator_raw), the latter being indeed zero for stateless allocators. Why use optional<> though? Two reasons at least:
Stateful allocators often cannot be default-cted; and our own default ctor requires that m_alloc_raw is initialized to something... even though it (by default ctor contract) will never be accessed via operator()() in that form. Bottom line is a null smart-pointer needs a default-cted *this for at least some smart-pointer types (namely unique_ptr at least; probably not shared_ptr).
Yay, optional can be uninitialized.
Some allocators (such as boost::interprocess::allocator) are not assignable, only copy-constructible, while we need to be move-assignable (see doc header for move-assignment; spoiler alert: Basic_blob::reserve_impl() may need that).
Yay, optional<T> has .emplace() which will construct (including copy-construct) a T.
It is slightly annoying that we waste the extra space for optional internals even when Allocator_raw is stateless (and it is often stateless!). Plus, when Buf_ptr is shared_ptr instead of unique_ptr these bullet points probably do not apply. Probably some meta-programming thing could be done to avoid even this overhead, but in my (ygoldfel) opinion the overhead is so minor, it does not even rise to the level of a to-do.
Definition at line 1409 of file basic_blob.hpp.
Referenced by flow::util::Basic_blob< Allocator, SHARING >::Deleter_raw::operator=().
m_buf_sz
template<typename Allocator , bool SHARING> size_type flow::util::Basic_blob< Allocator, SHARING >::Deleter_raw::m_buf_sz private
See ctor and operator()(): the size of the buffer to deallocate.
Definition at line 1412 of file basic_blob.hpp.
Referenced by flow::util::Basic_blob< Allocator, SHARING >::Deleter_raw::operator=().
The documentation for this class was generated from the following file:
util/basic_blob.hpp