Flow: flow::async::Cross_thread_task_loop Class Reference
flow::async::Cross_thread_task_loop Class Reference
Concrete Concurrent_task_loop that is able to efficiently schedule Tasks within a given Op to execute in different threads while still properly avoiding concurrency.
#include <x_thread_task_loop.hpp>
Public Member Functions
Cross_thread_task_loop (log::Logger *logger_ptr, util::String_view nickname, size_t n_threads_or_zero, bool est_hw_core_sharing_helps_algo=false, bool est_hw_core_pinning_helps_algo=false, bool hw_threads_is_grouping_collated=false)
Constructs object, making it available for post() and similar work, but without starting any threads and hence without the ability to perform any work; call start() to spawn threads and perform work.
~Cross_thread_task_loop () override
See superclass destructor.
void start (Task &&init_task_or_empty=Task(), const Thread_init_func &thread_init_func_or_empty=Thread_init_func()) override
Implements superclass API.
void stop () override
Implements superclass API.
size_t n_threads () const override
Implements superclass API.
Op create_op () override
Implements superclass API.
const Op_list & per_thread_ops () override
Implements superclass API.
void post (Task &&task, Synchronicity synchronicity=Synchronicity::S_ASYNC) override
Implements superclass API.
void post (const Op &op, Task &&task, Synchronicity synchronicity=Synchronicity::S_ASYNC) override
Implements superclass API.
util::Scheduled_task_handle schedule_from_now (const Fine_duration &from_now, Scheduled_task &&task) override
Implements superclass API.
util::Scheduled_task_handle schedule_at (const Fine_time_pt &at, Scheduled_task &&task) override
Implements superclass API.
util::Scheduled_task_handle schedule_from_now (const Op &op, const Fine_duration &from_now, Scheduled_task &&task) override
Implements superclass API.
util::Scheduled_task_handle schedule_at (const Op &op, const Fine_time_pt &at, Scheduled_task &&task) override
See superclass API.
Task_engine_ptr task_engine () override
See superclass API.
Public Member Functions inherited from flow::async::Concurrent_task_loop
~Concurrent_task_loop () override
Any implementing subclass's destructor shall execute stop() – see its doc header please – and then clean up any resources.
virtual void start (Task &&init_task_or_empty=Task(), const Thread_init_func &thread_init_func_or_empty=Thread_init_func())=0
Starts all threads in the thread pool; any queued post()ed (and similar) tasks may begin executing immediately; and any future posted work may execute in these threads.
virtual void stop ()=0
Waits for any ongoing task(s)/completion handler(s) to return; then prevents any further-queued such tasks from running; then gracefully stops/joins all threads in pool; and then returns.
virtual size_t n_threads () const =0
How many threads does start() start?
virtual Op create_op ()=0
Return a new Op which can bundle together an arbitrary set of post()s that would result in the provided task functions executing non-concurrently.
virtual const Op_list & per_thread_ops ()=0
Returns the optional-use, pre-created collection of per-thread async::Op objects, such that the i-th Op therein corresponds to the i-th (of N, where N = # of threads in this pool) thread.
virtual void post (Task &&task, Synchronicity synchronicity=Synchronicity::S_ASYNC)=0
Cause the given Task (function) to execute within the thread pool as soon as possible, in the first thread available, in otherwise first-come-first-served fashion.
virtual void post (const Op &op, Task &&task, Synchronicity synchronicity=Synchronicity::S_ASYNC)=0
Identical to the other post() with the added constraint that no other Task also similarly posted with the equivalent async::Op may execute concurrently.
virtual util::Scheduled_task_handle schedule_from_now (const Fine_duration &from_now, Scheduled_task &&task)=0
Equivalent to 2-argument post() but execution is scheduled for later, after the given time period passes.
virtual util::Scheduled_task_handle schedule_at (const Fine_time_pt &at, Scheduled_task &&task)=0
Equivalent to 2-argument schedule_from_now() except one specifies an absolute time point instead of wait duration.
virtual util::Scheduled_task_handle schedule_from_now (const Op &op, const Fine_duration &from_now, Scheduled_task &&task)=0
Equivalent to 3-argument post() but execution is scheduled for later, after the given time period passes.
virtual util::Scheduled_task_handle schedule_at (const Op &op, const Fine_time_pt &at, Scheduled_task &&task)=0
Equivalent to 3-argument schedule_from_now() except one specifies an absolute time point instead of wait duration.
virtual Task_engine_ptr task_engine ()=0
Returns a pointer to an internal util::Task_engine (a/k/a boost.asio io_service) for the purpose of performing a boost.asio async_*() action on some boost.asio I/O object in the immediate near future.
Public Member Functions inherited from flow::util::Null_interface
virtual ~Null_interface ()=0
Boring virtual destructor.
Public Member Functions inherited from flow::log::Log_context
Log_context (Logger *logger=0)
Constructs Log_context by storing the given pointer to a Logger and a null Component.
template<typename Component_payload >
Log_context (Logger *logger, Component_payload component_payload)
Constructs Log_context by storing the given pointer to a Logger and a new Component storing the specified generically typed payload (an enum value).
Log_context (const Log_context &src)
Copy constructor that stores equal Logger* and Component values as the source.
Log_context (Log_context &&src)
Move constructor that makes this equal to src, while the latter becomes as-if default-constructed.
Log_context & operator= (const Log_context &src)
Assignment operator that behaves similarly to the copy constructor.
Log_context & operator= (Log_context &&src)
Move assignment operator that behaves similarly to the move constructor.
void swap (Log_context &other)
Swaps Logger pointers and Component objects held by *this and other.
Logger * get_logger () const
Returns the stored Logger pointer, particularly as many FLOW_LOG_*() macros expect.
const Component & get_log_component () const
Returns reference to the stored Component object, particularly as many FLOW_LOG_*() macros expect.
Private Types
using Task_qing_thread_ptr = boost::movelib::unique_ptr< Task_qing_thread >
Short-hand for smart pointer to Task_qing_thread.
Private Attributes
const std::string m_nickname
See constructor.
const size_t m_n_threads_or_zero
See constructor.
const bool m_est_hw_core_sharing_helps_algo
See constructor.
const bool m_est_hw_core_pinning_helps_algo
See constructor.
const bool m_hw_threads_is_grouping_collated
See constructor.
std::vector< Task_qing_thread_ptr > m_qing_threads
N task-execution-capable worker threads whose lifetimes equal those of *this, all sharing m_shared_task_engine.
Task_engine_ptr m_shared_task_engine
boost.asio Task_engine (a/k/a io_service) co-used by all m_qing_threads.
const Op_list m_per_thread_strands
See per_thread_ops(). The boost::any payload is always of the type async::Strand_ptr.
Related Functions
(Note that these are not member functions.)
template<>
Strand_ptr op_to_exec_ctx (Concurrent_task_loop *loop, const Op &op)
Template specialization for operation that obtains the underlying execution context, in this case a util::Strand, stored in an async::Op generated by the given Cross_thread_task_loop.
Related Functions inherited from flow::async::Concurrent_task_loop
template<typename Exec_ctx_ptr >
Exec_ctx_ptr op_to_exec_ctx (Concurrent_task_loop *loop, const Op &op)
Template specialization model for operation that obtains the underlying execution context, such as a util::Task_engine or util::Strand, stored in an async::Op generated by the given Concurrent_task_loop.
Additional Inherited Members
Public Types inherited from flow::async::Concurrent_task_loop
using Thread_init_func = Function< void(size_t thread_idx)>
Short-hand for the thread-initializer-function optional arg type to start().
Detailed Description
Concrete Concurrent_task_loop that is able to efficiently schedule Tasks within a given Op to execute in different threads while still properly avoiding concurrency.
See also
Concurrent_task_loop doc header for an overview of this class in the context of sibling classes (alternatives).
By definition all you need to know to use it is in the super-interface Concurrent_task_loop doc header (except constructor semantics of course). However, in choosing this vs. a sibling type, one must at least loosely understand its underlying behavior. To summarize the behavior of this class beyond the interface guarantees:
A no-Op stand-alone Task executes simply as soon as any one thread becomes available.
An Op-sharing Task may execute in a different thread than another Task sharing the same Op. (They just won't execute concurrently.) If you're familiar with boost.asio: This internally uses util::Strand to achieve that behavior.
per_thread_ops() is organized as follows: If N worker threads are created, then accordingly N strands are created internally. Internally, per_thread_ops()[i] is really the i-th strand, not any thread, and hence even though it is "per-thread," actual execution may occur in other thread(s) than the i-th. However, user logic can remain exactly as if it were truly per-thread. Why? Answer: A thread is a thing where stuff can only execute serially within it – but so is a strand! And we have N of those, just like we have N threads; so it works by symmetry. So if there are N strands across N threads, then subdividing work among the N strands results in the same non-concurrency guarantees as doing so among the N threads directly. In fact, it might be somewhat more efficient in using idle thread time across the pool.
This allows for an interesting experiment if a legacy application is written in an explicitly per-thread way, maintaining per-thread data structures for example: Suppose one tweaks it to use Concurrent_task_loop. One can convert its tasks (conceptually speaking) and data structures to refer to per_thread_ops()-returned N Ops, instead of the N threads directly, and further modify it to work with a Concurrent_task_loop. Now, if the latter is a Segregated_thread_task_loop, then the resulting program will work identically (functionally speaking) to how it worked before these changes: one has perhaps made it more conceptual/readable/maintainable, but the thread arch is unchanged. The interesting part is next: To see whether one can gain efficiency from using a strand-based approach, but without making any real design changes in this legacy application, all one has to do now is replace the Segregated_thread_task_loop construction with a Cross_thread_task_loop one. All application logic can remain exactly identical (after initialization), yet efficiency gains might be achieved for "free" – simply by changing the concrete type of the central Concurrent_task_loop. One can even easily use one or the other based on config, changing between the two in the field.
Todo:
Add dynamic configurability of low-level thread/core behavior of Cross_thread_task_loop, Segregated_thread_task_loop, and the Concurrent_task_loop interface generally, as these parameters (including n_threads_or_zero, est_hw_core_sharing_helps_algo, est_hw_core_pinning_helps_algo) can only be set at construction time even though start() and stop() can be invoked anytime. For instance a non-virtual configure() method could be added to each Concurrent_task_loop subclass, potentially with different signatures. Note, also, that the decision to have stop() exit the actual threads, in addition to making some things easier to code/reason about internally, is also more amenable to these dynamic changes – messing with threading behavior dynamically is easier if one can exit and re-spawn the thread pool.
Regarding the dynamic-configurability to-do above: By my (ygoldfel) off-top-of-head estimation, it's easier to add in Cross_thread_task_loop than in Segregated_thread_task_loop, as there is exactly 1 util::Task_engine per *this in the former, while Segregated_thread_task_loop has N of them, 1 per thread. So changing the desired thread count, in particular, would be more difficult in the latter case, as one must not lose any enqueued tasks through stop() and start(). It would not be unreasonable to make one more dynamically-configurable than the other.
One must also be careful about the legacy-ish mechanism per_thread_ops() in this context.
Definition at line 88 of file x_thread_task_loop.hpp.
Member Typedef Documentation
Task_qing_thread_ptr
using flow::async::Cross_thread_task_loop::Task_qing_thread_ptr = boost::movelib::unique_ptr<Task_qing_thread> private
Short-hand for smart pointer to Task_qing_thread.
Definition at line 282 of file x_thread_task_loop.hpp.
Constructor & Destructor Documentation
Cross_thread_task_loop()
flow::async::Cross_thread_task_loop::Cross_thread_task_loop (log::Logger * logger_ptr, util::String_view nickname, size_t n_threads_or_zero, bool est_hw_core_sharing_helps_algo = false, bool est_hw_core_pinning_helps_algo = false, bool hw_threads_is_grouping_collated = false) explicit
Constructs object, making it available for post() and similar work, but without starting any threads and hence without the ability to perform any work; call start() to spawn threads and perform work.
The arguments n_threads_or_zero and ones following it should be viewed as configuration for the next start() call.
Parameters
logger_ptr Logger to use for subsequently logging.
nickname Brief, human-readable nickname of the new thread pool, as of this writing for logging only.
n_threads_or_zero If non-zero, start() will start exactly this many worker threads; and the system will be entirely entrusted with the question of which thread is assigned to which processor core and any subsequent migration. If zero, start() attempts to optimize the thread count and thread-to-core relationship itself, per optimal_worker_thread_count_per_pool() and optimize_pinning_in_thread_pool(). The thread pool will choose the worker thread count and any thread-to-core relationships as per those methods, having made the assumptions documented for those functions.
est_hw_core_sharing_helps_algo See optimal_worker_thread_count_per_pool().
est_hw_core_pinning_helps_algo See optimize_pinning_in_thread_pool().
hw_threads_is_grouping_collated See optimize_pinning_in_thread_pool().
Definition at line 29 of file x_thread_task_loop.cpp.
References m_shared_task_engine, and flow::async::S_ASYNC.
~Cross_thread_task_loop()
flow::async::Cross_thread_task_loop::~Cross_thread_task_loop () override
See superclass destructor.
Definition at line 71 of file x_thread_task_loop.cpp.
References FLOW_LOG_INFO, and stop().
Member Function Documentation
create_op()
Op flow::async::Cross_thread_task_loop::create_op () override virtual
Implements superclass API.
In this implementation: async::Op has the "weight" of a shared_ptr<> and internally corresponds to a util::Strand.
Returns
See superclass API.
Implements flow::async::Concurrent_task_loop.
Definition at line 267 of file x_thread_task_loop.cpp.
References m_shared_task_engine.
n_threads()
size_t flow::async::Cross_thread_task_loop::n_threads () const override virtual
Implements superclass API.
Returns
See superclass API.
Implements flow::async::Concurrent_task_loop.
Definition at line 262 of file x_thread_task_loop.cpp.
References m_qing_threads.
Referenced by post(), schedule_from_now(), and start().
per_thread_ops()
const Op_list & flow::async::Cross_thread_task_loop::per_thread_ops () override virtual
Implements superclass API.
In this implementation: Each pre-created Op internally corresponds to a pre-created long-lived util::Strand.
Returns
See superclass API.
Implements flow::async::Concurrent_task_loop.
Definition at line 272 of file x_thread_task_loop.cpp.
References m_per_thread_strands.
post() [1/2]
void flow::async::Cross_thread_task_loop::post (const Op & op, Task && task, Synchronicity synchronicity = Synchronicity::S_ASYNC) override virtual
Implements superclass API.
In this implementation: task will execute as soon as a thread is available, because no other applicable work is forthcoming, plus one more constraint: It will not allow task to execute concurrently to any other Task also associated with op. The latter is accomplished on account of Op internally being associated with a util::Strand.
Parameters
op See superclass API.
task See superclass API.
synchronicity See superclass API.
Implements flow::async::Concurrent_task_loop.
Definition at line 292 of file x_thread_task_loop.cpp.
References FLOW_LOG_TRACE, flow::log::Log_context::get_logger(), n_threads(), flow::async::op_to_exec_ctx< Strand_ptr >(), and post().
post() [2/2]
void flow::async::Cross_thread_task_loop::post (Task && task, Synchronicity synchronicity = Synchronicity::S_ASYNC) override virtual
Implements superclass API.
In this implementation: task will execute as soon as a thread is available, because no other applicable work is forthcoming.
Parameters
task See superclass API.
synchronicity See superclass API.
Implements flow::async::Concurrent_task_loop.
Definition at line 277 of file x_thread_task_loop.cpp.
References FLOW_LOG_TRACE, flow::log::Log_context::get_logger(), and m_shared_task_engine.
Referenced by post(), flow::async::Single_thread_task_loop::post(), and start().
schedule_at() [1/2]
util::Scheduled_task_handle flow::async::Cross_thread_task_loop::schedule_at (const Fine_time_pt & at, Scheduled_task && task) override virtual
Implements superclass API.
See also 1-arg post().
Parameters
at See superclass API.
task See superclass API.
Returns
See superclass API.
Implements flow::async::Concurrent_task_loop.
Definition at line 396 of file x_thread_task_loop.cpp.
References schedule_from_now().
Referenced by flow::async::Single_thread_task_loop::schedule_at().
schedule_at() [2/2]
util::Scheduled_task_handle flow::async::Cross_thread_task_loop::schedule_at (const Op & op, const Fine_time_pt & at, Scheduled_task && task) override virtual
See superclass API.
See also 2-arg post().
Parameters
op See superclass API.
at See superclass API.
task See superclass API.
Returns
See superclass API.
Implements flow::async::Concurrent_task_loop.
Definition at line 406 of file x_thread_task_loop.cpp.
References schedule_from_now().
schedule_from_now() [1/2]
util::Scheduled_task_handle flow::async::Cross_thread_task_loop::schedule_from_now (const Fine_duration & from_now, Scheduled_task && task) override virtual
Implements superclass API.
See also 1-arg post().
Parameters
from_now See superclass API.
task See superclass API.
Returns
See superclass API.
Implements flow::async::Concurrent_task_loop.
Definition at line 319 of file x_thread_task_loop.cpp.
References flow::async::cpu_idx(), FLOW_LOG_TRACE_WITHOUT_CHECKING, flow::log::Log_context::get_log_component(), flow::log::Log_context::get_logger(), m_shared_task_engine, n_threads(), flow::log::S_TRACE, and flow::util::schedule_task_from_now().
Referenced by schedule_at(), flow::async::Single_thread_task_loop::schedule_from_now(), and schedule_from_now().
schedule_from_now() [2/2]
util::Scheduled_task_handle flow::async::Cross_thread_task_loop::schedule_from_now (const Op & op, const Fine_duration & from_now, Scheduled_task && task) override virtual
Implements superclass API.
See also 2-arg post().
Parameters
op See superclass API.
from_now See superclass API.
task See superclass API.
Returns
See superclass API.
Implements flow::async::Concurrent_task_loop.
Definition at line 351 of file x_thread_task_loop.cpp.
References flow::async::cpu_idx(), FLOW_LOG_TRACE_WITHOUT_CHECKING, flow::log::Log_context::get_log_component(), flow::log::Log_context::get_logger(), m_shared_task_engine, n_threads(), flow::async::op_to_exec_ctx< Strand_ptr >(), flow::log::S_TRACE, schedule_from_now(), and flow::util::schedule_task_from_now().
start()
void flow::async::Cross_thread_task_loop::start (Task && init_task_or_empty = Task(), const Thread_init_func & thread_init_func_or_empty = Thread_init_func()) override virtual
Implements superclass API.
In this implementation this essentially involves a single Task_engine::restart(), followed by starting N threads, each of which executing a long-running Task_engine::run().
Logging subtlety for large thread pools
If n_threads() is large – e.g., hundreds – this method may produce a large number of log::Sev::S_INFO level log messages to log::Logger at get_logger(). There may be a few lines, split among this thread and the spawned thread, per each of n_threads() threads. In addition stop() and/or the destructor will produce a similar volume of INFO messages.
You may, however, use log::Config::this_thread_verbosity_override_auto(X) just before start(). X = log::Sev::S_NONE will disable all logging; while X = log::Sev::S_WARNING will skip anything but error conditions.
This is not special and can be done anytime in any context: it affects any logging through log::Config in this thread. In addition: If indeed such an X is set at entry to start(), we will intentionally affect each spawned thread as well, albeit only around startup and shutdown. This is for your convenience.
Parameters
init_task_or_empty See superclass API.
thread_init_func_or_empty See superclass API.
Implements flow::async::Concurrent_task_loop.
Definition at line 81 of file x_thread_task_loop.cpp.
References FLOW_LOG_INFO, FLOW_LOG_WARNING, flow::log::Log_context::get_logger(), m_est_hw_core_pinning_helps_algo, m_est_hw_core_sharing_helps_algo, m_hw_threads_is_grouping_collated, m_n_threads_or_zero, m_nickname, m_qing_threads, m_shared_task_engine, n_threads(), flow::async::optimize_pinning_in_thread_pool(), flow::util::ostream_op_string(), post(), and flow::async::S_ASYNC_AND_AWAIT_CONCURRENT_COMPLETION.
Referenced by flow::async::Single_thread_task_loop::start().
stop()
void flow::async::Cross_thread_task_loop::stop () override virtual
Implements superclass API.
In this implementation this essentially boils down to a single Task_engine::stop(), followed by joining each thread started by start().
Logging subtlety for large thread pools
A similar note from start() doc header applies here. Again: you may set an override verbosity just ahead of stop() to reduce or disable logging if desired.
In addition, for your convenience: Any shutdown logging within each of the spawned (now shutting down) threads will follow the override (if any) you had specified ahead of start().
Implements flow::async::Concurrent_task_loop.
Definition at line 192 of file x_thread_task_loop.cpp.
References FLOW_LOG_INFO, m_nickname, m_qing_threads, and m_shared_task_engine.
Referenced by flow::async::Single_thread_task_loop::stop(), and ~Cross_thread_task_loop().
task_engine()
Task_engine_ptr flow::async::Cross_thread_task_loop::task_engine () override virtual
See superclass API.
In this implementation: Internally there is just this Task_engine, and that is what this returns. The load-balancing is performed directly by boost.asio itself. (Reminder: general Concurrent_task_loop-using code would not rely on this implementation information.) (Reminder: be very sure you understand what will happen if/when you pass this into a boost.asio-compliant I/O object's constructor or similar. See the warning on this topic in Concurrent_task_loop doc header.)
Returns
See superclass API.
Implements flow::async::Concurrent_task_loop.
Definition at line 414 of file x_thread_task_loop.cpp.
References m_shared_task_engine.
Referenced by flow::async::Single_thread_task_loop::task_engine().
Friends And Related Function Documentation
op_to_exec_ctx()
Strand_ptr op_to_exec_ctx< Strand_ptr > (Concurrent_task_loop * loop, const Op & op) related
Template specialization for operation that obtains the underlying execution context, in this case a util::Strand, stored in an async::Op generated by the given Cross_thread_task_loop.
boost.asio tip: The returned util::Strand may be useful not only as an argument to bind_executor() (formerly Strand::wrap(), now deprecated) but can also be passed in lieu of a util::Task_engine into boost.asio-enabled I/O object constructors (util::Timer, boost::asio::ip::tcp::socket, etc.). The latter use uses the Strand as an "execution context."
Note Concurrent_task_loop::task_engine() is spiritually related to this function; but while that one gives one a util::Task_engine, which corresponds to the entire thread pool, this one returns an execution context specifically assigned to a multi-step async op op.
See also
Concurrent_task_loop doc header for discussion.
Parameters
loop Loop object that, one way or another, generated and returned op. Behavior is undefined if the concrete pointed-to type is not Cross_thread_task_loop. (assertion may trip).
op async::Op from *loop from which to extract the execution context on which you'd like to perform custom boost.asio work. Behavior is undefined if it is not from *loop (assertion may trip).
Returns
Pointer to a mutable util::Strand created from util::Task_engine E such that loop->task_engine() == &E.
Member Data Documentation
m_est_hw_core_pinning_helps_algo
const bool flow::async::Cross_thread_task_loop::m_est_hw_core_pinning_helps_algo private
See constructor.
Definition at line 293 of file x_thread_task_loop.hpp.
Referenced by start().
m_est_hw_core_sharing_helps_algo
const bool flow::async::Cross_thread_task_loop::m_est_hw_core_sharing_helps_algo private
See constructor.
Definition at line 291 of file x_thread_task_loop.hpp.
Referenced by start().
m_hw_threads_is_grouping_collated
const bool flow::async::Cross_thread_task_loop::m_hw_threads_is_grouping_collated private
See constructor.
Definition at line 295 of file x_thread_task_loop.hpp.
Referenced by start().
m_n_threads_or_zero
const size_t flow::async::Cross_thread_task_loop::m_n_threads_or_zero private
See constructor.
Warning
Not safe to use this in lieu of n_threads() when this is in fact zero.
Definition at line 289 of file x_thread_task_loop.hpp.
Referenced by start().
m_nickname
const std::string flow::async::Cross_thread_task_loop::m_nickname private
See constructor.
Definition at line 287 of file x_thread_task_loop.hpp.
Referenced by start(), and stop().
m_per_thread_strands
const Op_list flow::async::Cross_thread_task_loop::m_per_thread_strands private
See per_thread_ops(). The boost::any payload is always of the type async::Strand_ptr.
Definition at line 304 of file x_thread_task_loop.hpp.
Referenced by per_thread_ops().
m_qing_threads
std::vector<Task_qing_thread_ptr> flow::async::Cross_thread_task_loop::m_qing_threads private
N task-execution-capable worker threads whose lifetimes equal those of *this, all sharing m_shared_task_engine.
Definition at line 298 of file x_thread_task_loop.hpp.
Referenced by n_threads(), start(), and stop().
m_shared_task_engine
Task_engine_ptr flow::async::Cross_thread_task_loop::m_shared_task_engine private
boost.asio Task_engine (a/k/a io_service) co-used by all m_qing_threads.
Definition at line 301 of file x_thread_task_loop.hpp.
Referenced by create_op(), Cross_thread_task_loop(), post(), schedule_from_now(), start(), stop(), and task_engine().
The documentation for this class was generated from the following files:
async/x_thread_task_loop.hpp
async/async_fwd.hpp
async/x_thread_task_loop.cpp