Flow: flow::async::Op_list Class Reference
flow::async::Op_list Class Reference
Simple, immutable vector-like sequence of N opaque async::Op objects, usually corresponding to N worker threads, with typically used operations such as [index] and random Op selection.
#include <op.hpp>
Public Types
using Create_op_func = Function< Op(size_t target_op_idx)>
Short-hand for function that that takes the target Op-list index and returns new async::Op whose copy is suitable as the permanent Op at that index.
Public Member Functions
Op_list (log::Logger *logger_ptr, size_t n_ops, const Create_op_func &create_op_func)
Populates the async::Op list, which is immutable after this returns.
size_t size () const
Returns the number of async::Op stored in this Op_list.
const Op & operator[] (size_t idx) const
Returns reference to immutable async::Op at the given index in [0, size()).
const Op & random_op (size_t *chosen_idx=0) const
Returns (*this)[R], where we randomly select R as if by random_idx() and communicate it to the caller via optional out-arg.
size_t random_idx () const
Returns a randomly selected index from range [O, size()).
const std::vector< Op > & ops_sequence () const
Returns reference to immutable internally stored sequence of async::Op in order consistent with other methods of this class.
Public Member Functions inherited from flow::log::Log_context
Log_context (Logger *logger=0)
Constructs Log_context by storing the given pointer to a Logger and a null Component.
template<typename Component_payload >
Log_context (Logger *logger, Component_payload component_payload)
Constructs Log_context by storing the given pointer to a Logger and a new Component storing the specified generically typed payload (an enum value).
Log_context (const Log_context &src)
Copy constructor that stores equal Logger* and Component values as the source.
Log_context (Log_context &&src)
Move constructor that makes this equal to src, while the latter becomes as-if default-constructed.
Log_context & operator= (const Log_context &src)
Assignment operator that behaves similarly to the copy constructor.
Log_context & operator= (Log_context &&src)
Move assignment operator that behaves similarly to the move constructor.
void swap (Log_context &other)
Swaps Logger pointers and Component objects held by *this and other.
Logger * get_logger () const
Returns the stored Logger pointer, particularly as many FLOW_LOG_*() macros expect.
const Component & get_log_component () const
Returns reference to the stored Component object, particularly as many FLOW_LOG_*() macros expect.
Private Attributes
std::vector< Op > m_ops
The payload of async::Op objects.
util::Rnd_gen_uniform_range_mt< size_t > m_rnd_op_idx
Random number facility for generating random indices in [0, m_ops.size()).
Detailed Description
Simple, immutable vector-like sequence of N opaque async::Op objects, usually corresponding to N worker threads, with typically used operations such as [index] and random Op selection.
Thread safety
The object is immutable after construction; therefore each *this is safe for concurrent Op_list method calls.
Design rationale
This really only exists, at least originally, in service of Concurrent_task_loop::per_thread_ops() (which returns an Op_list nowadays). An alternative approach would have been to move these simple facilities directly into Concurrent_task_loop superclass. Historically that's how it started; there was a vector<Op> directly therein. It worked fine but (1) complicated the otherwise pure interface Concurrent_task_loop into part-interface, part-logic-store-for-subclasses; and (2) increased the required cooperation between subclass and superclass (which is cute in finished code but harder to build on/maintain). Hence, as experienced OO coders learn eventually, composition (where X is a member of Y) is more flexible and no more verbose than inheritance (where Y is a subclass of X); in both case the desired/achieved effect is to let Y leverage X's abilities. Hence Op_list is a separate little class to be included as a member by whatever subclass of Concurrent_task_loop needs it.
It is also a good sign that Op_list stands alone as a clean, reusable concept. It may find other uses than in Concurrent_task_loop::per_thread_ops().
Definition at line 56 of file op.hpp.
Member Typedef Documentation
Create_op_func
using flow::async::Op_list::Create_op_func = Function<Op (size_t target_op_idx)>
Short-hand for function that that takes the target Op-list index and returns new async::Op whose copy is suitable as the permanent Op at that index.
Definition at line 66 of file op.hpp.
Constructor & Destructor Documentation
Op_list()
flow::async::Op_list::Op_list (log::Logger * logger_ptr, size_t n_ops, const Create_op_func & create_op_func) explicit
Populates the async::Op list, which is immutable after this returns.
Caller may permanently store *this with a const qualifier.
Parameters
logger_ptr Logger to which to log subsequently.
n_ops How many Ops will we permanently store? The index range will therefore be [0, n_ops) or [0, n_ops - 1). Must be at least 1, or assert() trips.
create_op_func Caller's factory function that will generate the actual n_ops async::Op objects to store. The caller shall populate each Op it returns with a (small) value of whatever arbitrary type it wants. create_op_func() shall be called, in order, n_ops times synchronously, with index argument ranging fully through [0, n_ops). A copy of Op create_op_func(idx) is saved, and subsequently (*this)[idx] will return a reference to this permanently stored copy.
Definition at line 26 of file op.cpp.
References FLOW_LOG_INFO, m_ops, and flow::async::S_ASYNC.
Member Function Documentation
operator[]()
const Op & flow::async::Op_list::operator[] (size_t idx) const
Returns reference to immutable async::Op at the given index in [0, size()).
It is just like the const variety of "vector<Op>::operator[]".
Parameters
idx Value in [0, size()). assert() trips if out of range.
Returns
See above. Note the address stored in the returned reference is valid until destructor runs; hence it's not necessary (though cheap) to copy the Op.
Definition at line 46 of file op.cpp.
References m_ops.
Referenced by random_op().
ops_sequence()
const std::vector< Op > & flow::async::Op_list::ops_sequence () const
Returns reference to immutable internally stored sequence of async::Op in order consistent with other methods of this class.
Returns
See above.
Definition at line 70 of file op.cpp.
References m_ops.
random_idx()
size_t flow::async::Op_list::random_idx () const
Returns a randomly selected index from range [O, size()).
Returns
See above.
Definition at line 65 of file op.cpp.
References m_rnd_op_idx.
Referenced by flow::async::Segregated_thread_task_loop::post(), random_op(), flow::async::Segregated_thread_task_loop::schedule_from_now(), and flow::async::Segregated_thread_task_loop::task_engine().
random_op()
const Op & flow::async::Op_list::random_op (size_t * chosen_idx = 0) const
Returns (*this)[R], where we randomly select R as if by random_idx() and communicate it to the caller via optional out-arg.
Logs a TRACE message.
Parameters
chosen_idx If not null, then a post-condition is that *chosen_idx has been set to the index of the returned Op.
Returns
See above. Note the address stored in the returned reference is valid until destructor runs; hence it's not necessary (though cheap) to copy the Op.
Definition at line 51 of file op.cpp.
References FLOW_LOG_TRACE, operator[](), random_idx(), and size().
Referenced by flow::async::Segregated_thread_task_loop::create_op().
size()
size_t flow::async::Op_list::size () const
Returns the number of async::Op stored in this Op_list.
The returned value is always the same.
Returns
See above.
Definition at line 41 of file op.cpp.
References m_ops.
Referenced by random_op().
Member Data Documentation
m_ops
std::vector<Op> flow::async::Op_list::m_ops private
The payload of async::Op objects.
This is effectively const (immutable) after construction. While Op copy is light-weight, the effective constness we can nevertheless save a copy by always taking addresses like &m_ops[i] when possible.
Definition at line 138 of file op.hpp.
Referenced by Op_list(), operator[](), ops_sequence(), and size().
m_rnd_op_idx
util::Rnd_gen_uniform_range_mt<size_t> flow::async::Op_list::m_rnd_op_idx mutable private
Random number facility for generating random indices in [0, m_ops.size()).
Thread-safe sans mutex.
Implementation detail
m_rnd_op_idx() is the only used operation, and it emits a pseudo-random number. This can be viewed as as merely accessing an outside resource, conceptually, hence such operations should probably be const, as mutexes are for example. So, as with a mutex, make it mutable.
Definition at line 148 of file op.hpp.
Referenced by random_idx().
The documentation for this class was generated from the following files:
async/op.hpp
async/op.cpp