Flow: flow::net_flow::Port_space Class Reference
flow::net_flow::Port_space Class Reference
Internal net_flow class that maintains the available Flow-protocol port space, somewhat similarly to the classic TCP or UDP port scheme.
#include <port_space.hpp>
Public Member Functions
Port_space (log::Logger *logger)
Constructs the Port_space with all ports available.
flow_port_t reserve_port (flow_port_t port, Error_code *err_code)
Reserve the specified service port, or reserve_ephemeral_port() if the specified port is S_PORT_ANY.
flow_port_t reserve_ephemeral_port (Error_code *err_code)
Reserve a randomly chosen available ephemeral port.
void return_port (flow_port_t port, Error_code *err_code)
Return a previously reserved port (of any type).
Public Member Functions inherited from flow::log::Log_context
Log_context (Logger *logger=0)
Constructs Log_context by storing the given pointer to a Logger and a null Component.
template<typename Component_payload >
Log_context (Logger *logger, Component_payload component_payload)
Constructs Log_context by storing the given pointer to a Logger and a new Component storing the specified generically typed payload (an enum value).
Log_context (const Log_context &src)
Copy constructor that stores equal Logger* and Component values as the source.
Log_context (Log_context &&src)
Move constructor that makes this equal to src, while the latter becomes as-if default-constructed.
Log_context & operator= (const Log_context &src)
Assignment operator that behaves similarly to the copy constructor.
Log_context & operator= (Log_context &&src)
Move assignment operator that behaves similarly to the move constructor.
void swap (Log_context &other)
Swaps Logger pointers and Component objects held by *this and other.
Logger * get_logger () const
Returns the stored Logger pointer, particularly as many FLOW_LOG_*() macros expect.
const Component & get_log_component () const
Returns reference to the stored Component object, particularly as many FLOW_LOG_*() macros expect.
Static Public Attributes
static const size_t S_NUM_PORTS = size_t(std::numeric_limits<flow_port_t>::max()) + 1
Total number of ports in the port space, including S_PORT_ANY.
static const size_t S_NUM_SERVICE_PORTS = S_NUM_PORTS / 2 - 1
Total number of "service" ports (ones that can be reserved by number with reserve_port()).
static const size_t S_NUM_EPHEMERAL_PORTS = S_NUM_PORTS - S_NUM_SERVICE_PORTS - 1
Total number of "ephemeral" ports (ones reserved at random with reserve_ephemeral_port()).
static const flow_port_t S_FIRST_SERVICE_PORT = 1
The port number of the lowest service port.
static const flow_port_t S_FIRST_EPHEMERAL_PORT = S_FIRST_SERVICE_PORT + S_NUM_SERVICE_PORTS
The port number of the lowest ephemeral port.
Private Types
using Bit_set = boost::dynamic_bitset<>
Short-hand for bit set of arbitary length, representing a port set (each bit is a port; 1 open, 0 reserved).
using Random_generator = util::Rnd_gen_uniform_range_base::Random_generator
Random number generator.
using flow_port_sans_overflow_t = uint32_t
A type same as flow_port_t but larger, useful when doing arithmetic that might hit overflow in corner cases.
Private Member Functions
size_t find_available_port_bit_idx (const Bit_set &ports)
Helper method that, given a reference to a bit set representing available ports (1 available, 0 reserved) finds a random available (1) port in that bit set.
Static Private Member Functions
static bool is_service_port (flow_port_t port)
Returns true if and only if the given port is a service port (as opposed to ephemeral or S_PORT_ANY).
Private Attributes
Bit_set m_service_ports
Current service port set.
Bit_set m_ephemeral_ports
Current ephemeral port set; indexing analogous to m_service_ports but starting at S_FIRST_EPHEMERAL_PORT.
Bit_set m_ephemeral_and_recent_ephemeral_ports
Set representing the union of the set of current reserved ephemeral ports and the set of the last up-to-S_MAX_RECENT_EPHEMERAL_PORTS returned and available ephemeral ports.
std::queue< flow_port_t > m_recent_ephemeral_ports
A FIFO of recently used but currently available ephemeral ports.
Random_generator m_rnd_generator
Random number generator for picking ports.
Static Private Attributes
static const size_t S_MAX_RECENT_EPHEMERAL_PORTS = S_NUM_EPHEMERAL_PORTS / 32
The maximum size of m_recent_ephemeral_ports.
Detailed Description
Internal net_flow class that maintains the available Flow-protocol port space, somewhat similarly to the classic TCP or UDP port scheme.
The class's main use case it to be stored in a Node, though it could be used in other scenarios of desired. net_flow users should not use this class directly.
The port scheme is similar to TCP or UDP's but not identical. net_flow::flow_port_t maximum value defines the total number of ports available. Port S_PORT_ANY is a special value and cannot be used as a port. The remaining port space is divided into 2 parts: S_NUM_SERVICE_PORTS "service ports" and S_NUM_EPHEMERAL_PORTS "ephemeral ports." Thus the port ranges are [S_FIRST_SERVICE_PORT, S_FIRST_SERVICE_PORT + S_NUM_SERVICE_PORTS - 1] and [S_FIRST_EPHEMERAL_PORT, S_FIRST_EPHEMERAL_PORT + S_NUM_EPHEMERAL_PORTS - 1], respectively. Both types of ports are on the same number line so that Flow-protocol socket addressing can be symmetrical between client and server once a connection has been set up.
At construction all ports are available. A port can then be "reserved" by the class user. That port can then no longer be reserved until it is "returned" via return_port().
One can either reserve to a specified service port (reserve_port()) or a random available ephemeral port (reserve_ephemeral_port()). Unlike with TCP and UDP ports, it's not possible to reserve a user-supplied ephemeral port (reserve_port() will fail in this case). Therefore, service ports and ephemeral ports are entirely separate (it is not merely a convention as in TCP and UDP ports).
While this is transparent to the class user, this implementation avoids reserving ephemeral ports that have been recently returned, to avoid confusion in the socket implementation. It does so by keeping a queue (of some reasonably large length up to a maximum size) of such ports. Ports within this queue are reserved only if there is absolutely no ephemeral port space left other than the ports on the queue.
Main (all?) differences from TCP/UDP ports: different allocation of ephemeral vs. non-ephemeral port space; no privileged ports; enforced inability to reserve a specific ephemeral port; no service name -> port number mapping (yet?).
Thread safety
Separate objects: All functionality safe for simultaneous execution from multiple threads. Same object: Not safe to execute a non-const operation simultaneously with any other operation; otherwise safe. Rationale: Node only deals with its Port_space in thread W.
Implementation notes
bit_set objects are used to represent the set of reserved vs. available ports of a given type (0 means taken, 1 means available). This is not only quick and memory-compact but also allows a convenient search for a random available port (random bit -> find_next() if not open -> find_first() if still not found -> no ports available if even still not found).
Todo:
While the ephemeral port reuse avoidance works well within a single Port_space lifetime, it does not carry over across different Port_spaces. I.e., if Port_space is destructed and then constructed, the container of recently used ports starts out empty, so a port may (with some low but sizable probability) be reused. This could be avoided by persisting (e.g., via boost.serialization) those structures to disk (perhaps at a user-supplied boost::filesystem::path) in ~Port_space(). This wouldn't work if Port_space crashed, however. To solve that, we could easily start a thread in Port_space() (and join it in ~Port_space()) that would save that state every N seconds. If that's not enough, we can instead have that thread run a boost.asio io_service::run() event loop and io_service::post() the save operation onto it (from arbitrary threads) each time a new ephemeral port is reserved (with some kind of protection against incessant disk writing built into this worker thread; e.g., don't save if saved in the last N msec).
Definition at line 91 of file port_space.hpp.
Member Typedef Documentation
Bit_set
using flow::net_flow::Port_space::Bit_set = boost::dynamic_bitset<> private
Short-hand for bit set of arbitary length, representing a port set (each bit is a port; 1 open, 0 reserved).
Definition at line 164 of file port_space.hpp.
flow_port_sans_overflow_t
using flow::net_flow::Port_space::flow_port_sans_overflow_t = uint32_t private
A type same as flow_port_t but larger, useful when doing arithmetic that might hit overflow in corner cases.
Definition at line 170 of file port_space.hpp.
Random_generator
using flow::net_flow::Port_space::Random_generator = util::Rnd_gen_uniform_range_base::Random_generator private
Random number generator.
Definition at line 167 of file port_space.hpp.
Constructor & Destructor Documentation
Port_space()
flow::net_flow::Port_space::Port_space (log::Logger * logger) explicit
Constructs the Port_space with all ports available.
Parameters
logger The Logger implementation to use subsequently.
Definition at line 45 of file port_space.cpp.
References FLOW_LOG_INFO, m_ephemeral_and_recent_ephemeral_ports, m_ephemeral_ports, m_service_ports, S_FIRST_EPHEMERAL_PORT, S_FIRST_SERVICE_PORT, S_NUM_EPHEMERAL_PORTS, S_NUM_SERVICE_PORTS, and flow::net_flow::S_PORT_ANY.
Member Function Documentation
find_available_port_bit_idx()
size_t flow::net_flow::Port_space::find_available_port_bit_idx (const Bit_set & ports) private
Helper method that, given a reference to a bit set representing available ports (1 available, 0 reserved) finds a random available (1) port in that bit set.
Parameters
ports A bit set representing port availability (e.g., m_ephemeral_ports).
Returns
The bit index of a random available port, or Bit_set::npos if all are taken.
Definition at line 261 of file port_space.cpp.
References m_rnd_generator.
Referenced by reserve_ephemeral_port().
is_service_port()
bool flow::net_flow::Port_space::is_service_port (flow_port_t port) static private
Returns true if and only if the given port is a service port (as opposed to ephemeral or S_PORT_ANY).
Parameters
port Port to check.
Returns
See above.
Definition at line 67 of file port_space.cpp.
References flow::util::in_closed_open_range(), S_FIRST_SERVICE_PORT, and S_NUM_SERVICE_PORTS.
Referenced by reserve_port(), and return_port().
reserve_ephemeral_port()
flow_port_t flow::net_flow::Port_space::reserve_ephemeral_port (Error_code * err_code)
Reserve a randomly chosen available ephemeral port.
Parameters
err_code See flow::Error_code docs for error reporting semantics. error::Code generated: error::Code::S_OUT_OF_PORTS.
Returns
On success, the reserved port; on failure, S_PORT_ANY.
Definition at line 112 of file port_space.cpp.
References find_available_port_bit_idx(), FLOW_ERROR_EMIT_ERROR, FLOW_LOG_INFO, FLOW_LOG_TRACE, m_ephemeral_and_recent_ephemeral_ports, m_ephemeral_ports, m_recent_ephemeral_ports, S_FIRST_EPHEMERAL_PORT, S_NUM_EPHEMERAL_PORTS, flow::net_flow::error::S_OUT_OF_PORTS, and flow::net_flow::S_PORT_ANY.
Referenced by reserve_port().
reserve_port()
flow_port_t flow::net_flow::Port_space::reserve_port (flow_port_t port, Error_code * err_code)
Reserve the specified service port, or reserve_ephemeral_port() if the specified port is S_PORT_ANY.
Parameters
port A valid and still available service port number, or S_PORT_ANY.
err_code See flow::Error_code docs for error reporting semantics. error::Code generated: error::Code::S_INVALID_SERVICE_PORT_NUMBER, error::Code::S_PORT_TAKEN, or whatever set by reserve_ephemeral_port() if port == S_PORT_ANY.
Returns
On success, the reserved port; on failure, S_PORT_ANY.
Definition at line 75 of file port_space.cpp.
References FLOW_ERROR_EMIT_ERROR, FLOW_LOG_INFO, FLOW_LOG_TRACE, is_service_port(), m_service_ports, reserve_ephemeral_port(), S_FIRST_SERVICE_PORT, flow::net_flow::error::S_INVALID_SERVICE_PORT_NUMBER, flow::net_flow::S_PORT_ANY, and flow::net_flow::error::S_PORT_TAKEN.
Referenced by flow::net_flow::Node::listen_worker().
return_port()
void flow::net_flow::Port_space::return_port (flow_port_t port, Error_code * err_code)
Return a previously reserved port (of any type).
Parameters
port A previously reserved port.
err_code See flow::Error_code docs for error reporting semantics. error::Code generated: error::Code::S_PORT_TAKEN.
Definition at line 175 of file port_space.cpp.
References FLOW_ERROR_EMIT_ERROR, FLOW_LOG_INFO, FLOW_LOG_TRACE, flow::util::in_closed_open_range(), is_service_port(), m_ephemeral_and_recent_ephemeral_ports, m_ephemeral_ports, m_recent_ephemeral_ports, m_service_ports, S_FIRST_EPHEMERAL_PORT, S_FIRST_SERVICE_PORT, flow::net_flow::error::S_INTERNAL_ERROR_PORT_NOT_TAKEN, S_MAX_RECENT_EPHEMERAL_PORTS, and S_NUM_EPHEMERAL_PORTS.
Referenced by flow::net_flow::Node::close_connection_immediately(), flow::net_flow::Node::close_empty_server_immediately(), and flow::net_flow::Node::listen_worker().
Member Data Documentation
m_ephemeral_and_recent_ephemeral_ports
Bit_set flow::net_flow::Port_space::m_ephemeral_and_recent_ephemeral_ports private
Set representing the union of the set of current reserved ephemeral ports and the set of the last up-to-S_MAX_RECENT_EPHEMERAL_PORTS returned and available ephemeral ports.
In other words, the union of the ports represented by m_ephemeral_ports and m_recent_ephemeral_ports. In yet other words, a 1 bit represents an available and not-recently-used port. This is kept for performance, so that when choosing a random port one can find a random 1 bit to find a not-recently-used and open port.
Invariants:
Port P is in m_recent_ephemeral_ports => bit (P - S_FIRST_EPHEMERAL_PORT) is 0 in this.
Bit N is 0 in m_ephemeral_ports => bit N is 0 in this.
All other bits are 1.
Definition at line 234 of file port_space.hpp.
Referenced by Port_space(), reserve_ephemeral_port(), and return_port().
m_ephemeral_ports
Bit_set flow::net_flow::Port_space::m_ephemeral_ports private
Current ephemeral port set; indexing analogous to m_service_ports but starting at S_FIRST_EPHEMERAL_PORT.
Definition at line 219 of file port_space.hpp.
Referenced by Port_space(), reserve_ephemeral_port(), and return_port().
m_recent_ephemeral_ports
std::queue<flow_port_t> flow::net_flow::Port_space::m_recent_ephemeral_ports private
A FIFO of recently used but currently available ephemeral ports.
Algorithm: push port onto back of queue when it's returned; pop front of queue if m_recent_ephemeral_ports is beyond S_MAX_RECENT_EPHEMERAL_PORTS long. If port is needed and no more non-m_ephemeral_and_recent_ephemeral_ports ports are available, pop front of queue (i.e., oldest recently used port) and use that. If emptied, there are simply no more ports left.
Definition at line 243 of file port_space.hpp.
Referenced by reserve_ephemeral_port(), and return_port().
m_rnd_generator
Random_generator flow::net_flow::Port_space::m_rnd_generator private
Random number generator for picking ports.
Definition at line 246 of file port_space.hpp.
Referenced by find_available_port_bit_idx().
m_service_ports
Bit_set flow::net_flow::Port_space::m_service_ports private
Current service port set.
Bit 0 is port S_FIRST_SERVICE_PORT, bit 1 is S_FIRST_SERVICE_PORT + 1, etc. In particular, this starts off as all 1s (all ports open).
Definition at line 213 of file port_space.hpp.
Referenced by Port_space(), reserve_port(), and return_port().
S_FIRST_EPHEMERAL_PORT
const flow_port_t flow::net_flow::Port_space::S_FIRST_EPHEMERAL_PORT = S_FIRST_SERVICE_PORT + S_NUM_SERVICE_PORTS static
The port number of the lowest ephemeral port.
Definition at line 111 of file port_space.hpp.
Referenced by Port_space(), reserve_ephemeral_port(), and return_port().
S_FIRST_SERVICE_PORT
const flow_port_t flow::net_flow::Port_space::S_FIRST_SERVICE_PORT = 1 static
The port number of the lowest service port.
Definition at line 108 of file port_space.hpp.
Referenced by is_service_port(), flow::net_flow::error::Category::message(), Port_space(), reserve_port(), and return_port().
S_MAX_RECENT_EPHEMERAL_PORTS
const size_t flow::net_flow::Port_space::S_MAX_RECENT_EPHEMERAL_PORTS = S_NUM_EPHEMERAL_PORTS / 32 static private
The maximum size of m_recent_ephemeral_ports.
Definition at line 205 of file port_space.hpp.
Referenced by return_port().
S_NUM_EPHEMERAL_PORTS
const size_t flow::net_flow::Port_space::S_NUM_EPHEMERAL_PORTS = S_NUM_PORTS - S_NUM_SERVICE_PORTS - 1 static
Total number of "ephemeral" ports (ones reserved at random with reserve_ephemeral_port()).
Definition at line 105 of file port_space.hpp.
Referenced by Port_space(), reserve_ephemeral_port(), and return_port().
S_NUM_PORTS
const size_t flow::net_flow::Port_space::S_NUM_PORTS = size_t(std::numeric_limits<flow_port_t>::max()) + 1 static
Total number of ports in the port space, including S_PORT_ANY.
Definition at line 99 of file port_space.hpp.
S_NUM_SERVICE_PORTS
const size_t flow::net_flow::Port_space::S_NUM_SERVICE_PORTS = S_NUM_PORTS / 2 - 1 static
Total number of "service" ports (ones that can be reserved by number with reserve_port()).
Definition at line 102 of file port_space.hpp.
Referenced by is_service_port(), flow::net_flow::error::Category::message(), and Port_space().
The documentation for this class was generated from the following files:
net_flow/detail/port_space.hpp
net_flow/detail/port_space.cpp