Flow: flow::net_flow::Peer_socket_receive_stats_accumulator Class Reference
flow::net_flow::Peer_socket_receive_stats_accumulator Class Reference
A class that keeps a Peer_socket_receive_stats data store, includes methods to conveniently accumulate data in it, and provides output to ostream.
#include <socket_stats.hpp>
Public Member Functions
const Peer_socket_receive_stats & stats () const
Returns reference to non-modifiable current set of accumulated stats.
void total_data_packet (size_t data)
Indicates one DATA packet has been received on socket.
void good_data_packet (size_t data)
Indicates total_data_packet(), and these data are new and acceptable into Receive buffer assuming there is space.
void good_data_dropped_buf_overflow_packet (size_t data)
Indicates good_data_packet(), but these data are dropped due to insufficient Receive buffer space.
void good_data_dropped_reassembly_q_overflow_packet (size_t data)
Indicates good_data_packet(), but these data are dropped due to insufficient Receive reassembly queue space (only possible when retransmission is enabled).
void good_data_accepted_packet (size_t data)
Indicates good_data_packet(), and these data are not dropped (so either delivered into Receive buffer or queued for reassembly later).
void good_data_delivered_packet (size_t data)
Indicates good_data_accepted_packet(), and these data are delivered into Receive buffer (either immediately upon receipt or upon later reassembly).
void good_data_first_qd_packet (size_t data)
Indicates good_data_accepted_packet(), and these data are, upon receipt, queued for reassembly (not immediately delivered into Receive buffer).
void late_or_dupe_data_packet (size_t data)
Indicates total_data_packet(), but the arrived data have either already been received before or (more likely) have been considered Dropped by now; therefore data not delivered to Receive buffer.
void error_data_packet (size_t data)
Indicates total_data_packet(), but there is some error about the sequence numbers so that they are not acceptable, and the connection did/will close as a result.
void presumed_dropped_data (size_t data)
Indicates that one or more unreceived data packets have been considered Dropped due to the number of later packets that have been received.
void total_to_send_ack_packet (size_t data)
Indicates that an individual acknowledgment for one packet will be sent.
void good_to_send_ack_packet (size_t data)
Indicates that good_data_delivered_packet() and therefore an individual acknowledgment for this packet will be sent.
void late_or_dupe_to_send_ack_packet (size_t data)
Indicates that late_or_dupe_data_packet() and therefore an individual acknowledgment for this packet will be sent.
void current_pending_to_ack_packets (size_t count)
Indicates that all incoming data in the current boost.asio handler have been scanned and any ACKs that may be sent in this handler have been sent, and that immediately after that fact, the number of individual acknowledgments (NOTE: not ACK packets but individual acknowledgments therein) is as given in the count argument.
void sent_individual_ack ()
Indicates than one individual acknowledgment of a data packet has been packaged into an ACK packet that will be sent as soon as possible.
void sent_low_lvl_ack_packet (bool rcv_wnd_update_only)
Indicates than one low-level ACK packet will be sent as soon as possible.
void rcv_wnd_recovery_event_start ()
Indicates we seem to have detected that our rcv_wnd went from exhaustion to largely free, and therefore we will now inform the sender of this, so that it can resume sending data.
void rcv_wnd_recovery_event_finish (bool success)
Indicates that the recovery indicated by last rcv_wnd_recovery_event_start() call has finished (we are no longer ACKing sender to advertise receive window).
void buffer_fed (size_t size)
Indicates the Receive buffer was enqueued with data from network (so its data_size() increased).
void low_lvl_packet (const std::type_info &type, size_t size)
Indicates a Low_lvl_packet& p was received with typeid(p) == type, deserialized from a buffer of length size bytes, targeted at the associated socket.
Additional Inherited Members
Private Member Functions inherited from flow::net_flow::Peer_socket_receive_stats
Peer_socket_receive_stats ()
Constructs object by initializing stats to their initial values.
void output (std::ostream *os) const
Outputs the current stats, across multiple lines but not ending with a newline, into the given output stream.
Private Attributes inherited from flow::net_flow::Peer_socket_receive_stats
Fine_time_pt m_init_time
The time this object (or source object from assignment) was made; should be about equal to when socket was made.
uint64_t m_total_data_size
Bytes in DATA packets received on socket.
uint64_t m_total_data_count
Number of DATA packets received on socket.
uint64_t m_good_data_size
Of m_total_data_size, the data that were new and acceptable into Receive buffer assuming there was space.
uint64_t m_good_data_count
Of m_total_data_count, the data that were new and acceptable into Receive buffer assuming there was space.
uint64_t m_good_data_accepted_size
Of m_good_data_size, the data that were not dropped (so either delivered into Receive buffer or queued for reassembly later).
uint64_t m_good_data_accepted_count
Of m_good_data_count, the data that were not dropped (so either delivered into Receive buffer or queued for reassembly later).
uint64_t m_good_data_delivered_size
Of m_good_data_accepted_size, the data that were delivered into Receive buffer (either immediately upon receipt or upon later reassembly).
uint64_t m_good_data_delivered_count
Of m_good_data_accepted_count, the data that were delivered into Receive buffer (either immediately upon receipt or upon later reassembly).
uint64_t m_good_data_first_qd_size
Of m_good_data_accepted_size, the data that were, upon receipt, queued for reassembly (not immediately delivered into Receive buffer).
uint64_t m_good_data_first_qd_count
Of m_good_data_accepted_count, the data that were, upon receipt, queued for reassembly (not immediately delivered into Receive buffer).
uint64_t m_good_data_dropped_buf_overflow_size
Of m_good_data_size, the data that were dropped due to insufficient Receive buffer space.
uint64_t m_good_data_dropped_buf_overflow_count
Of m_good_data_count, the data that were dropped due to insufficient Receive buffer space.
uint64_t m_good_data_dropped_reassembly_q_overflow_size
Of m_good_data_size, the data that were dropped due to insufficient Receive reassembly queue space (only possible when retransmission is enabled).
uint64_t m_good_data_dropped_reassembly_q_overflow_count
Of m_good_data_count, the data that were dropped due to insufficient Receive reassembly queue space (only possible when retransmission is enabled).
uint64_t m_error_data_size
Of m_total_data_size, the data that contained some error about the sequence numbers so that they were not acceptable, and the connection did/will close as a result.
uint64_t m_error_data_count
Of m_total_data_count, the data that contained some error about the sequence numbers so that they were not acceptable, and the connection did/will close as a result.
uint64_t m_late_or_dupe_data_size
Of m_total_data_size, the data that had either already been received before or (more likely) had been considered Dropped by now; therefore these data not delivered to Receive buffer.
uint64_t m_late_or_dupe_data_count
Of m_total_data_count, the data that had either already been received before or (more likely) had been considered Dropped by now; therefore these data not delivered to Receive buffer.
uint64_t m_presumed_dropped_data_size
Total number of bytes in hypothetical data packets that have been considered Dropped due to the number of later packets that have been received.
uint64_t m_total_to_send_acks_data_size
Bytes in received DATA packets acknowledged thus far or that have been received and are pending to be acknowledged.
uint64_t m_total_to_send_acks_count
Number of DATA packets acknowledged thus far or that have been received and are pending to be acknowledged.
uint64_t m_good_to_send_acks_data_size
Of m_total_to_send_acks_data_size, the data that also satisfy the criteria in m_good_data_delivered_size.
uint64_t m_good_to_send_acks_count
Of m_total_to_send_acks_count, the data that also satisfy the criteria in m_good_data_delivered_count.
uint64_t m_late_or_dupe_to_send_acks_data_size
Of m_total_to_send_acks_data_size, the data that also satisfy the criteria in m_late_or_dupe_data_size.
uint64_t m_late_or_dupe_to_send_acks_count
Of m_total_to_send_acks_count, the data that also satisfy the criteria in m_late_or_dupe_data_count.
size_t m_current_pending_acks_count
Of m_total_to_send_acks_count, the packets that have not yet been sent to the sender (pending acknowledgments).
uint64_t m_delayed_acks_count
The total number of individual packet acknowledgments whose sending was delayed (via delayed ACK mechanism) beyond the handler in which they were originally constructed.
uint64_t m_sent_individual_acks_count
Number of DATA packets such that for a given packet an individual acknowledgment has been packaged into an ACK packet that has been sent or will be sent as soon as possible.
uint64_t m_sent_low_lvl_acks_count
Number of low-level ACK packets that have been sent or will be sent as soon as possible.
uint64_t m_rcv_wnd_recovery_count
Number of times we detected (heuristically but fairly reliably) that the following event occurred: our rcv_wnd (or free Receive buffer space) was exhausted; but then significatly freed by application-layer receive() calls.
uint64_t m_rcv_wnd_recovery_success_count
Of m_rcv_wnd_recovery_count, the number of times the recovery was successful: i.e., resulted in more data packets arriving from sender.
uint64_t m_rcv_wnd_recovery_timeout_count
Of m_rcv_wnd_recovery_count, the number of times the recovery failed: i.e., resulted in a certain lengthy timeout firing before any more data packets arrived from sender.
uint64_t m_sent_low_lvl_rcv_wnd_only_acks_count
Of m_sent_low_lvl_acks_count, the packets that contained no individual acknowledgments but are to be sent only to advertise rcv_wnd.
size_t m_max_buf_data_size
Maximum number of bytes in the Receive buffer so far.
std::map< std::type_index, uint64_t > m_low_lvl_packet_size_by_type
Total size in serialized form of low-level packets received targeted at this socket, split up by polymorphic sub-type ID type_index(typeid(p)), where p is a reference to an instance of a sub-type of Low_lvl_packet (or, in English, by packet type).
std::map< std::type_index, uint64_t > m_low_lvl_packet_count_by_type
Count of low-level packets received targeted at this socket, split up by packet type similarly to m_low_lvl_packet_size_by_type.
Related Functions inherited from flow::net_flow::Peer_socket_receive_stats
std::ostream & operator<< (std::ostream &os, const Peer_socket_receive_stats &stats)
Prints string representation of the stats in the given stats object to the standard ostream and returns the latter.
Detailed Description
A class that keeps a Peer_socket_receive_stats data store, includes methods to conveniently accumulate data in it, and provides output to ostream.
Any object of this class is intended to have a 1-to-1 relationship with a Peer_socket. The interface is intentionally simple; the class keeps some counters and limited auxilliary state (such as creation time); the Node informs the class of events (like "DATA packet received"), counts of which are stored in the class and are accessible through the interface (at least through the ostream output operator).
As usual, invoke the event handler methods of the class whenever the appropriate events occur. Failing to do so will obviously result in wrong statistics.
The class intentionally does not take a reference to a Peer_socket and avoids logging; it is a simple accumulating data store.
Thread safety
Same as any struct with no locking done therein.
See also
Peer_socket_receive_stats
Definition at line 49 of file socket_stats.hpp.
Member Function Documentation
buffer_fed()
void flow::net_flow::Peer_socket_receive_stats_accumulator::buffer_fed (size_t size)
Indicates the Receive buffer was enqueued with data from network (so its data_size() increased).
Parameters
size The # of bytes in the buffer after the enqueueing.
Definition at line 148 of file socket_stats.cpp.
References flow::net_flow::Peer_socket_receive_stats::m_max_buf_data_size.
Referenced by flow::net_flow::Node::sock_data_to_rcv_buf_unless_overflow(), and flow::net_flow::Node::sock_slide_rcv_next_seq_num().
current_pending_to_ack_packets()
void flow::net_flow::Peer_socket_receive_stats_accumulator::current_pending_to_ack_packets (size_t count)
Indicates that all incoming data in the current boost.asio handler have been scanned and any ACKs that may be sent in this handler have been sent, and that immediately after that fact, the number of individual acknowledgments (NOTE: not ACK packets but individual acknowledgments therein) is as given in the count argument.
Note that unlike most methods in this class, this indicates the current state as opposed to an event. Internally this is necessary to maintain a total count of individual acks that have ever been delayed (without double-counting).
The current mechanism is that, in a given boost.asio low-level receive handler, we will either flush all the acks that have built up over the last N (where N >= 1, including the current one) handlers, or we will queue up 0 or more to send in a later handler. (We do not add some more + flush some but not all, nor do we just flush some but not all.) Thus, in the 2 cases just described, we'd call this method with count = 0 or some value >= the value from the last time, respectively.
Parameters
count Number of packets. This should be either zero or >= the last value passed into the same call for this object. Otherwise assertion trips.
Definition at line 104 of file socket_stats.cpp.
References flow::net_flow::Peer_socket_receive_stats::m_current_pending_acks_count, and flow::net_flow::Peer_socket_receive_stats::m_delayed_acks_count.
error_data_packet()
void flow::net_flow::Peer_socket_receive_stats_accumulator::error_data_packet (size_t data)
Indicates total_data_packet(), but there is some error about the sequence numbers so that they are not acceptable, and the connection did/will close as a result.
Parameters
data User data size.
Definition at line 69 of file socket_stats.cpp.
References flow::net_flow::Peer_socket_receive_stats::m_error_data_count, and flow::net_flow::Peer_socket_receive_stats::m_error_data_size.
Referenced by flow::net_flow::Node::handle_data_to_established(), and flow::net_flow::Node::sock_categorize_data_to_established().
good_data_accepted_packet()
void flow::net_flow::Peer_socket_receive_stats_accumulator::good_data_accepted_packet (size_t data)
Indicates good_data_packet(), and these data are not dropped (so either delivered into Receive buffer or queued for reassembly later).
Parameters
data User data size.
Definition at line 51 of file socket_stats.cpp.
References flow::net_flow::Peer_socket_receive_stats::m_good_data_accepted_count, and flow::net_flow::Peer_socket_receive_stats::m_good_data_accepted_size.
Referenced by flow::net_flow::Node::sock_data_to_rcv_buf_unless_overflow(), and flow::net_flow::Node::sock_data_to_reassembly_q_unless_overflow().
good_data_delivered_packet()
void flow::net_flow::Peer_socket_receive_stats_accumulator::good_data_delivered_packet (size_t data)
Indicates good_data_accepted_packet(), and these data are delivered into Receive buffer (either immediately upon receipt or upon later reassembly).
Parameters
data User data size.
Definition at line 57 of file socket_stats.cpp.
References flow::net_flow::Peer_socket_receive_stats::m_good_data_delivered_count, and flow::net_flow::Peer_socket_receive_stats::m_good_data_delivered_size.
Referenced by flow::net_flow::Node::sock_data_to_rcv_buf_unless_overflow(), and flow::net_flow::Node::sock_slide_rcv_next_seq_num().
good_data_dropped_buf_overflow_packet()
void flow::net_flow::Peer_socket_receive_stats_accumulator::good_data_dropped_buf_overflow_packet (size_t data)
Indicates good_data_packet(), but these data are dropped due to insufficient Receive buffer space.
Parameters
data User data size.
Definition at line 39 of file socket_stats.cpp.
References flow::net_flow::Peer_socket_receive_stats::m_good_data_dropped_buf_overflow_count, and flow::net_flow::Peer_socket_receive_stats::m_good_data_dropped_buf_overflow_size.
Referenced by flow::net_flow::Node::sock_data_to_rcv_buf_unless_overflow().
good_data_dropped_reassembly_q_overflow_packet()
void flow::net_flow::Peer_socket_receive_stats_accumulator::good_data_dropped_reassembly_q_overflow_packet (size_t data)
Indicates good_data_packet(), but these data are dropped due to insufficient Receive reassembly queue space (only possible when retransmission is enabled).
Parameters
data User data size.
Definition at line 45 of file socket_stats.cpp.
References flow::net_flow::Peer_socket_receive_stats::m_good_data_dropped_reassembly_q_overflow_count, and flow::net_flow::Peer_socket_receive_stats::m_good_data_dropped_reassembly_q_overflow_size.
Referenced by flow::net_flow::Node::sock_data_to_reassembly_q_unless_overflow().
good_data_first_qd_packet()
void flow::net_flow::Peer_socket_receive_stats_accumulator::good_data_first_qd_packet (size_t data)
Indicates good_data_accepted_packet(), and these data are, upon receipt, queued for reassembly (not immediately delivered into Receive buffer).
Parameters
data User data size.
Definition at line 63 of file socket_stats.cpp.
References flow::net_flow::Peer_socket_receive_stats::m_good_data_first_qd_count, and flow::net_flow::Peer_socket_receive_stats::m_good_data_first_qd_size.
Referenced by flow::net_flow::Node::sock_data_to_reassembly_q_unless_overflow().
good_data_packet()
void flow::net_flow::Peer_socket_receive_stats_accumulator::good_data_packet (size_t data)
Indicates total_data_packet(), and these data are new and acceptable into Receive buffer assuming there is space.
Parameters
data User data size.
Definition at line 33 of file socket_stats.cpp.
References flow::net_flow::Peer_socket_receive_stats::m_good_data_count, and flow::net_flow::Peer_socket_receive_stats::m_good_data_size.
Referenced by flow::net_flow::Node::handle_data_to_established().
good_to_send_ack_packet()
void flow::net_flow::Peer_socket_receive_stats_accumulator::good_to_send_ack_packet (size_t data)
Indicates that good_data_delivered_packet() and therefore an individual acknowledgment for this packet will be sent.
Note that good_data_packet() alone does not necessarily mean that an acknowledgment will be sent in response (namely if we have to drop the packet due to insufficient buffer space).
Parameters
data User data size.
Definition at line 92 of file socket_stats.cpp.
References flow::net_flow::Peer_socket_receive_stats::m_good_to_send_acks_count, and flow::net_flow::Peer_socket_receive_stats::m_good_to_send_acks_data_size.
Referenced by flow::net_flow::Node::handle_data_to_established().
late_or_dupe_data_packet()
void flow::net_flow::Peer_socket_receive_stats_accumulator::late_or_dupe_data_packet (size_t data)
Indicates total_data_packet(), but the arrived data have either already been received before or (more likely) have been considered Dropped by now; therefore data not delivered to Receive buffer.
Parameters
data User data size.
Definition at line 75 of file socket_stats.cpp.
References flow::net_flow::Peer_socket_receive_stats::m_late_or_dupe_data_count, and flow::net_flow::Peer_socket_receive_stats::m_late_or_dupe_data_size.
Referenced by flow::net_flow::Node::handle_data_to_established().
late_or_dupe_to_send_ack_packet()
void flow::net_flow::Peer_socket_receive_stats_accumulator::late_or_dupe_to_send_ack_packet (size_t data)
Indicates that late_or_dupe_data_packet() and therefore an individual acknowledgment for this packet will be sent.
Parameters
data User data size.
Definition at line 98 of file socket_stats.cpp.
References flow::net_flow::Peer_socket_receive_stats::m_late_or_dupe_to_send_acks_count, and flow::net_flow::Peer_socket_receive_stats::m_late_or_dupe_to_send_acks_data_size.
Referenced by flow::net_flow::Node::handle_data_to_established().
low_lvl_packet()
void flow::net_flow::Peer_socket_receive_stats_accumulator::low_lvl_packet (const std::type_info & type, size_t size)
Indicates a Low_lvl_packet& p was received with typeid(p) == type, deserialized from a buffer of length size bytes, targeted at the associated socket.
Caveat: Some packets may not be targeted at any particular socket; probably malformed. They would not be counted here.
Caveat: SYN counts; but note that the Peer_socket with which this call is associated would need to first be created before making the call.
Parameters
type typeid(p), where p refers to an instance of a concrete Low_lvl_packet sub-type.
size Datagram contents' size.
Definition at line 153 of file socket_stats.cpp.
References flow::net_flow::Peer_socket_receive_stats::m_low_lvl_packet_count_by_type, and flow::net_flow::Peer_socket_receive_stats::m_low_lvl_packet_size_by_type.
presumed_dropped_data()
void flow::net_flow::Peer_socket_receive_stats_accumulator::presumed_dropped_data (size_t data)
Indicates that one or more unreceived data packets have been considered Dropped due to the number of later packets that have been received.
For each such packet that does arrive in the future (though unlikely), late_or_dupe_data_packet() will be called.
Parameters
data User data size.
Definition at line 81 of file socket_stats.cpp.
References flow::net_flow::Peer_socket_receive_stats::m_presumed_dropped_data_size.
Referenced by flow::net_flow::Node::sock_track_new_data_after_gap_rexmit_off().
rcv_wnd_recovery_event_finish()
void flow::net_flow::Peer_socket_receive_stats_accumulator::rcv_wnd_recovery_event_finish (bool success)
Indicates that the recovery indicated by last rcv_wnd_recovery_event_start() call has finished (we are no longer ACKing sender to advertise receive window).
Parameters
success true if recovery successful (sender has sent more DATA packets); false if recovery failed (we stopped due to exceeding long timeout).
Definition at line 143 of file socket_stats.cpp.
References flow::net_flow::Peer_socket_receive_stats::m_rcv_wnd_recovery_success_count, and flow::net_flow::Peer_socket_receive_stats::m_rcv_wnd_recovery_timeout_count.
rcv_wnd_recovery_event_start()
void flow::net_flow::Peer_socket_receive_stats_accumulator::rcv_wnd_recovery_event_start ()
Indicates we seem to have detected that our rcv_wnd went from exhaustion to largely free, and therefore we will now inform the sender of this, so that it can resume sending data.
Definition at line 138 of file socket_stats.cpp.
References flow::net_flow::Peer_socket_receive_stats::m_rcv_wnd_recovery_count.
sent_individual_ack()
void flow::net_flow::Peer_socket_receive_stats_accumulator::sent_individual_ack ()
Indicates than one individual acknowledgment of a data packet has been packaged into an ACK packet that will be sent as soon as possible.
Definition at line 124 of file socket_stats.cpp.
References flow::net_flow::Peer_socket_receive_stats::m_sent_individual_acks_count.
sent_low_lvl_ack_packet()
void flow::net_flow::Peer_socket_receive_stats_accumulator::sent_low_lvl_ack_packet (bool rcv_wnd_update_only)
Indicates than one low-level ACK packet will be sent as soon as possible.
Parameters
rcv_wnd_update_only true if and only if this ACK contains no individual acknowledgments; i.e., it is sent only with the purpose of advertising rcv_wnd.
Definition at line 129 of file socket_stats.cpp.
References flow::net_flow::Peer_socket_receive_stats::m_sent_low_lvl_acks_count, and flow::net_flow::Peer_socket_receive_stats::m_sent_low_lvl_rcv_wnd_only_acks_count.
stats()
const Peer_socket_receive_stats & flow::net_flow::Peer_socket_receive_stats_accumulator::stats () const
Returns reference to non-modifiable current set of accumulated stats.
Returns
Ditto.
Definition at line 161 of file socket_stats.cpp.
total_data_packet()
void flow::net_flow::Peer_socket_receive_stats_accumulator::total_data_packet (size_t data)
Indicates one DATA packet has been received on socket.
Parameters
data User data size.
Definition at line 27 of file socket_stats.cpp.
References flow::net_flow::Peer_socket_receive_stats::m_total_data_count, and flow::net_flow::Peer_socket_receive_stats::m_total_data_size.
Referenced by flow::net_flow::Node::handle_data_to_established().
total_to_send_ack_packet()
void flow::net_flow::Peer_socket_receive_stats_accumulator::total_to_send_ack_packet (size_t data)
Indicates that an individual acknowledgment for one packet will be sent.
Parameters
data User data size.
Definition at line 86 of file socket_stats.cpp.
References flow::net_flow::Peer_socket_receive_stats::m_total_to_send_acks_count, and flow::net_flow::Peer_socket_receive_stats::m_total_to_send_acks_data_size.
The documentation for this class was generated from the following files:
net_flow/detail/stats/socket_stats.hpp
net_flow/detail/stats/socket_stats.cpp