Flow: flow::async::Segregated_thread_task_loop Class Reference
flow::async::Segregated_thread_task_loop Class Reference
Concrete Concurrent_task_loop that uses the legacy pin-Tasks-within-1-Op-to-1-thread method of achieving required non-concurrency of Tasks.
#include <segregated_thread_task_loop.hpp>
Public Member Functions
Segregated_thread_task_loop (log::Logger *logger_ptr, util::String_view nickname, size_t n_threads_or_zero, bool est_hw_core_sharing_helps_algo=false, bool est_hw_core_pinning_helps_algo=false, bool hw_threads_is_grouping_collated=false)
Constructs object, making it available for post() and similar work, but without starting any threads and hence without the ability to perform any work; call start() to spawn threads and perform work.
~Segregated_thread_task_loop () override
See superclass destructor.
void start (Task &&init_task_or_empty=Task(), const Thread_init_func &thread_init_func_or_empty=Thread_init_func()) override
Implements superclass API.
void stop () override
Implements superclass API.
size_t n_threads () const override
Implements superclass API.
Op create_op () override
Implements superclass API.
const Op_list & per_thread_ops () override
Implements superclass API.
void post (Task &&task, Synchronicity synchronicity=Synchronicity::S_ASYNC) override
Implements superclass API.
void post (const Op &op, Task &&task, Synchronicity synchronicity=Synchronicity::S_ASYNC) override
Implements superclass API.
util::Scheduled_task_handle schedule_from_now (const Fine_duration &from_now, Scheduled_task &&task) override
Implements superclass API.
util::Scheduled_task_handle schedule_at (const Fine_time_pt &at, Scheduled_task &&task) override
Implements superclass API.
util::Scheduled_task_handle schedule_from_now (const Op &op, const Fine_duration &from_now, Scheduled_task &&task) override
Implements superclass API.
util::Scheduled_task_handle schedule_at (const Op &op, const Fine_time_pt &at, Scheduled_task &&task) override
See superclass API.
Task_engine_ptr task_engine () override
See superclass API.
Public Member Functions inherited from flow::async::Concurrent_task_loop
~Concurrent_task_loop () override
Any implementing subclass's destructor shall execute stop() – see its doc header please – and then clean up any resources.
virtual void start (Task &&init_task_or_empty=Task(), const Thread_init_func &thread_init_func_or_empty=Thread_init_func())=0
Starts all threads in the thread pool; any queued post()ed (and similar) tasks may begin executing immediately; and any future posted work may execute in these threads.
virtual void stop ()=0
Waits for any ongoing task(s)/completion handler(s) to return; then prevents any further-queued such tasks from running; then gracefully stops/joins all threads in pool; and then returns.
virtual size_t n_threads () const =0
How many threads does start() start?
virtual Op create_op ()=0
Return a new Op which can bundle together an arbitrary set of post()s that would result in the provided task functions executing non-concurrently.
virtual const Op_list & per_thread_ops ()=0
Returns the optional-use, pre-created collection of per-thread async::Op objects, such that the i-th Op therein corresponds to the i-th (of N, where N = # of threads in this pool) thread.
virtual void post (Task &&task, Synchronicity synchronicity=Synchronicity::S_ASYNC)=0
Cause the given Task (function) to execute within the thread pool as soon as possible, in the first thread available, in otherwise first-come-first-served fashion.
virtual void post (const Op &op, Task &&task, Synchronicity synchronicity=Synchronicity::S_ASYNC)=0
Identical to the other post() with the added constraint that no other Task also similarly posted with the equivalent async::Op may execute concurrently.
virtual util::Scheduled_task_handle schedule_from_now (const Fine_duration &from_now, Scheduled_task &&task)=0
Equivalent to 2-argument post() but execution is scheduled for later, after the given time period passes.
virtual util::Scheduled_task_handle schedule_at (const Fine_time_pt &at, Scheduled_task &&task)=0
Equivalent to 2-argument schedule_from_now() except one specifies an absolute time point instead of wait duration.
virtual util::Scheduled_task_handle schedule_from_now (const Op &op, const Fine_duration &from_now, Scheduled_task &&task)=0
Equivalent to 3-argument post() but execution is scheduled for later, after the given time period passes.
virtual util::Scheduled_task_handle schedule_at (const Op &op, const Fine_time_pt &at, Scheduled_task &&task)=0
Equivalent to 3-argument schedule_from_now() except one specifies an absolute time point instead of wait duration.
virtual Task_engine_ptr task_engine ()=0
Returns a pointer to an internal util::Task_engine (a/k/a boost.asio io_service) for the purpose of performing a boost.asio async_*() action on some boost.asio I/O object in the immediate near future.
Public Member Functions inherited from flow::util::Null_interface
virtual ~Null_interface ()=0
Boring virtual destructor.
Public Member Functions inherited from flow::log::Log_context
Log_context (Logger *logger=0)
Constructs Log_context by storing the given pointer to a Logger and a null Component.
template<typename Component_payload >
Log_context (Logger *logger, Component_payload component_payload)
Constructs Log_context by storing the given pointer to a Logger and a new Component storing the specified generically typed payload (an enum value).
Log_context (const Log_context &src)
Copy constructor that stores equal Logger* and Component values as the source.
Log_context (Log_context &&src)
Move constructor that makes this equal to src, while the latter becomes as-if default-constructed.
Log_context & operator= (const Log_context &src)
Assignment operator that behaves similarly to the copy constructor.
Log_context & operator= (Log_context &&src)
Move assignment operator that behaves similarly to the move constructor.
void swap (Log_context &other)
Swaps Logger pointers and Component objects held by *this and other.
Logger * get_logger () const
Returns the stored Logger pointer, particularly as many FLOW_LOG_*() macros expect.
const Component & get_log_component () const
Returns reference to the stored Component object, particularly as many FLOW_LOG_*() macros expect.
Private Types
using Task_qing_thread_ptr = boost::movelib::unique_ptr< Task_qing_thread >
Short-hand for smart pointer to Task_qing_thread.
Private Member Functions
void post_impl (const Task_engine_ptr &chosen_task_engine, Synchronicity synchronicity, Task &&task)
Helper performing the core Task_engine::post() (or similar) call on behalf of the various post() overloads.
util::Scheduled_task_handle schedule_from_now_impl (const Task_engine_ptr &chosen_task_engine, const Fine_duration &from_now, Scheduled_task &&task)
Helper performing the core util::schedule_task_from_now() call on behalf of the various schedule_from_now() overloads.
Private Attributes
const std::string m_nickname
See constructor.
const size_t m_n_threads_or_zero
See constructor.
const bool m_est_hw_core_sharing_helps_algo
See constructor.
const bool m_est_hw_core_pinning_helps_algo
See constructor.
const bool m_hw_threads_is_grouping_collated
See constructor.
std::vector< Task_qing_thread_ptr > m_qing_threads
N task-execution-capable worker threads whose lifetimes equal those of *this, each with its own util::Task_engine.
std::vector< Task_engine_ptr > m_task_engines
boost.asio Task_engines (a/k/a io_services) used by each respective element in m_qing_threads.
boost::movelib::unique_ptr< const Op_list > m_per_thread_ops
See per_thread_ops().
Related Functions
(Note that these are not member functions.)
template<>
Task_engine_ptr op_to_exec_ctx (Concurrent_task_loop *loop, const Op &op)
Template specialization for operation that obtains the underlying execution context, in this case a util::Task_engine, stored in an async::Op generated by the given Segregated_thread_task_loop.
Related Functions inherited from flow::async::Concurrent_task_loop
template<typename Exec_ctx_ptr >
Exec_ctx_ptr op_to_exec_ctx (Concurrent_task_loop *loop, const Op &op)
Template specialization model for operation that obtains the underlying execution context, such as a util::Task_engine or util::Strand, stored in an async::Op generated by the given Concurrent_task_loop.
Additional Inherited Members
Public Types inherited from flow::async::Concurrent_task_loop
using Thread_init_func = Function< void(size_t thread_idx)>
Short-hand for the thread-initializer-function optional arg type to start().
Detailed Description
Concrete Concurrent_task_loop that uses the legacy pin-Tasks-within-1-Op-to-1-thread method of achieving required non-concurrency of Tasks.
See also
Concurrent_task_loop doc header for an overview of this class in the context of sibling classes (alternatives).
By definition all you need to know to use it is in the super-interface Concurrent_task_loop doc header (except constructor semantics of course). However, in choosing this vs. a sibling type, one must at least loosely understand its underlying behavior. To summarize the behavior of this class beyond the interface guarantees:
A no-Op stand-alone Task executes as soon as thread T becomes available, and T is randomly chosen.
An Op-sharing Task will always execute in the same thread T as the first Task; and that T is randomly chosen at the time of that 1st Task. This ensures they won't execute concurrently by definition.
per_thread_ops() is organized as follows: If N worker threads are created, then, internally, per_thread_ops()[i] is really the i-th thread. Very simple.
See discussion in Cross_thread_task_loop doc header about an "interesting experiment" related to us.
Todo:
In Segregated_thread_task_loop, when dealing with the 2-arg post() (the one taking an async::Op and an async::Task) and similar schedule_*() methods – consider postponing the random thread selection until the last possible moment, as opposed to in create_op(). Given that Segregated_thread_task_loop is legacy-ish in nature, the resulting significant increase in internal complexity may or may not be worth accepting. This to-do also makes little practical difference without the nearby to-do that would bias in favor of less-loaded threads.
Todo:
In Segregated_thread_task_loop, when randomly selecting a thread, considering trying to bias in favor of threads with less load (perhaps measured as # of tasks enqueued in a given thread's Task_engine); and/or round-robin thread assignment; and/or other heuristics.
Definition at line 61 of file segregated_thread_task_loop.hpp.
Member Typedef Documentation
Task_qing_thread_ptr
using flow::async::Segregated_thread_task_loop::Task_qing_thread_ptr = boost::movelib::unique_ptr<Task_qing_thread> private
Short-hand for smart pointer to Task_qing_thread.
Definition at line 238 of file segregated_thread_task_loop.hpp.
Constructor & Destructor Documentation
Segregated_thread_task_loop()
flow::async::Segregated_thread_task_loop::Segregated_thread_task_loop (log::Logger * logger_ptr, util::String_view nickname, size_t n_threads_or_zero, bool est_hw_core_sharing_helps_algo = false, bool est_hw_core_pinning_helps_algo = false, bool hw_threads_is_grouping_collated = false) explicit
Constructs object, making it available for post() and similar work, but without starting any threads and hence without the ability to perform any work; call start() to spawn threads and perform work.
The arguments n_threads_or_zero and ones following it should be viewed as configuration for the next start() call.
Parameters
logger_ptr Logger to use for subsequently logging.
nickname Brief, human-readable nickname of the new thread pool, as of this writing for logging only.
n_threads_or_zero If non-zero, start() will start exactly this many worker threads; and the system will be entirely entrusted with the question of which thread is assigned to which processor core and any subsequent migration. If zero, start() attempts to optimize the thread count and thread-to-core relationship itself, per optimal_worker_thread_count_per_pool() and optimize_pinning_in_thread_pool(). The thread pool will choose the worker thread count and any thread-to-core relationships as per those methods, having made the assumptions documented for those functions.
est_hw_core_sharing_helps_algo See optimal_worker_thread_count_per_pool().
est_hw_core_pinning_helps_algo See optimize_pinning_in_thread_pool().
hw_threads_is_grouping_collated See optimize_pinning_in_thread_pool().
Definition at line 29 of file segregated_thread_task_loop.cpp.
References FLOW_LOG_INFO, flow::log::Log_context::get_logger(), m_nickname, m_per_thread_ops, m_task_engines, n_threads(), and flow::async::S_ASYNC.
~Segregated_thread_task_loop()
flow::async::Segregated_thread_task_loop::~Segregated_thread_task_loop () override
See superclass destructor.
Definition at line 88 of file segregated_thread_task_loop.cpp.
References FLOW_LOG_INFO, and stop().
Member Function Documentation
create_op()
Op flow::async::Segregated_thread_task_loop::create_op () override virtual
Implements superclass API.
In this implementation: async::Op has the "weight" of a raw pointer and internally corresponds to a thread.
Returns
See superclass API.
Implements flow::async::Concurrent_task_loop.
Definition at line 265 of file segregated_thread_task_loop.cpp.
References per_thread_ops(), and flow::async::Op_list::random_op().
n_threads()
size_t flow::async::Segregated_thread_task_loop::n_threads () const override virtual
Implements superclass API.
Returns
See superclass API.
Implements flow::async::Concurrent_task_loop.
Definition at line 260 of file segregated_thread_task_loop.cpp.
References m_qing_threads.
Referenced by schedule_from_now_impl(), Segregated_thread_task_loop(), and start().
per_thread_ops()
const Op_list & flow::async::Segregated_thread_task_loop::per_thread_ops () override virtual
Implements superclass API.
In this implementation: Each pre-created Op internally corresponds (1-to-1 overall) to one of the worker threads spawned at construction.
Returns
See superclass API.
Implements flow::async::Concurrent_task_loop.
Definition at line 270 of file segregated_thread_task_loop.cpp.
References m_per_thread_ops.
Referenced by create_op(), post(), schedule_from_now(), and task_engine().
post() [1/2]
void flow::async::Segregated_thread_task_loop::post (const Op & op, Task && task, Synchronicity synchronicity = Synchronicity::S_ASYNC) override virtual
Implements superclass API.
In this implementation: identical to 1-arg post() for the first async::Task to be associated with op (randomly choose T, then basically 1-arg-post() equivalent); for subsequent such Tasks act similarly but simply keep that same T.
Parameters
op See superclass API.
task See superclass API.
synchronicity See superclass API.
Implements flow::async::Concurrent_task_loop.
Definition at line 295 of file segregated_thread_task_loop.cpp.
References FLOW_LOG_TRACE, flow::async::op_to_exec_ctx< Task_engine_ptr >(), and post_impl().
post() [2/2]
void flow::async::Segregated_thread_task_loop::post (Task && task, Synchronicity synchronicity = Synchronicity::S_ASYNC) override virtual
Implements superclass API.
In this implementation: task will execute as soon as thread T is available, because no other applicable work is forthcoming; and T is randomly chosen by the implementation.
Parameters
task See superclass API.
synchronicity See superclass API.
Implements flow::async::Concurrent_task_loop.
Definition at line 275 of file segregated_thread_task_loop.cpp.
References FLOW_LOG_TRACE, m_task_engines, per_thread_ops(), post_impl(), and flow::async::Op_list::random_idx().
Referenced by start().
post_impl()
void flow::async::Segregated_thread_task_loop::post_impl (const Task_engine_ptr & chosen_task_engine, Synchronicity synchronicity, Task && task) private
Helper performing the core Task_engine::post() (or similar) call on behalf of the various post() overloads.
Parameters
chosen_task_engine The value m_qing_threads[idx].task_engine(). for some valid idx: the engine for the thread selected to execute task.
synchronicity See any post().
task See any post().
Definition at line 360 of file segregated_thread_task_loop.cpp.
References flow::log::Log_context::get_logger().
Referenced by post().
schedule_at() [1/2]
util::Scheduled_task_handle flow::async::Segregated_thread_task_loop::schedule_at (const Fine_time_pt & at, Scheduled_task && task) override virtual
Implements superclass API.
See also 1-arg post().
Parameters
at See superclass API.
task See superclass API.
Returns
See superclass API.
Implements flow::async::Concurrent_task_loop.
Definition at line 345 of file segregated_thread_task_loop.cpp.
References schedule_from_now().
schedule_at() [2/2]
util::Scheduled_task_handle flow::async::Segregated_thread_task_loop::schedule_at (const Op & op, const Fine_time_pt & at, Scheduled_task && task) override virtual
See superclass API.
See also 2-arg post().
Parameters
op See superclass API.
at See superclass API.
task See superclass API.
Returns
See superclass API.
Implements flow::async::Concurrent_task_loop.
Definition at line 352 of file segregated_thread_task_loop.cpp.
References schedule_from_now().
schedule_from_now() [1/2]
util::Scheduled_task_handle flow::async::Segregated_thread_task_loop::schedule_from_now (const Fine_duration & from_now, Scheduled_task && task) override virtual
Implements superclass API.
See also 1-arg post().
Parameters
from_now See superclass API.
task See superclass API.
Returns
See superclass API.
Implements flow::async::Concurrent_task_loop.
Definition at line 312 of file segregated_thread_task_loop.cpp.
References FLOW_LOG_TRACE, m_task_engines, per_thread_ops(), flow::async::Op_list::random_idx(), and schedule_from_now_impl().
Referenced by schedule_at().
schedule_from_now() [2/2]
util::Scheduled_task_handle flow::async::Segregated_thread_task_loop::schedule_from_now (const Op & op, const Fine_duration & from_now, Scheduled_task && task) override virtual
Implements superclass API.
See also 2-arg post().
Parameters
op See superclass API.
from_now See superclass API.
task See superclass API.
Returns
See superclass API.
Implements flow::async::Concurrent_task_loop.
Definition at line 328 of file segregated_thread_task_loop.cpp.
References FLOW_LOG_TRACE, flow::async::op_to_exec_ctx< Task_engine_ptr >(), and schedule_from_now_impl().
schedule_from_now_impl()
util::Scheduled_task_handle flow::async::Segregated_thread_task_loop::schedule_from_now_impl (const Task_engine_ptr & chosen_task_engine, const Fine_duration & from_now, Scheduled_task && task) private
Helper performing the core util::schedule_task_from_now() call on behalf of the various schedule_from_now() overloads.
Parameters
chosen_task_engine See post_impl().
from_now See any schedule_from_now().
task See any schedule_from_now().
Returns
See any schedule_from_now().
Definition at line 374 of file segregated_thread_task_loop.cpp.
References flow::async::cpu_idx(), FLOW_LOG_TRACE_WITHOUT_CHECKING, flow::log::Log_context::get_log_component(), flow::log::Log_context::get_logger(), n_threads(), flow::log::S_TRACE, and flow::util::schedule_task_from_now().
Referenced by schedule_from_now().
start()
void flow::async::Segregated_thread_task_loop::start (Task && init_task_or_empty = Task(), const Thread_init_func & thread_init_func_or_empty = Thread_init_func()) override virtual
Implements superclass API.
In this implementation this essentially involves repeating N times: Task_engine::restart(); spawn thread; in it execute a long-running Task_engine::run().
Logging subtlety for large thread pools
See Cross_thread_task_loop::start() doc header similar section: The exact same note applies here.
Parameters
init_task_or_empty See superclass API.
thread_init_func_or_empty See superclass API.
Implements flow::async::Concurrent_task_loop.
Definition at line 98 of file segregated_thread_task_loop.cpp.
References FLOW_LOG_INFO, flow::log::Log_context::get_logger(), m_est_hw_core_pinning_helps_algo, m_est_hw_core_sharing_helps_algo, m_hw_threads_is_grouping_collated, m_n_threads_or_zero, m_nickname, m_qing_threads, m_task_engines, n_threads(), flow::async::optimize_pinning_in_thread_pool(), flow::util::ostream_op_string(), post(), flow::async::S_ASYNC_AND_AWAIT_CONCURRENT_COMPLETION, and task_engine().
stop()
void flow::async::Segregated_thread_task_loop::stop () override virtual
Implements superclass API.
In this implementation this essentially boils down to N Task_engine::stop()s, followed by joining each thread started by start().
Logging subtlety for large thread pools
See Cross_thread_task_loop::stop() doc header similar section: The exact same note applies here.
Implements flow::async::Concurrent_task_loop.
Definition at line 192 of file segregated_thread_task_loop.cpp.
References FLOW_LOG_INFO, m_qing_threads, and m_task_engines.
Referenced by ~Segregated_thread_task_loop().
task_engine()
Task_engine_ptr flow::async::Segregated_thread_task_loop::task_engine () override virtual
See superclass API.
In this implementation: As with create_op(), this selects a thread from the pool randomly, and each thread has a 1-1 dedicated internal Task_engine. The load-balancing is hence performed, by us, at the time of this call – not later when one does the async_*() action. (Reminder: general Concurrent_task_loop-using code would not rely on this implementation information.) (Reminder: be very sure you understand what will happen if/when you pass this into a boost.asio-compliant I/O object's constructor or similar. See the warning on this topic in Concurrent_task_loop doc header.)
Returns
See superclass API.
Implements flow::async::Concurrent_task_loop.
Definition at line 404 of file segregated_thread_task_loop.cpp.
References FLOW_LOG_TRACE, m_task_engines, per_thread_ops(), and flow::async::Op_list::random_idx().
Referenced by start().
Friends And Related Function Documentation
op_to_exec_ctx()
Task_engine_ptr op_to_exec_ctx< Task_engine_ptr > (Concurrent_task_loop * loop, const Op & op) related
Template specialization for operation that obtains the underlying execution context, in this case a util::Task_engine, stored in an async::Op generated by the given Segregated_thread_task_loop.
While *loop is running, the Task_engine is running in exactly 1 thread.
Note Concurrent_task_loop::task_engine() is spiritually related to this function; but while that one gives one a random thread's util::Task_engine, this one returns the specific thread's assigned to a multi-step async op op.
See also
Concurrent_task_loop doc header for discussion.
Parameters
loop Loop object that, one way or another, generated and returned op. Behavior is undefined if the concrete pointed-to type is not Segregated_thread_task_loop. (assertion may trip).
op async::Op from *loop from which to extract the execution context on which you'd like to perform custom boost.asio work. Behavior is undefined if it is not from *loop (assertion may trip).
Returns
Pointer to a mutable util::Task_engine E used by *loop.
Member Data Documentation
m_est_hw_core_pinning_helps_algo
const bool flow::async::Segregated_thread_task_loop::m_est_hw_core_pinning_helps_algo private
See constructor.
Definition at line 280 of file segregated_thread_task_loop.hpp.
Referenced by start().
m_est_hw_core_sharing_helps_algo
const bool flow::async::Segregated_thread_task_loop::m_est_hw_core_sharing_helps_algo private
See constructor.
Definition at line 278 of file segregated_thread_task_loop.hpp.
Referenced by start().
m_hw_threads_is_grouping_collated
const bool flow::async::Segregated_thread_task_loop::m_hw_threads_is_grouping_collated private
See constructor.
Definition at line 282 of file segregated_thread_task_loop.hpp.
Referenced by start().
m_n_threads_or_zero
const size_t flow::async::Segregated_thread_task_loop::m_n_threads_or_zero private
See constructor.
Warning
Not safe to use this in lieu of n_threads() when this is in fact zero.
Definition at line 276 of file segregated_thread_task_loop.hpp.
Referenced by start().
m_nickname
const std::string flow::async::Segregated_thread_task_loop::m_nickname private
See constructor.
Definition at line 274 of file segregated_thread_task_loop.hpp.
Referenced by Segregated_thread_task_loop(), and start().
m_per_thread_ops
boost::movelib::unique_ptr<const Op_list> flow::async::Segregated_thread_task_loop::m_per_thread_ops private
See per_thread_ops().
The boost::any payload is always of the type Task_engine_ptr. The latter not being something else, namely Task_qing_thread* or similar, is due to the same thread safety reason mentioned in the warning in m_qing_threads doc header.
Definition at line 307 of file segregated_thread_task_loop.hpp.
Referenced by per_thread_ops(), and Segregated_thread_task_loop().
m_qing_threads
std::vector<Task_qing_thread_ptr> flow::async::Segregated_thread_task_loop::m_qing_threads private
N task-execution-capable worker threads whose lifetimes equal those of *this, each with its own util::Task_engine.
Due to the latter fact, util::Strand would not be useful to implement async::Op semantics; as every Task_engine involved run()s within one thread only.
Warning
Outside of ctor, this datum must not be accessed except in start() and stop(), as that would break the thread-safety guarantee wherein post() (and similar) are safe to call concurrently with start() or stop(). All such work shall be done through m_task_engines exclusively.
Definition at line 293 of file segregated_thread_task_loop.hpp.
Referenced by n_threads(), start(), and stop().
m_task_engines
std::vector<Task_engine_ptr> flow::async::Segregated_thread_task_loop::m_task_engines private
boost.asio Task_engines (a/k/a io_services) used by each respective element in m_qing_threads.
It is critical that this not be modified after constructor returns, for the same thread safety reason mentioned in the warning in m_qing_threads doc header.
Definition at line 300 of file segregated_thread_task_loop.hpp.
Referenced by post(), schedule_from_now(), Segregated_thread_task_loop(), start(), stop(), and task_engine().
The documentation for this class was generated from the following files:
async/segregated_thread_task_loop.hpp
async/async_fwd.hpp
async/segregated_thread_task_loop.cpp