Flow: flow::net_flow::Congestion_control_classic_with_bandwidth_est Class Reference
flow::net_flow::Congestion_control_classic_with_bandwidth_est Class Reference
Classic congestion control but with backoff to bandwidth estimate-based pipe size.
#include <cong_ctl_classic_bw.hpp>
Public Member Functions
Congestion_control_classic_with_bandwidth_est (log::Logger *logger_ptr, Peer_socket::Const_ptr sock)
Constructs object by setting up logging and saving a pointer to the containing Peer_socket.
size_t congestion_window_bytes () const override
Implements Congestion_control_strategy::congestion_window_bytes() API.
void on_individual_ack (const Fine_duration &packet_rtt, const size_t bytes, const size_t sent_cwnd_bytes) override
Implements Congestion_control_strategy::on_individual_ack() API.
void on_acks (size_t bytes, size_t packets) override
Implements Congestion_control_strategy::on_acks() API.
void on_loss_event (size_t bytes, size_t packets) override
Implements Congestion_control_strategy::on_loss_event() API.
void on_drop_timeout (size_t bytes, size_t packets) override
Implements Congestion_control_strategy::on_drop_timeout() API.
void on_idle_timeout () override
Implements Congestion_control_strategy::on_idle_timeout() API.
virtual size_t congestion_window_bytes () const =0
Returns the maximal number of bytes (with respect to m_data field of DATA packets) that this socket should allow to be In-flight at this time.
virtual void on_acks (size_t bytes, size_t packets)
Informs the congestion control strategy that 1 or more previously sent packets whose status was In-flight just received acknowledgments, thus changing their state from In-flight to Acknowledged.
virtual void on_loss_event (size_t bytes, size_t packets)
Informs the congestion control strategy that 1 or more previously sent packets whose status was In-flight have just been inferred to be Dropped by receiving acknowledgments of packets that were sent later than the now-Dropped packets.
virtual void on_individual_ack (const Fine_duration &packet_rtt, const size_t bytes, const size_t sent_cwnd_bytes)
Informs the congestion control strategy that exactly 1 previously sent packet whose status was In-flight is now known to have the given round trip time (RTT), via acknowledgment.
virtual void on_drop_timeout (size_t bytes, size_t packets)
Informs the congestion control strategy that 1 or more previously sent packets whose status was In-flight have just been inferred to be Dropped because of the Drop Timer expiring.
virtual void on_idle_timeout ()
Informs the congestion control strategy that Node considers the connection to be "idle" by virtue of no desired send activity on the part of the user application for some period of time.
Public Member Functions inherited from flow::util::Null_interface
virtual ~Null_interface ()=0
Boring virtual destructor.
Public Member Functions inherited from flow::log::Log_context
Log_context (Logger *logger=0)
Constructs Log_context by storing the given pointer to a Logger and a null Component.
template<typename Component_payload >
Log_context (Logger *logger, Component_payload component_payload)
Constructs Log_context by storing the given pointer to a Logger and a new Component storing the specified generically typed payload (an enum value).
Log_context (const Log_context &src)
Copy constructor that stores equal Logger* and Component values as the source.
Log_context (Log_context &&src)
Move constructor that makes this equal to src, while the latter becomes as-if default-constructed.
Log_context & operator= (const Log_context &src)
Assignment operator that behaves similarly to the copy constructor.
Log_context & operator= (Log_context &&src)
Move assignment operator that behaves similarly to the move constructor.
void swap (Log_context &other)
Swaps Logger pointers and Component objects held by *this and other.
Logger * get_logger () const
Returns the stored Logger pointer, particularly as many FLOW_LOG_*() macros expect.
const Component & get_log_component () const
Returns reference to the stored Component object, particularly as many FLOW_LOG_*() macros expect.
Private Member Functions
size_t congestion_window_adjusted_bytes () const
Returns the best bandwidth/latency-based guess for what the current window (pipe) size should be.
Private Attributes
Congestion_control_classic_data m_classic_data
The Reno CWND/SSTHRESH-changing engine and CWND/SSTHRESH storage.
Send_bandwidth_estimator::Time_unit m_rtt_min
The minimum individual packet's RTT observed so far; it should be reset to the next sample if m_reset_rtt_min is true, which may happen if our algorithm thinks the pipe has changed drastically, making past measurements useless.
bool m_reset_rtt_min
If true, then when the next RTT measurement comes in, any past measurement should be disregarded, and m_rtt_min should be set to the new measurement.
Static Private Attributes
static const Send_bandwidth_estimator::Time_unit S_INIT_RTT_MIN = boost::chrono::seconds(20)
The initial value for m_rtt_min, until one RTT measurement comes in.
Additional Inherited Members
Protected Member Functions inherited from flow::net_flow::Congestion_control_strategy
Congestion_control_strategy (log::Logger *logger_ptr, Peer_socket::Const_ptr sock)
Constructs object by setting up logging and saving a pointer to the containing Peer_socket.
Peer_socket::Const_ptr socket () const
Utility for subclasses that returns a handle to the containing Peer_socket.
Detailed Description
Classic congestion control but with backoff to bandwidth estimate-based pipe size.
Implements Congestion_control_strategy abstract API.
The basic idea is the same as in Congestion_control_classic. See that class's doc header first. Except where noted below, the algorithm is identical.
The difference is that instead of halving (or otherwise lowering by an arbitrary constant factor) the window, we set the window to a pipe width based on our estimate of the available bandwidth and the inherent latency in the pipe. The latter is tracked by keeping the minimum individual packet RTT observed thus far; the former (bandwidth estimate) is obtained from Send_bandwidth_estimator. Normally bandwidth estimation would be inside the congestion control strategy class, but since its results may be useful independently of congestion control, it is a separate module.
The specifics of the implementation are based on Westwood/Westwood+. The part about computing the pipe width based on B * RTTmin comes from the original Westwood paper. The bandwidth estimation algorithm is based on Westwood+ and is discussed in further detail in class Send_bandwidth_estimator. The reference implementation is Linux kernel's Westwood+ implementation; see Send_bandwidth_estimator doc header for references.
The strength of this algorithm is that it is potentially less timid in the face of random loss as opposed to true congestion, when compared to Congestion_control_classic (Reno). It won't just halve CWND at the slightest provocation. On the other hand bandwidth estimation seems to, in my tests at least, kind of measure the rate at which we're sending data and less the actual available pipe. Still, at least at lower latencies and loss rates it can greatly outperform Congestion_control_classic; though at higher such values it can actually be worse (at least in my crude tests – more formal testing with real simulation TBD).
See also
Congestion_control_classic, Send_bandwidth_estimator.
Definition at line 61 of file cong_ctl_classic_bw.hpp.
Constructor & Destructor Documentation
Congestion_control_classic_with_bandwidth_est()
flow::net_flow::Congestion_control_classic_with_bandwidth_est::Congestion_control_classic_with_bandwidth_est (log::Logger * logger_ptr, Peer_socket::Const_ptr sock)
Constructs object by setting up logging and saving a pointer to the containing Peer_socket.
Congestion window is chosen to be some small initial value, and an exponential congestion window growth is set up to continue indefinitely, until a loss event, drop timeout, or idle timeout.
Only a weak pointer of sock is stored: the shared_ptr itself is not saved, so the reference count of sock does not increase. This avoids a circular shared_ptr situation that would arise from *this pointing to sock, and sock pointing to *this (the two objects do need access to each other, as explained in class Congestion_control_strategy doc header).
Parameters
logger_ptr The Logger implementation to use subsequently.
sock The Peer_socket for which this module will control congestion policy.
Definition at line 31 of file cong_ctl_classic_bw.cpp.
Member Function Documentation
congestion_window_adjusted_bytes()
size_t flow::net_flow::Congestion_control_classic_with_bandwidth_est::congestion_window_adjusted_bytes () const private
Returns the best bandwidth/latency-based guess for what the current window (pipe) size should be.
Returns
A CWND/SSTHRESH-suitable value.
Definition at line 173 of file cong_ctl_classic_bw.cpp.
References FLOW_LOG_TRACE, m_rtt_min, and flow::net_flow::Congestion_control_strategy::socket().
Referenced by on_drop_timeout(), and on_loss_event().
congestion_window_bytes()
size_t flow::net_flow::Congestion_control_classic_with_bandwidth_est::congestion_window_bytes () const override virtual
Implements Congestion_control_strategy::congestion_window_bytes() API.
Returns
See Congestion_control_strategy::congestion_window_bytes().
Implements flow::net_flow::Congestion_control_strategy.
Definition at line 45 of file cong_ctl_classic_bw.cpp.
References flow::net_flow::Congestion_control_classic_data::congestion_window_bytes(), and m_classic_data.
on_acks()
void flow::net_flow::Congestion_control_classic_with_bandwidth_est::on_acks (size_t bytes, size_t packets) override virtual
Implements Congestion_control_strategy::on_acks() API.
Congestion window grows either linearly (in congestion avoidance mode) or exponentially (in slow start mode). There is no congestion avoidance mode until at least one of on_loss_event() or on_drop_timeout() occurs; at least until then slow start is in effect.
Additional Peer_socket state used: none.
Parameters
bytes See Congestion_control_strategy::on_acks().
packets See Congestion_control_strategy::on_acks().
Reimplemented from flow::net_flow::Congestion_control_strategy.
Definition at line 96 of file cong_ctl_classic_bw.cpp.
References m_classic_data, and flow::net_flow::Congestion_control_classic_data::on_acks().
on_drop_timeout()
void flow::net_flow::Congestion_control_classic_with_bandwidth_est::on_drop_timeout (size_t bytes, size_t packets) override virtual
Implements Congestion_control_strategy::on_drop_timeout() API.
Congestion window is set to a low value, while the next slow start session is set to end at a pipe width based on the estimation of the available outgoing bandwidth. Thus a slow start session, most likely, begins.
Internally this also may affect our gauge of the "true" latency of the pipe.
Additional Peer_socket state used: none.
Parameters
bytes See Congestion_control_strategy::on_drop_timeout().
packets See Congestion_control_strategy::on_drop_timeout().
Reimplemented from flow::net_flow::Congestion_control_strategy.
Definition at line 137 of file cong_ctl_classic_bw.cpp.
References congestion_window_adjusted_bytes(), FLOW_LOG_TRACE, m_classic_data, m_reset_rtt_min, flow::net_flow::Congestion_control_classic_data::on_drop_timeout(), and flow::net_flow::Congestion_control_strategy::socket().
on_idle_timeout()
void flow::net_flow::Congestion_control_classic_with_bandwidth_est::on_idle_timeout () override virtual
Implements Congestion_control_strategy::on_idle_timeout() API.
Congestion window is set to a low value. Thus a slow start session begins.
Additional Peer_socket state used: none.
Reimplemented from flow::net_flow::Congestion_control_strategy.
Definition at line 209 of file cong_ctl_classic_bw.cpp.
References m_classic_data, and flow::net_flow::Congestion_control_classic_data::on_idle_timeout().
on_individual_ack()
void flow::net_flow::Congestion_control_classic_with_bandwidth_est::on_individual_ack (const Fine_duration & packet_rtt, const size_t bytes, const size_t sent_cwnd_bytes) override virtual
Implements Congestion_control_strategy::on_individual_ack() API.
This results in no congestion_window_bytes() change but may affect its later values.
Internally this gauges the "true" latency of the pipe.
Parameters
packet_rtt See Congestion_control_strategy::on_individual_ack().
bytes See Congestion_control_strategy::on_individual_ack().
sent_cwnd_bytes See Congestion_control_strategy::on_individual_ack().
Reimplemented from flow::net_flow::Congestion_control_strategy.
Definition at line 50 of file cong_ctl_classic_bw.cpp.
References FLOW_LOG_TRACE, m_reset_rtt_min, m_rtt_min, and flow::net_flow::Congestion_control_strategy::socket().
on_loss_event()
void flow::net_flow::Congestion_control_classic_with_bandwidth_est::on_loss_event (size_t bytes, size_t packets) override virtual
Implements Congestion_control_strategy::on_loss_event() API.
Congestion window changes (probably drops) to a value based on the estimation of the available outgoing bandwidth, and the next slow start (if any, e.g., on a later Drop Timeout) will end once the congestion window exceeds this value. Thus after this call congestion avoidance mode begins anew.
Additional Peer_socket state used: none.
Parameters
bytes See Congestion_control_strategy::on_loss_event().
packets See Congestion_control_strategy::on_loss_event().
Reimplemented from flow::net_flow::Congestion_control_strategy.
Definition at line 103 of file cong_ctl_classic_bw.cpp.
References congestion_window_adjusted_bytes(), FLOW_LOG_TRACE, m_classic_data, flow::net_flow::Congestion_control_classic_data::on_congestion_event(), and flow::net_flow::Congestion_control_strategy::socket().
Member Data Documentation
m_classic_data
Congestion_control_classic_data flow::net_flow::Congestion_control_classic_with_bandwidth_est::m_classic_data private
The Reno CWND/SSTHRESH-changing engine and CWND/SSTHRESH storage.
Definition at line 187 of file cong_ctl_classic_bw.hpp.
Referenced by congestion_window_bytes(), on_acks(), on_drop_timeout(), on_idle_timeout(), and on_loss_event().
m_reset_rtt_min
bool flow::net_flow::Congestion_control_classic_with_bandwidth_est::m_reset_rtt_min private
If true, then when the next RTT measurement comes in, any past measurement should be disregarded, and m_rtt_min should be set to the new measurement.
Do this if the pipe may have drastically changed, obsoleting any prior observations.
Definition at line 201 of file cong_ctl_classic_bw.hpp.
Referenced by on_drop_timeout(), and on_individual_ack().
m_rtt_min
Send_bandwidth_estimator::Time_unit flow::net_flow::Congestion_control_classic_with_bandwidth_est::m_rtt_min private
The minimum individual packet's RTT observed so far; it should be reset to the next sample if m_reset_rtt_min is true, which may happen if our algorithm thinks the pipe has changed drastically, making past measurements useless.
Definition at line 194 of file cong_ctl_classic_bw.hpp.
Referenced by congestion_window_adjusted_bytes(), and on_individual_ack().
S_INIT_RTT_MIN
const Send_bandwidth_estimator::Time_unit flow::net_flow::Congestion_control_classic_with_bandwidth_est::S_INIT_RTT_MIN = boost::chrono::seconds(20) static private
The initial value for m_rtt_min, until one RTT measurement comes in.
Initialize to conservatively large value. I considered making this configurable, but it doesn't seem worth it, as we'll get a real RTT sample with the very first ACK that arrives. Also the Linux tcp_westwood.c reference implementation does the same thing (a hard constant).
Definition at line 182 of file cong_ctl_classic_bw.hpp.
The documentation for this class was generated from the following files:
net_flow/detail/cong_ctl/cong_ctl_classic_bw.hpp
net_flow/detail/cong_ctl/cong_ctl_classic_bw.cpp