Flow: flow::perf::Checkpointing_timer::Aggregator Class Reference
flow::perf::Checkpointing_timer::Aggregator Class Reference
This companion/inner class of Checkpointing_timer provides aggregation of results from many Checkpointing_timers each measuring some user operation being repeated many times; particularly when the operation consists of multiple steps (checkpoints) of interest.
#include <checkpt_timer.hpp>
Public Member Functions
Aggregator (log::Logger *logger_ptr, std::string &&name_moved, size_t max_n_samples)
Constructs a new, empty aggregator.
void aggregate (Checkpointing_timer_ptr timer_ptr)
Register given Checkpointing_timer for aggregated results.
void clear ()
Act as if aggregate() has never been called since construction.
void log_aggregated_results (log::Logger *alternate_logger_ptr_or_null, bool show_sum, bool show_mean, uint64_t mean_scale_or_zero) const
Called after the final Checkpointing_timer has finished (final checkpoint() call) and been aggregate()d, this INFO-logs human-friendly readout of the aggregated results so far.
Checkpointing_timer_ptr create_aggregated_result (log::Logger *alternate_logger_ptr_or_null, bool info_log_result, uint64_t mean_scale_or_zero=1) const
Provides programmatic access to the aggregation result that would be logged by log_aggregated_results() – in the form of a returned new Checkpointing_timer that stores those numbers.
Public Member Functions inherited from flow::log::Log_context
Log_context (Logger *logger=0)
Constructs Log_context by storing the given pointer to a Logger and a null Component.
template<typename Component_payload >
Log_context (Logger *logger, Component_payload component_payload)
Constructs Log_context by storing the given pointer to a Logger and a new Component storing the specified generically typed payload (an enum value).
Log_context (const Log_context &src)
Copy constructor that stores equal Logger* and Component values as the source.
Log_context (Log_context &&src)
Move constructor that makes this equal to src, while the latter becomes as-if default-constructed.
Log_context & operator= (const Log_context &src)
Assignment operator that behaves similarly to the copy constructor.
Log_context & operator= (Log_context &&src)
Move assignment operator that behaves similarly to the move constructor.
void swap (Log_context &other)
Swaps Logger pointers and Component objects held by *this and other.
Logger * get_logger () const
Returns the stored Logger pointer, particularly as many FLOW_LOG_*() macros expect.
const Component & get_log_component () const
Returns reference to the stored Component object, particularly as many FLOW_LOG_*() macros expect.
Static Public Member Functions
static void log_aggregated_result_in_timer (log::Logger *logger_ptr, const Checkpointing_timer &agg_timer, unsigned int n_samples, uint64_t mean_scale_or_zero=1)
Given an aggregated-result Checkpointing_timer (as if returned by create_aggregated_result()) logs the SUM or MEAN or SCALED-MEAN stored in it as INFO messages.
Public Attributes
const std::string m_name
The immutable human-readable name for this timer. It's const so no need for accessor for now.
Private Attributes
std::vector< Checkpointing_timer_ptr > m_timers
The ref-counted pointers to source timers passed to aggregate() in that order.
Detailed Description
This companion/inner class of Checkpointing_timer provides aggregation of results from many Checkpointing_timers each measuring some user operation being repeated many times; particularly when the operation consists of multiple steps (checkpoints) of interest.
Please read the aggregation section in Checkpointing_timer doc header before using this.
One small technical point: To make a Checkpointing_timer X available for Aggregator::aggregate(X), you must construct it on the heap and provide a Checkpointing_timer_ptr accordingly:
Checkpointing_timer_ptr X(new Checkpointing_timer(...));
Thread safety
A reiteration of the aforementioned Checkpointing_timer doc header: Non-const methods are generally not safe if called concurrently with any other method on the same Aggregator. In practice this should only matter for calling aggregate(). If you are timing things concurrently happening in different threads you may need to add a mutex lock around aggregate(); and in that case make sure it doesn't adversely affect your algorithm's overall performance (or, if it does, then that is acceptable).
Definition at line 556 of file checkpt_timer.hpp.
Constructor & Destructor Documentation
Aggregator()
flow::perf::Checkpointing_timer::Aggregator::Aggregator (log::Logger * logger_ptr, std::string && name_moved, size_t max_n_samples) explicit
Constructs a new, empty aggregator.
After this call aggregate() to add source Checkpointing_timers.
Parameters
name_moved Nickname for the agg, for logging and such.
max_n_samples The number of times you shall call aggregate() shall not exceed this. See similar (in spirit) max_n_checkpoints in Checkpointing_timer constructor.
logger_ptr Logger to use for subsequently logging.
Definition at line 348 of file checkpt_timer.cpp.
References m_timers.
Member Function Documentation
aggregate()
void flow::perf::Checkpointing_timer::Aggregator::aggregate (Checkpointing_timer_ptr timer_ptr)
Register given Checkpointing_timer for aggregated results.
The best time to call this is immediately after the last timer_ptr->checkpoint() call, as that way the call itself won't be included in the timer's duration(s).
The second best time to call it is immediately after *timer_ptr is constructed; the call is quite cheap, so it really shouldn't affect results much. The third best time is somewhere between those 2 points in time; in that case its (quite small, probably negligible) time cost will be charged to whatever checkpoint was "running" at the time.
Requirements on aggregated timers
In and of itself *timer_ptr can be any Checkpointing_timer with at least one checkpoint() call done. In addition, behavior is undefined in log_aggregated_results() and create_aggregated_result() unless all of the following hold about all aggregate()d timers at the time of those calls.
Their which_clocks values (as passed to Checkpointing_timer constructor) are all equal.
They each have the same number of checkpoints.
For each i: Their i-th Checkpointing_timer::Checkpoint::m_name values are all mutually equal.
Since aggregation collates the many measurements of the same multi-step operation, these should all be common sense; if one doesn't hold for you, there is some kind of very basic problem.
Thread safety
See Aggregator doc header. A mutex lock around this call may be desirable depending on situation.
Parameters
timer_ptr The timer to register.
Definition at line 357 of file checkpt_timer.cpp.
References FLOW_LOG_TRACE, and flow::perf::Checkpointing_timer::m_name.
clear()
void flow::perf::Checkpointing_timer::Aggregator::clear ()
Act as if aggregate() has never been called since construction.
Definition at line 366 of file checkpt_timer.cpp.
create_aggregated_result()
Checkpointing_timer_ptr flow::perf::Checkpointing_timer::Aggregator::create_aggregated_result (log::Logger * alternate_logger_ptr_or_null, bool info_log_result, uint64_t mean_scale_or_zero = 1) const
Provides programmatic access to the aggregation result that would be logged by log_aggregated_results() – in the form of a returned new Checkpointing_timer that stores those numbers.
log_aggregated_results() basically calls this once for each type of aggregated data it wants to see. Accordingly, if you desire programmatic access to type X of aggregated results, call this and specify the type X of interest, as args. log_aggregated_results() doc header's perf notes apply here similarly.
You can also use info_log_result to immediately log the results, as log_aggregated_results() would for that aggregation type. Conceivably you could then ignore the return value, depending on your goals.
Parameters
alternate_logger_ptr_or_null Same meaning as for log_aggregated_results(). However here this is only relevant if info_log_result; otherwise ignored (null is fine).
info_log_result If and only if true, INFO messages are logged with human-readable representation of the returned data, similarly to (partial) log_aggregated_results() output. Actually it simply calls log_aggregated_result_in_timer() on the returned Checkpointing_timer.
mean_scale_or_zero If zero then return SUM aggregated output; otherwise MEAN or SCALED-MEAN aggregated output, with this value as the scale-constant (the value 1 => an un-scaled MEAN output). (E.g., one could show the average latency per 100,000 requests which might be more conveniently large than a per-request mean.)
Returns
Ref-counted pointer to a new Checkpointing_timer that stores the aggregated results. This timer will have the same which_clocks, and its checkpoints() will have the same length and in-order names, as each of the source timers; its name and get_logger() will come from Aggregator name (ctor arg) and get_logger() respectively.
Definition at line 371 of file checkpt_timer.cpp.
References flow::perf::Checkpointing_timer::checkpoint(), flow::perf::Checkpointing_timer::Checkpointing_timer(), FLOW_LOG_TRACE, flow::log::Log_context::get_logger(), flow::perf::Checkpointing_timer::Checkpoint::m_name, flow::perf::Checkpointing_timer::m_name, flow::perf::Checkpointing_timer::Checkpoint::m_since_last, and flow::perf::Duration_set::m_values.
log_aggregated_result_in_timer()
void flow::perf::Checkpointing_timer::Aggregator::log_aggregated_result_in_timer (log::Logger * logger_ptr, const Checkpointing_timer & agg_timer, unsigned int n_samples, uint64_t mean_scale_or_zero = 1) static
Given an aggregated-result Checkpointing_timer (as if returned by create_aggregated_result()) logs the SUM or MEAN or SCALED-MEAN stored in it as INFO messages.
Publicly, it exists for one use case (as of this writing), namely to log a "manually" compiled aggregated-result Checkpointing_timer. This pattern is explained in the Checkpointing_timer doc header in the aggregation section.
Naturally, it is also used internally by create_aggregated_result() and log_aggregated_results(), hence why they all produce similar output.
Parameters
logger_ptr Same meaning as in log_aggregated_results(), except null is not a valid value (behavior is undefined).
agg_timer Aggregated-result Checkpointing_timer, as if returned by create_aggregated_result(). Behavior is undefined unless it was, in fact, returned by that method (or is a copy of such); or unless it was compiled as described in the aforementioned pattern, documented in Checkpointing_timer doc header.
n_samples For appropriate logging, this must contain the # of samples (repetitions of the measured operation) collected to yield agg_timer.
mean_scale_or_zero For appropriate logging, this must contain the type of aggregated numbers that are stored in agg_timer. See create_aggregated_result().
Definition at line 470 of file checkpt_timer.cpp.
References FLOW_LOG_INFO, FLOW_LOG_SET_CONTEXT, and flow::perf::Checkpointing_timer::m_name.
log_aggregated_results()
void flow::perf::Checkpointing_timer::Aggregator::log_aggregated_results (log::Logger * alternate_logger_ptr_or_null, bool show_sum, bool show_mean, uint64_t mean_scale_or_zero) const
Called after the final Checkpointing_timer has finished (final checkpoint() call) and been aggregate()d, this INFO-logs human-friendly readout of the aggregated results so far.
This will include all 3 types of aggregation: sum; mean; and mean-scaled-by-convenience-constant; or some specified subset thereof.
Performance
It is possible to call it between aggregate()s, perhaps to output incremental results. It may be slow and should not be called within any perf-critical section and definitely not in any measured section. The most natural time to call it is after all data collection has finished.
Parameters
alternate_logger_ptr_or_null If null, logs are sent to get_logger() as normal; otherwise it is sent to the supplied log::Logger instead. Since logging this output is a first-class facility within Checkpointing_timer::Aggregator – unlike vast majority of Flow logging which is a secondary (though important in practice) nicety – it seemed sensible to provide extra control of this particular bit of logging. Also note that any (probably TRACE) logging outside of the timer-data output will still go to get_logger().
show_sum Whether to show the SUM aggregated output type.
show_mean Whether to show the MEAN aggregated output type.
mean_scale_or_zero If zero do not show SCALED-MEAN aggregated output; otherwise show it, with this value as the scale-constant. (E.g., one could show the average latency per 100,000 requests which might be more conveniently large than a per-request mean.)
Definition at line 506 of file checkpt_timer.cpp.
References FLOW_LOG_INFO.
Member Data Documentation
m_name
const std::string flow::perf::Checkpointing_timer::Aggregator::m_name
The immutable human-readable name for this timer. It's const so no need for accessor for now.
Definition at line 700 of file checkpt_timer.hpp.
m_timers
std::vector<Checkpointing_timer_ptr> flow::perf::Checkpointing_timer::Aggregator::m_timers private
The ref-counted pointers to source timers passed to aggregate() in that order.
Definition at line 706 of file checkpt_timer.hpp.
Referenced by Aggregator().
The documentation for this class was generated from the following files:
perf/checkpt_timer.hpp
perf/checkpt_timer.cpp