Flow: flow::net_flow::Low_lvl_packet Struct Reference
flow::net_flow::Low_lvl_packet Struct Reference abstract
Internal net_flow struct that encapsulates the Flow-protocol low-level packet structure and serves as the super-type for all specific packet types, represented by derived structs like Ack_packet, Rst_packet, etc.
#include <low_lvl_packet.hpp>
Classes
struct Aux_raw_data
Helper data store type for storing binary data needed by serialize_to_raw_data(), when certains bits are not already represented by the public data members present in struct Low_lvl_packet.
struct Packet_type_info
A simple, unmodifiable data store that contains the properties unique to each packet type a/k/a concrete sub-type of Low_lvl_packet.
Public Types
using Const_buffer = boost::asio::const_buffer
Short-hand for boost.asio immutable buffer, which essentially is a pointer to and length of a memory area.
using Const_buffer_sequence = std::vector< Const_buffer >
Short-hand for sequence of immutable buffers; i.e., a sequence of 1 or more scattered areas in memory.
using security_token_t = uint64_t
Type used for m_security_token member of a couple different packet types.
using rexmit_id_t = uint8_t
Type used to store the retransmission count in DATA and ACK packets.
using rcv_wnd_t = uint32_t
Type used to store the size of m_rcv_wnd member in a couple of different packet types.
Public Types inherited from flow::util::Shared_ptr_alias_holder< boost::shared_ptr< Low_lvl_packet > >
using Ptr = boost::shared_ptr< Low_lvl_packet >
Short-hand for ref-counted pointer to mutable values of type Target_type::element_type (a-la T*).
using Const_ptr = Const_target_ptr
Short-hand for ref-counted pointer to immutable values of type Target_type::element_type (a-la T const *).
Public Member Functions
virtual size_t serialize_to_raw_data (Const_buffer_sequence *raw_bufs) const =0
Serializes the current logical packet data from *this into the given Const_buffer_sequence, which is a sequence of pointers and lengths of existing scattered areas in memory, presumably for transmission over the wire to a compatible serializing Node.
size_t serialize_to_raw_data_and_log (Const_buffer_sequence *raw_bufs) const
Identical to serialize_to_raw_data() but adds log-level-appropriate logging after the operation.
Public Member Functions inherited from flow::util::Null_interface
virtual ~Null_interface ()=0
Boring virtual destructor.
Public Member Functions inherited from flow::log::Log_context
Log_context (Logger *logger=0)
Constructs Log_context by storing the given pointer to a Logger and a null Component.
template<typename Component_payload >
Log_context (Logger *logger, Component_payload component_payload)
Constructs Log_context by storing the given pointer to a Logger and a new Component storing the specified generically typed payload (an enum value).
Log_context (const Log_context &src)
Copy constructor that stores equal Logger* and Component values as the source.
Log_context (Log_context &&src)
Move constructor that makes this equal to src, while the latter becomes as-if default-constructed.
Log_context & operator= (const Log_context &src)
Assignment operator that behaves similarly to the copy constructor.
Log_context & operator= (Log_context &&src)
Move assignment operator that behaves similarly to the move constructor.
void swap (Log_context &other)
Swaps Logger pointers and Component objects held by *this and other.
Logger * get_logger () const
Returns the stored Logger pointer, particularly as many FLOW_LOG_*() macros expect.
const Component & get_log_component () const
Returns reference to the stored Component object, particularly as many FLOW_LOG_*() macros expect.
Static Public Member Functions
template<typename Low_lvl_packet_sub >
static boost::shared_ptr< Low_lvl_packet_sub > create_uninit_packet (log::Logger *logger_ptr)
Constructs packet with uninitialized (essentially random) values, of the Low_lvl_packet sub-type specified as the template parameter (Ack_packet, Rst_packet, etc.).
template<typename Low_lvl_packet_sub >
static Ptr create_uninit_packet_base (log::Logger *logger_ptr)
A simple convenience method that casts the result of create_uninit_packet() from shared_ptr<T>, where T is a sub-type of Low_lvl_packet, to shared_ptr<Low_lvl_packet> a/k/a Ptr.
static Ptr create_from_raw_data_packet (log::Logger *logger_ptr, util::Blob *raw_packet, bool prefer_no_move)
Constructs packet on the heap with values determined by the given raw binary data as presumably received from the wire and originally serialized by a compatible serializing Node.
static const std::string & type_id_to_str (const std::type_index &type_id)
Returns a brief (a few characters) string description of the given packet type given as type_index(typeid(p)), where p is a reference to an instance of a concrete Low_lvl_packet sub-type.
Static Public Member Functions inherited from flow::util::Shared_ptr_alias_holder< boost::shared_ptr< Low_lvl_packet > >
static Ptr ptr_cast (const From_ptr &ptr_to_cast)
Provides syntactic-sugary way to perform a static_pointer_cast<> from a compatible smart pointer type From_ptr, typically From_ptr::element_type being in the same class hierarchy as Target_ptr::element_type.
static Const_ptr const_ptr_cast (const From_ptr &ptr_to_cast)
Identical to ptr_cast() but adds const-ness (immutability) to the pointed-to type.
static Ptr dynamic_ptr_cast (const From_ptr &ptr_to_cast)
Equivalent to ptr_cast() but a dynamic_pointer_cast instead of static.
static Const_ptr dynamic_const_ptr_cast (const From_ptr &ptr_to_cast)
Identical to const_ptr_cast() but a dynamic_pointer_cast instead of static.
Public Attributes
bool m_opt_rexmit_on
Option indicating whether this connection is using retransmission or not.
struct {
flow_port_t m_src_port
Flow-protocol port # of socket in sending Node.
flow_port_t m_dst_port
Flow-protocol port # of socket in receiving Node.
} m_packed
Packed group affected by #pragma pack.
const Function< std::ostream &(std::ostream &)> m_type_ostream_manip
ostream manipulator (argument to ostream <<) that will output packet's type ("ACK", "RST", etc.).
const Function< std::ostream &(std::ostream &)> m_verbose_ostream_manip
ostream manipulator (argument to ostream <<) that will output packet info suitable for DATA log level.
const Function< std::ostream &(std::ostream &)> m_concise_ostream_manip
ostream manipulator (argument to ostream <<) that will output packet info suitable for TRACE log level.
Protected Member Functions
Low_lvl_packet (log::Logger *logger_ptr)
Constructs packet with uninitialized (essentially random) values.
size_t serialize_common_header_to_raw_data (Const_buffer_sequence *raw_bufs) const
Helper for serialize_to_raw_data() implementations in sub-types that encodes the header common to all packet types, starting with the packet type ID leading that header.
virtual std::ostream & to_ostream (std::ostream &os, bool verbose=false) const
Writes a multi-line representation of *this to an output stream.
Static Protected Member Functions
static constexpr bool native_is_big_endian ()
Returns true, at compile time, if and only if the native memory representation is big-endian, meaning, for example, the value uint32_t(1) is stored as the bytes, in order, 0x00 0x00 0x00 0x01, and not the reverse.
Private Member Functions
std::ostream & type_to_ostream (std::ostream &os) const
Writes a brief representation of typeid(*this) – i.e., the packet type (ACK, RST, etc.) – to an output stream.
virtual bool deserialize_type_specific_data_from_raw_data_packet (Const_buffer *raw_buf, bool prefer_no_move, util::Blob *raw_packet)=0
virtual helper for create_from_raw_data_packet() that fills out the fields of *this that are not in Low_lvl_packet but rather in the sub-type.
Static Private Member Functions
static const uint8_t & type_id_native_to_raw (const std::type_info &type_id)
Helper that looks up the Packet_type_info::m_raw_type_id value for the given typeid(p), where p refers to an instance of a concrete sub-type of Low_lvl_packet.
Private Attributes
Aux_raw_data m_aux_raw_data
Auxilliary data area necessary for serialize_to_raw_data() to work.
Static Private Attributes
static const boost::unordered_map< std::type_index, Packet_type_info > S_NATIVE_TYPE_ID_TO_PACKET_TYPE_INFO
Mapping from native typeid(), a/k/a packet type (for all possible packet types), to the set of properties of that packet type.
Detailed Description
Internal net_flow struct that encapsulates the Flow-protocol low-level packet structure and serves as the super-type for all specific packet types, represented by derived structs like Ack_packet, Rst_packet, etc.
This struct and its sub-struct hierarchy are not too complex but nevertheless are somewhat unorthodox, combining a few different paradigms. So it's worth explaining these paradigms.
Paradigm: Data store
This is a struct holding the conceptual contents of a packet. Low_lvl_packet stores common values like m_opt_rexmit_on, m_src_port, and a few more. Each sub-struct stores further values specific to each packet type; for example, as of this writing, Data_packet::m_data contains the data payload of a DATA packet; this would not apply, for example, to another sub-struct like Rst_packet, because an RST stores no binary blob like that.
Since it's a simple data store, the applicable data members (in this struct and the sub-types) are both public AND non-const. They can be read and written at will, thus changing or reading the logical contents of the packet.
Paradigm: Polymorphic type
While a simple data store, it also represents a hierarchy of possible packet types, and indeed a number of important polymorphic operations are included. Some are private/internal, and some are public. A public method may not appear polymorphic by its signature, but in that case usually its implementation uses non-public virtual methods to accomplish its tasks. Specifically, the key APIs are:
create_uninit_packet<T>(): This creates an uninitialized sub-object of Low_lvl_packet, of actual type T, where T derives from Low_lvl_packet. This returns a shared_ptr<T>, and any actual constructor used to implement this factory method is non-public, so the only way for a user to create a Low_lvl_packet is to get at a ref-counted pointer to it – not a raw, unprotected pointer. If storing only shared_ptr<T> or Ptr values, deletion is not something to worry about, as it will happen automatically.
Same with the other factory methods described just below. Direct access to Low_lvl_packet* or T*, where T derives from Low_lvl_packet, is not allowed (but this is not enforced at compile time and, at best, via assert()s at runtime).
create_from_raw_data_packet(): Given a raw serialized packet, this factory method constructs a Low_lvl_packet of the appropriate polymorphic sub-type, filling it at all levels with the data deserialized for the input binary blob. Internally, it uses some private, virtual action to get this to work. At any rate, this method is used to crete a logical representation of a packet off the wire.
serialize_to_raw_data(): The opposite operation: convert existing object to raw data sendable over the wire. This uses a high-performance scatter-gather paradigm of producing a sequence of pointers and lengths to already existing data areas, avoiding copying. This thing is virtual and applies to any Low_lvl_packet sub-object.
(Reminder: As with all polymorphism and shared_ptr, you may need static_pointer_cast<> to up- and down-cast between Low_lvl_packet and subclasses. Also Low_lvl_packet::ptr_cast() up-casts even syntactically-sugarier-ly.)
The two basic flows are:
Call create_uninit_packet<T>() to construct a sub-struct of Low_lvl_packet, returned as a ref-counted pointer to T. Fill out all the fields manually, accessing object via aforemetioned smart pointer. Call serialize_to_raw_data(). Pass result of latter to a boost.asio network-sending routine to send over wire. Ensure you pass a Ptr to the completion handler passed to that routine, so that the Low_lvl_packet survives while being sent. The handler can let the Ptr go out of scope, likely deleteing the Low_lvl_packet.
Receive raw packet over wire. Call create_from_raw_data_packet() to yield a Low_lvl_packet::Ptr pointing to new Low_lvl_packet sub-object with all fields filled out. Read the fields as needed to process the packet; store the Ptr if necessary; eventually removing it from all data structures will drop ref-count to zero, and it will be auto-deleted.
Other utlities
A number of (typically polymorphic) facilities exist, mainly to log these objects to ostreams, including when logging with FLOW_LOG_TRACE() and FLOW_LOG_DATA().
m_verbose_ostream_manip and m_concise_ostream_manip are const data members that can be output via the usual << operator to ostreams in order to output verbose and concise descriptions of any Low_lvl_packet (of any sub-struct type, polymorphically).
m_type_ostream_manip can be similarly used to output just the packet type of any given Low_lvl_packet (producing strings like "ACK" or "RST").
The implementation of these is typically some polymorphic virtual magic, but the use is straightforward using these ostream manipulator data members.
Implementation notes
History of approaches
Originally the implementation used the boost.serialization library for packet serialization, but it turned out to consume way too much CPU time which consequently limited the maximum throughput at high speeds. The next implementation used the traditional approach based on "packed" structures (structures without any padding), in one big struct Low_lvl_packet. However, I deemed the latter setup too C-like (yet simultaneously not C-like enough, in that no unions were used, hence RAM was wasted despite the C-like approach). Ultimately, the current version of the implementation came about, with its polymorphic struct hierarchy and abstract Low_lvl_packet struct (which, in the previous iteration, simply contained everything about every type, complete with an enum Type instead of using C++'s built-in typeid, as the current version uses).
While the above evolution was more about coding style philosophy (from a single type and a type selector enum to a polymorphic hierarchy and typeid), the other evolution concerned the way serialization (for sending over the write) worked. At first, as mentioned, there were the logical values (which were public and non-const), and there were private packed structs into which the logical values were placed (with transformation for endianness and other things) at serialization time; finally then assembling a newly allocated single binary buffer, those packed structs copied into it. Not bad – rather verbose having all those types defined, but not bad – but it did involve a new buffer and linear-time copying into that buffer. This seemed like a shame.
This led to the final improvement, which was to turn the serialization function into one that generates a boost::asio::const_buffer_sequence, basically a sequence of pointers and associated lengths of areas already present in memory. In most cases (with a couple small exceptions), the stored public data members (e.g., m_src_port and Data_packet::m_data) could simply have their addresses and lengths taken and placed into the const_buffer_sequence – no buffer copying involved. This should achieve a nice performance improvement. The removal of things like struct Common_header and struct Ack_header is a good bonus coding-wise, too.
(There is a caveat there. While no issue for the true performance culprits, namely Data_packet::m_data, the various multi-byte integer values like m_src_port technically have to undergo endianness conversion during serialization. So technically simply taking an address and size is not enough; the value needs to be flipped potentially. In reality, though, all relevant architectures are such that we chose identical network byte order as memory byte order, making no flipping necessary in practice. Of course, if we spread to an architecture where this is not true, everything will explode. However, a compile-time assertion would warn us of this, and a nearby comment will instruct on how to deal with the problem, in the unlikely case it were to appear. [Little-endian is rather universal these days.])
Packed structures, stored integers, and alignment
When 2 or more contiguous data members are used in serializing (serialize_to_raw_data() or overridden version), they are packed together via "#pragma pack". (Note that this affect entire structs at a time only; hence we need to use some anonymously-typed grouping structs named m_packed.)
Numeric values are stored as unsigned integers, which is the most portable choice for serializing. Booleans are serialized as bytes for compactness.
Some effort is made to keep fields aligned along word edges when serializing. There is not too much of that as of this writing, but we should remain vigilant as packet formats become more complex over time.
Todo:
With C++11, some lines of code could be eliminated by using using for Low_lvl_packet sub-types to inherit the constructor(s) of Low_lvl_packet. (For some of the sub-types an explicit constructor would still be necessary, but it would just shadow the inherited one, which is fine and still saves lines in the other sub-types.) However, for now I've left it as-is, partially to be friendly to the Doxygen documentation generator, and partially to make the interface easy to read. Still, it may be better the other way.
Definition at line 164 of file low_lvl_packet.hpp.
Member Typedef Documentation
Const_buffer
using flow::net_flow::Low_lvl_packet::Const_buffer = boost::asio::const_buffer
Short-hand for boost.asio immutable buffer, which essentially is a pointer to and length of a memory area.
Todo:
Consider moving alias Low_lvl_packet::Const_buffer to util namespace or even outside it, as it is used commonly (or boost::asio::const_buffer is used where Const_buffer could be used for readability).
Definition at line 179 of file low_lvl_packet.hpp.
Const_buffer_sequence
using flow::net_flow::Low_lvl_packet::Const_buffer_sequence = std::vector<Const_buffer>
Short-hand for sequence of immutable buffers; i.e., a sequence of 1 or more scattered areas in memory.
This is a model of the ConstBufferSequence model in boost.asio, which means a const reference to this can be passed to boost.asio scatter-gathering send functions such as Udp_socket::async_send_to(); the scattered buffers represented by an instance of this type will be, at high performance, gathered into a single UDP datagram and sent over the wire if possible.
Definition at line 188 of file low_lvl_packet.hpp.
rcv_wnd_t
using flow::net_flow::Low_lvl_packet::rcv_wnd_t = uint32_t
Type used to store the size of m_rcv_wnd member in a couple of different packet types.
Definition at line 202 of file low_lvl_packet.hpp.
rexmit_id_t
using flow::net_flow::Low_lvl_packet::rexmit_id_t = uint8_t
Type used to store the retransmission count in DATA and ACK packets.
Why 8 bits? This handles up 255 retransmissions, which is long after we'd kill the connection anyway.
Definition at line 199 of file low_lvl_packet.hpp.
security_token_t
using flow::net_flow::Low_lvl_packet::security_token_t = uint64_t
Type used for m_security_token member of a couple different packet types.
Definition at line 191 of file low_lvl_packet.hpp.
Constructor & Destructor Documentation
Low_lvl_packet()
flow::net_flow::Low_lvl_packet::Low_lvl_packet (log::Logger * logger_ptr) explicit protected
Constructs packet with uninitialized (essentially random) values.
This is not public, because a Low_lvl_packet is meaningless without being of some specific sub-type referring to an actual packet (e.g., Ack_packet, Rst_packet, etc.). (The presence of pure virtual methods would probably accomplish this too, but it's nice to be explicit.)
Parameters
logger_ptr Logger to use subsequently.
Definition at line 54 of file low_lvl_packet.cpp.
References type_to_ostream().
Member Function Documentation
create_from_raw_data_packet()
Low_lvl_packet::Ptr flow::net_flow::Low_lvl_packet::create_from_raw_data_packet (log::Logger * logger_ptr, util::Blob * raw_packet, bool prefer_no_move) static
Constructs packet on the heap with values determined by the given raw binary data as presumably received from the wire and originally serialized by a compatible serializing Node.
The returned value is a reference-counted pointer with a reference count of 1 (i.e., no other references to underlying object have been saved anywhere by the time method returns).
It is the opposite of serialize_to_raw_data() but not symmetrically efficient; where the latter produces a sequence of pointers/lengths of already present areas of memory (no copying), the present method copies the raw data into a new structure and is thus less efficient.
Suppose ptr is returned. Then *ptr is of polymorphic type Low_lvl_packet* but actually is of some specific sub-type (like Ack_packet*). typeid(*ptr) can be used to determine the exact type. In particular one can write things like: bool is_ack = typeid(*ptr) == typeid(Ack_packet). Of course, in many cases one may call one of a number of virtual methods of Low_lvl_packet to get type-specific polymorphic behavior.
See also
m_type_ostream_manip() for easy way to output human-readable version of typeid(*ptr).name(), where ptr is the value returned.
Parameters
raw_packet Pointer to entire packet raw buffer as received over the wire. Upon return, the state of *raw_packet is not known; and caller retains ownership of it (e.g., can read another datagram into it if desired). As of this writing it will either remain unchanged or be emptied (via a move elsewhere) – but ideally code without relying on either specific outcome.
prefer_no_move If true, the method should (if at all reasonable) not alter raw_packet->capacity() (in particular it should not use move semantics to send its contents to another data structure); otherwise it should be free to do so (i.e., if it considers doing so beneficial for performance reasons).
logger_ptr Will be used to log within this method as well as be saved as the Logger* in the new Low_lvl_packet created and returned (if any).
Returns
A null pointer on failure; otherwise pointer to an object of some sub-type of Low_lvl_packet.
Definition at line 381 of file low_lvl_packet.cpp.
References flow::util::buffers_dump_string(), FLOW_LOG_DATA, FLOW_LOG_SET_CONTEXT, FLOW_LOG_TRACE, FLOW_LOG_WARNING, FLOW_LOG_WITHOUT_CHECKING, flow::log::Log_context::get_log_component(), m_aux_raw_data, flow::net_flow::Low_lvl_packet::Aux_raw_data::m_opt_rexmit_on_raw, m_packed, flow::net_flow::Low_lvl_packet::Aux_raw_data::m_reserved2, flow::log::S_DATA, flow::log::S_TRACE, flow::log::Logger::should_log(), and type_id_native_to_raw().
Referenced by flow::net_flow::Node::handle_incoming().
create_uninit_packet()
template<typename Low_lvl_packet_sub > boost::shared_ptr< Low_lvl_packet_sub > flow::net_flow::Low_lvl_packet::create_uninit_packet (log::Logger * logger_ptr) static
Constructs packet with uninitialized (essentially random) values, of the Low_lvl_packet sub-type specified as the template parameter (Ack_packet, Rst_packet, etc.).
Since any constructor is not public, this is the only way to instantiate a blank Low_lvl_packet sub-object.
Compiler template parameter inference should make the following work, so the template parameter can be omitted.:
shared_ptr<Ack_packet> = create_uninit_packet(get_logger());
// ^-- Low_lvl_packet_sub was inferred to be Ack_packet based on the left hand side of the assignment.
Template Parameters
Low_lvl_packet_sub Any type deriving from Low_lvl_packet.
Parameters
logger_ptr Logger to use subsequently in the new object.
Returns
Ref-counted pointer to newly created object of the specified type. If you need an up-cast pointer, use create_uninit_packet_base().
Definition at line 1388 of file low_lvl_packet.hpp.
create_uninit_packet_base()
template<typename Low_lvl_packet_sub > Low_lvl_packet::Ptr flow::net_flow::Low_lvl_packet::create_uninit_packet_base (log::Logger * logger_ptr) static
A simple convenience method that casts the result of create_uninit_packet() from shared_ptr<T>, where T is a sub-type of Low_lvl_packet, to shared_ptr<Low_lvl_packet> a/k/a Ptr.
Parameters
logger_ptr See create_uninit_packet().
Returns
See create_uninit_packet() (but cast to a type compatible with the polymorphic base type).
Definition at line 1399 of file low_lvl_packet.hpp.
References flow::util::Shared_ptr_alias_holder< boost::shared_ptr< Low_lvl_packet > >::ptr_cast().
deserialize_type_specific_data_from_raw_data_packet()
virtual bool flow::net_flow::Low_lvl_packet::deserialize_type_specific_data_from_raw_data_packet (Const_buffer * raw_buf, bool prefer_no_move, util::Blob * raw_packet) private pure virtual
virtual helper for create_from_raw_data_packet() that fills out the fields of *this that are not in Low_lvl_packet but rather in the sub-type.
*raw_buf must represent the area of create_from_raw_data_packet()'s *raw_buf argument immediately following the Common Header, which is the area deserialized into Low_lvl_packet proper. Hence *raw_buf must point to and contain the length of the rest of that input buffer. The present method must then deserialize it into the sub-object's own fields.
Parameters
raw_buf Pointer to immutable buffer just past the input raw packet data's Common Header area. Note that while the underlying area is immutable (hence the type Const_buffer!), *raw_buf itself may be modified (i.e., the area to which it will refer on exit is undefined).
prefer_no_move See create_from_raw_data_packet().
raw_packet See create_from_raw_data_packet(). raw_buf must start somewhere within it and be sized to go exactly to its end.
Returns
false if create_from_raw_data_packet() should return Ptr() (error); true if deserialization successful.
Implemented in flow::net_flow::Syn_packet, flow::net_flow::Syn_ack_packet, flow::net_flow::Syn_ack_ack_packet, flow::net_flow::Data_packet, flow::net_flow::Ack_packet, and flow::net_flow::Rst_packet.
native_is_big_endian()
constexpr bool flow::net_flow::Low_lvl_packet::native_is_big_endian () static constexpr protected
Returns true, at compile time, if and only if the native memory representation is big-endian, meaning, for example, the value uint32_t(1) is stored as the bytes, in order, 0x00 0x00 0x00 0x01, and not the reverse.
Can be used in a compile-time check such as static_assert().
Returns
See above.
Definition at line 1404 of file low_lvl_packet.hpp.
serialize_common_header_to_raw_data()
size_t flow::net_flow::Low_lvl_packet::serialize_common_header_to_raw_data (Const_buffer_sequence * raw_bufs) const protected
Helper for serialize_to_raw_data() implementations in sub-types that encodes the header common to all packet types, starting with the packet type ID leading that header.
Parameters
raw_bufs See serialize_to_raw_data(). Header fields are encoded and appended to this.
Returns
See serialize_to_raw_data(). The total # of bytes encoded and appended to *raw_bufs by the call.
Definition at line 159 of file low_lvl_packet.cpp.
References m_aux_raw_data, m_opt_rexmit_on, flow::net_flow::Low_lvl_packet::Aux_raw_data::m_opt_rexmit_on_raw, m_packed, flow::net_flow::Low_lvl_packet::Aux_raw_data::m_reserved2, and type_id_native_to_raw().
serialize_to_raw_data()
virtual size_t flow::net_flow::Low_lvl_packet::serialize_to_raw_data (Const_buffer_sequence * raw_bufs) const pure virtual
Serializes the current logical packet data from *this into the given Const_buffer_sequence, which is a sequence of pointers and lengths of existing scattered areas in memory, presumably for transmission over the wire to a compatible serializing Node.
It is the opposite of create_from_raw_data_packet() but not symmetrically efficient; where the latter copies the raw data into a new structure, the present method produces a sequence of pointers/lengths of already present areas of memory (no copying) and is thus more efficient.
The input *raw_bufs is appended to and is not cleared by this method. Thus one may use this method to produce a larger buffer sequence of which the serialization of *this is only a part (possibly in the middle somewhere).
Behavior is undefined if one modifies *this after calling the present method. It is safer to run this on a const Low_lvl_packet rather than a mutable Low_lvl_packet.
Warning
This efficiency comes with an important caveat: the generated additions to *raw_bufs will remain valid only while *this exists. If its destructor runs, the buffers added here will become invalid, and accessing them will result in undefined behavior.
Parameters
raw_bufs Pointer to the sequence of Const_buffers into which we will append pointers/lengths of serialized data.
Returns
Size in bytes of the data references to which have been appended to *raw_bufs; Already present data are not included.
Implemented in flow::net_flow::Syn_packet, flow::net_flow::Syn_ack_packet, flow::net_flow::Syn_ack_ack_packet, flow::net_flow::Data_packet, flow::net_flow::Ack_packet, and flow::net_flow::Rst_packet.
Referenced by serialize_to_raw_data_and_log().
serialize_to_raw_data_and_log()
size_t flow::net_flow::Low_lvl_packet::serialize_to_raw_data_and_log (Const_buffer_sequence * raw_bufs) const
Identical to serialize_to_raw_data() but adds log-level-appropriate logging after the operation.
Parameters
raw_bufs See serialize_to_raw_data().
Returns
See serialize_to_raw_data().
Definition at line 130 of file low_lvl_packet.cpp.
References flow::util::buffers_dump_string(), FLOW_LOG_DATA_WITHOUT_CHECKING, FLOW_LOG_TRACE_WITHOUT_CHECKING, flow::log::Log_context::get_log_component(), flow::log::Log_context::get_logger(), m_type_ostream_manip, flow::log::S_DATA, flow::log::S_TRACE, and serialize_to_raw_data().
to_ostream()
std::ostream & flow::net_flow::Low_lvl_packet::to_ostream (std::ostream & os, bool verbose = false) const protected virtual
Writes a multi-line representation of *this to an output stream.
Unless the sub-type needs to add no information of its own (as of this writing, the case for Rst_packet), this implementation (of this virtual method) is only present as a utility for the sub-types. The sub-type is recommended to first call this implementation; then add type-specific lines afterwards, ending with a newline. Following this recommendation will result in uniform, decent-looking overall output.
Note
This is protected, because it is meant only to be used in the implementation of the ostream manipulators m_verbose_ostream_manip and m_concise_ostream_manip, which are public and to be used by users of this type.
Parameters
os The output stream to use. Normally I'd make this a pointer, but this non-constant reference is fairly typical in STL and the world in general, for ostream in particular.
verbose If false, output suitable for TRACE level logging is produced; otherwise for DATA level logging.
Returns
os.
Reimplemented in flow::net_flow::Syn_packet, flow::net_flow::Syn_ack_packet, flow::net_flow::Syn_ack_ack_packet, flow::net_flow::Data_packet, and flow::net_flow::Ack_packet.
Definition at line 912 of file low_lvl_packet.cpp.
Referenced by flow::net_flow::Syn_packet::to_ostream(), flow::net_flow::Syn_ack_packet::to_ostream(), flow::net_flow::Syn_ack_ack_packet::to_ostream(), flow::net_flow::Data_packet::to_ostream(), and flow::net_flow::Ack_packet::to_ostream().
type_id_native_to_raw()
const uint8_t & flow::net_flow::Low_lvl_packet::type_id_native_to_raw (const std::type_info & type_id) static private
Helper that looks up the Packet_type_info::m_raw_type_id value for the given typeid(p), where p refers to an instance of a concrete sub-type of Low_lvl_packet.
Note that is returns a reference, and indeed the referred to memory will remain valid and unmodified throughout the program's runtime. Therefore, it can be used for serialization without copying.
Implementation note
It would be nice to make this constexpr, as then it can be used in switch() statement conditionals. Unfortunately, at least as of C++17, this is not possible with our current implementation: S_NATIVE_TYPE_ID_TO_PACKET_TYPE_INFO is an unordered_map (as of this writing), and that is not a "literal" type (in other words, lookups in it are not done at compile time, even when for a human it would seem clearly possible... iterators and such are involved, and that goes beyond what constexpr evaluation can do).
Parameters
type_id See type_id_to_str().
Returns
Reference to a constant area of memory.
Definition at line 119 of file low_lvl_packet.cpp.
References S_NATIVE_TYPE_ID_TO_PACKET_TYPE_INFO.
Referenced by create_from_raw_data_packet(), and serialize_common_header_to_raw_data().
type_id_to_str()
const std::string & flow::net_flow::Low_lvl_packet::type_id_to_str (const std::type_index & type_id) static
Returns a brief (a few characters) string description of the given packet type given as type_index(typeid(p)), where p is a reference to an instance of a concrete Low_lvl_packet sub-type.
Parameters
type_id See above. If the p points to a value of some other type, behavior is undefined.
Returns
Reference to a string without newlines or other whitespace: "DATA", "ACK", "SYN_ACK_ACK", etc.
Definition at line 108 of file low_lvl_packet.cpp.
References S_NATIVE_TYPE_ID_TO_PACKET_TYPE_INFO.
Referenced by flow::net_flow::Peer_socket_info::output_pkt_count_key(), and type_to_ostream().
type_to_ostream()
std::ostream & flow::net_flow::Low_lvl_packet::type_to_ostream (std::ostream & os) const private
Writes a brief representation of typeid(*this) – i.e., the packet type (ACK, RST, etc.) – to an output stream.
See also type_id_to_str().
Note
This is private, because it is meant only to be used in the implementation of the ostream manipulator m_type_ostream_manip, which is public and to be used by users of this type.
Parameters
os The output stream to use. Normally I'd make this a pointer, but this non-constant reference is fairly typical in STL and the world in general, for ostream in particular.
Returns
os.
Definition at line 1053 of file low_lvl_packet.cpp.
References type_id_to_str().
Referenced by Low_lvl_packet().
Member Data Documentation
m_aux_raw_data
Aux_raw_data flow::net_flow::Low_lvl_packet::m_aux_raw_data mutable private
Auxilliary data area necessary for serialize_to_raw_data() to work.
This is explained in doc header for Aux_raw_data.
It is declared mutable, because the conceptual state contained within a Low_lvl_packet is expressed via its public non-const data members. m_aux_raw_data is merely a helper data store for the const method serialize_to_raw_data(). Since that method is const, this should be mutable, like a performance cache of sorts, only not exactly.
Definition at line 571 of file low_lvl_packet.hpp.
Referenced by create_from_raw_data_packet(), and serialize_common_header_to_raw_data().
m_concise_ostream_manip
const Function<std::ostream& (std::ostream&)> flow::net_flow::Low_lvl_packet::m_concise_ostream_manip
ostream manipulator (argument to ostream <<) that will output packet info suitable for TRACE log level.
Definition at line 251 of file low_lvl_packet.hpp.
m_dst_port
flow_port_t flow::net_flow::Low_lvl_packet::m_dst_port
Flow-protocol port # of socket in receiving Node.
Definition at line 233 of file low_lvl_packet.hpp.
m_opt_rexmit_on
bool flow::net_flow::Low_lvl_packet::m_opt_rexmit_on
Option indicating whether this connection is using retransmission or not.
This value must not change over the course of a connection and is provided in each packet for simpler deserialization (so that the latter can proceed completely without having to check the connection properties).
For a given connection handshake, the SYN receiver should either disconnect/RST or respond with SYN_ACK. If it responds with SYN_ACK, it indicates agreement to abide by this option for the rest of the connection.
Definition at line 222 of file low_lvl_packet.hpp.
Referenced by flow::net_flow::Data_packet::deserialize_type_specific_data_from_raw_data_packet(), flow::net_flow::Ack_packet::deserialize_type_specific_data_from_raw_data_packet(), and serialize_common_header_to_raw_data().
m_src_port
flow_port_t flow::net_flow::Low_lvl_packet::m_src_port
Flow-protocol port # of socket in sending Node.
Definition at line 231 of file low_lvl_packet.hpp.
m_type_ostream_manip
const Function<std::ostream& (std::ostream&)> flow::net_flow::Low_lvl_packet::m_type_ostream_manip
ostream manipulator (argument to ostream <<) that will output packet's type ("ACK", "RST", etc.).
Definition at line 245 of file low_lvl_packet.hpp.
Referenced by flow::net_flow::Syn_packet::deserialize_type_specific_data_from_raw_data_packet(), flow::net_flow::Syn_ack_packet::deserialize_type_specific_data_from_raw_data_packet(), flow::net_flow::Syn_ack_ack_packet::deserialize_type_specific_data_from_raw_data_packet(), flow::net_flow::Data_packet::deserialize_type_specific_data_from_raw_data_packet(), flow::net_flow::Ack_packet::deserialize_type_specific_data_from_raw_data_packet(), flow::net_flow::Rst_packet::deserialize_type_specific_data_from_raw_data_packet(), and serialize_to_raw_data_and_log().
m_verbose_ostream_manip
const Function<std::ostream& (std::ostream&)> flow::net_flow::Low_lvl_packet::m_verbose_ostream_manip
ostream manipulator (argument to ostream <<) that will output packet info suitable for DATA log level.
Definition at line 248 of file low_lvl_packet.hpp.
S_NATIVE_TYPE_ID_TO_PACKET_TYPE_INFO
const boost::unordered_map< std::type_index, Low_lvl_packet::Packet_type_info > flow::net_flow::Low_lvl_packet::S_NATIVE_TYPE_ID_TO_PACKET_TYPE_INFO static private
Mapping from native typeid(), a/k/a packet type (for all possible packet types), to the set of properties of that packet type.
The keys are every possible value of type_index(typeid(p)), where p is a reference to an instance of any concrete Low_lvl_packet sub-type.
Implementation note
An alternative way to implement this mechanism (as of this writing, raw type IDs and brief string descriptions per packet type) is to use virtual liberally, combined with a switch if needed. (Note, also, that a way to index – such as in an unordered container – by packet type is necessary elsewhere. We use type_index(typeid())) now, but a [worse] alternative is to have virtual type IDs returned for each Low_lvl_packet sub-type.) I could explain at length all the reasons why the chosen way is superior, but let me just give you the conclusion: I originally tried it the virtual/switch way. Instead of the raw type IDs and string descriptions being conveniently encapsulated in the present map (where there's little to no chance of conflicting values), they were distributed across virtual implementations. This was less maintainable; nor did it improve OO style, since the raw type ID values (at least) were still inter-dependent (were not allowed to conflict) in any case. The present solution does not pretend the actual contents of these values are of no interest to Low_lvl_packet itself (as opposed to the sub-types), and in not having to pretend this, all related code is quite a bit more compact and a bit more maintainable as well.
Definition at line 558 of file low_lvl_packet.hpp.
Referenced by type_id_native_to_raw(), and type_id_to_str().
The documentation for this struct was generated from the following files:
net_flow/detail/low_lvl_packet.hpp
net_flow/detail/low_lvl_packet.cpp